### ISSUE TITLE
Can't change roles after setting in Server dialog

### ISSUE THREAD

**Issue by JayAnderson-Clayton** [pgadmin-org/pgadmin4#6560] opened 2023-07-11 20:41 UTC
I went from pgAdmin 6 to 7, and now I'm having problems connecting to my database.
The error I get is 
Failed to setup the role syntax error at or near "-" LINE 1: SET ROLE TO AWSData-PG-User-Dev-Dept ^

I think the issue is the hyphens we have in our role names.  That line is not correct syntax but if I put quotes around it and execute the command, it works. I tried putting quotes around the role name in the server dialog, but I still into a different error instead (Failed to setup the role the cursor is closed)

**Comment by akshay-joshi** [comment] 2023-07-12 04:03
Duplicate of #6531

**Closed by akshay-joshi** 2023-07-12 04:03 UTC
