### ISSUE TITLE
the pgadmin 4 quit unexpectedly and wouldn't open

### ISSUE THREAD

**Issue by sumana1810** [pgadmin-org/pgadmin4#6709] opened 2023-08-22 02:48 UTC
I installed the app from m1 Mac 13.5.1. 
downloaded the version 15.4 

the app ran once but won't re-open

**Comment by gunduzl** [comment] 2023-08-23 11:59
Some problem to me also and my pc is m1 mac

**Comment by yogeshmahajan-1903** [comment] 2023-08-24 03:45
pgAdmin yet does not support M1 Mac platform.

**Comment by nikhil-mohite** [comment] 2023-08-25 11:25
Hi @sumana1810,
Please download pgAdmin 4 v7.6 from [https://www.pgadmin.org/download/pgadmin-4-macos/](https://www.pgadmin.org/download/pgadmin-4-macos/)

Duplicate of #6625

**Closed by nikhil-mohite** 2023-08-25 11:25 UTC
