### ISSUE TITLE
unable to connect to server (passwords with special characters \ ')

### ISSUE THREAD

**Issue by ASMag** [pgadmin-org/pgadmin4#5903] opened 2023-02-28 18:53 UTC
Hi

since I had installed pgAdmin 6.20, I have connection problems. I am using several database roles (users) at the same PostgreSQL server. Only some users authentications are still working. I guess the difference are special characters in the users passwords:
1) \ (backslash in a password)
=> authentication failed, pgAdmin log:
> 2023-02-28 14:50:43,047: ERROR    pgadmin:                Could not connect to server(#5) - '[servername]'.
> Error: connection to server at "127.0.0.1", port 15432 failed: FATAL:  password authentication failed for user "username"

2) ...'**dU** (password ends with a single quote followed by "dU")
=> authentication failed, pgAdmin log:
> 2023-02-28 14:51:17,438: ERROR     pgadmin:            Could not connect to server(#10) - '[servername]'.
> Error: invalid dsn: missing "=" after "**dU**'" in connection info string

Connection via command line program `[pgAdmin-InstallDir]\runtime\psql.exe` still works.

At least at pgAdmin version 6.20 there are seems to be problems with special characters in passwords. Version 6.9 is not affected.

Used software: 
pgAdmin version: 6.20 windows 10
postgreSQL version: 12.12 ubuntu server 20.04

I guess the password quoting or the mechanism of transmitting a password from GUI to the communication tool (maybe psql) was changed by the developers.

If more details are required do not be hesitate to give me a pointer.

Regards
ASMag

**Comment by yogeshmahajan-1903** [comment] 2023-03-01 05:08
@ASMag 
Seems to be duplicate of https://github.com/pgadmin-org/pgadmin4/issues/5862. Fix will be available in next release.
By the time you can check on nightly build from here https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/

**Closed** 2023-03-01 05:08 UTC
Labels: Bug
