### ISSUE TITLE
pgAdmin stopped output of messages during procedure execution

### ISSUE THREAD

**Issue by istolarov** [pgadmin-org/pgadmin4#6643] opened 2023-08-01 16:38 UTC
After v.6.21, when executing stored function, you no longer see output of std out messages until procedures ends execution. Then everything is printed at once. It was a nice feature to see what's going on while function was executing...

**Comment by adityatoshniwal** [comment] 2023-08-02 10:18
HI @istolarov  Did you try pgAdmin 7.5?

**Comment by alessandroDrogal** [comment] 2023-08-03 12:41
Same problem in pgAdmin 7.5

**Comment by akshay-joshi** [comment] 2023-08-04 11:54
Duplicate of #6420

**Closed by akshay-joshi** 2023-08-04 11:54 UTC
