### ISSUE TITLE
Login fails with more than one authentication source configured in 7.0

### ISSUE THREAD

**Issue by cklein05** [pgadmin-org/pgadmin4#6151] opened 2023-04-19 06:59 UTC
After having upgraded to version 7.0, no user was able to log into pgAdmin 4 anymore. For any login attempt, the message _Incorrect username or password._ is shown. Logon credentials have been entered correctly and have worked well before.

pgAdmin runs in server mode on a recent Ubuntu 22.04 LTS and was installed/upgraded through pgAdmin's Debian/Ubuntu repository.

Login fails, if there are more than one authentication source is configured. In this certain case, two authentication sources, `ldap` and `internal`, are configured:

``` python
AUTHENTICATION_SOURCES = ['ldap', 'internal']
```
Although I cannot test other authentication sources, I guess that the same problem arises with other authentication sources as well (as long as there are more than one sources).

Login succeeds, if only one authentication source is configured at a time. That is, using only ``ldap`` or using only ``internal`` works without any issues.

**Comment by yogeshmahajan-1903** [comment] 2023-04-19 07:49
@cklein05 
Could you please share the pgAdmin logs?

**Comment by cklein05** [comment] 2023-04-19 08:54
Sorry, forgot the logs. There's not much in the logs. Only after setting
``` python
Debug = true
[...]
FILE_LOG_LEVEL = logging.DEBUG
```
some entries get logged while login fails:

```
=== APPLICATION STARTUP ===

2023-04-19 10:46:10,803: INFO   pgadmin:        ########################################################
2023-04-19 10:46:10,803: INFO   pgadmin:        Starting pgAdmin 4 v7.0...
2023-04-19 10:46:10,803: INFO   pgadmin:        ########################################################
2023-04-19 10:46:10,803: DEBUG  pgadmin:        Python syspath: ['/usr/pgadmin4/web', '/etc/pgadmin', '/usr/pgadmin4/web', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/usr/pgadmin4/venv/lib/python3.10/site-packages']
2023-04-19 10:46:11,910: INFO   pgadmin:        Registering blueprint module: <AboutModule 'about'>
2023-04-19 10:46:11,912: INFO   pgadmin:        Registering blueprint module: <AuthenticateModule 'authenticate'>
2023-04-19 10:46:11,913: INFO   pgadmin:        Registering blueprint module: <BrowserModule 'browser'>
2023-04-19 10:46:13,306: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-04-19 10:46:13,318: INFO   pgadmin:        Registering blueprint module: <DashboardModule 'dashboard'>
2023-04-19 10:46:13,318: INFO   pgadmin:        Registering blueprint module: <HelpModule 'help'>
2023-04-19 10:46:13,319: INFO   pgadmin:        Registering blueprint module: <MiscModule 'misc'>
2023-04-19 10:46:14,344: INFO   pgadmin:        Registering blueprint module: <PreferencesModule 'preferences'>
2023-04-19 10:46:14,347: INFO   pgadmin:        Registering blueprint module: <PgAdminModule 'redirects'>
2023-04-19 10:46:14,348: INFO   pgadmin:        Registering blueprint module: <SettingsModule 'settings'>
2023-04-19 10:46:14,352: INFO   pgadmin:        Registering blueprint module: <ToolsModule 'tools'>
2023-04-19 10:46:14,865: DEBUG  pgadmin:        Config server mode: True
2023-04-19 10:46:14,866: DEBUG  pgadmin:        Not running under the desktop runtime, port: 5050

=== LOGIN ATTEMPT ===

2023-04-19 10:46:22,389: DEBUG  pgadmin:        Authentication initiated via source: ldap
2023-04-19 10:46:23,011: DEBUG  pgadmin:        Authentication initiated via source: internal

=== LOGIN FAILED WITH "Incorrect username or password" ===
=== NO MORE LOG ENTRIES ===
```

**Comment by alecl** [comment] 2023-04-19 23:02
I'm running into this issue with v7 connecting to Amazon Aurora RDS databases for Postgres 14.6. Downgrade back to 6.x works fine again.

**Comment by yogeshmahajan-1903** [comment] 2023-04-20 09:27
@cklein05 
Would you mind sharing LDAP configuration? We are able to login to pgadmin successfully with AUTHENTICATION_SOURCES = ['ldap','internal'].

**Comment by yogeshmahajan-1903** [comment] 2023-04-20 09:27
> I'm running into this issue with v7 connecting to Amazon Aurora RDS databases for Postgres 14.6. Downgrade back to 6.x works fine again.

Are you facing issue while logging in pgadmin? or while connecting DB server?

**Comment by yogeshmahajan-1903** [comment] 2023-04-20 11:17
@cklein05 

With AUTHENTICATION_SOURCES = ['ldap','internal'], only internal users are not able to login. LDAP users are able to login successfully. Could you please confirm this behaviour?
This will be fixed in upcoming release,

**Comment by cklein05** [comment] 2023-04-20 11:40
Yes, I can confirm that. Actually, ldap based logins work if both ldap and internal have been configured. Looking forward to getting the next release.

However, actually the ldap users weren't able to login as well. Now, I know the reason: the ldap users tried to log into pgAdmin using their email address, which doesn't work as they need to specify their ldap username (maybe that has worked in the past?)

In any case, thank you very much for helping and fixing the  bug :)

**Comment by alecl** [comment] 2023-04-21 12:59
> > I'm running into this issue with v7 connecting to Amazon Aurora RDS databases for Postgres 14.6. Downgrade back to 6.x works fine again.
> 
> Are you facing issue while logging in pgadmin? or while connecting DB server?

While connecting to the DB server. There's nothing of note in the RDS error postgres log file for PgAdmin 7.x connection failures.

With PgAdmin 6.x, a proper connection for me looks like this:

2023-04-19 22:18:06 UTC:<ip>(33032):postgres@mydb:[14082]:LOG:  connection authenticated: identity="postgres" method=md5 (/rdsdbdata/config/pg_hba.conf:13)
2023-04-19 22:18:06 UTC:<ip>(33032):postgres@mydb:[14082]:LOG:  connection authorized: user=postgres database=mydb SSL enabled (protocol=TLSv1.2, cipher=AES128-SHA256, bits=128)

**Comment by adityatoshniwal** [comment] 2023-04-27 08:32
Tried setting `AUTHENTICATION_SOURCES=['ldap', 'internal']` with no ldap setup. Fallbacks to internal. Works fine on https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-04-26/apt/

**Closed by adityatoshniwal** 2023-04-27 08:32 UTC
Labels: Bug, EDB Sprint 141

**Comment by landi1993** [comment] 2023-05-16 06:46
I can confirm this behaviour that LDAP login is working while internal login is not working when configured as:
`AUTHENTICATION_SOURCES=['ldap', 'internal']`

However, when i configure it vice versa (`AUTHENTICATION_SOURCES=['internal', 'ldap']`), authentication is working for both internal users and ldap users. 

Running pgadmin4 with HELM chart pgadmin4-1.15.1 which runs a pgAdmin4 7.0 image

**Comment by yogeshmahajan-1903** [comment] 2023-05-16 07:48
@landi1993 
Could you please try with pgAdmin 4 version 7.1?

**Comment by landi1993** [comment] 2023-05-23 12:15
> @landi1993 Could you please try with pgAdmin 4 version 7.1?

pgAdmin4 Version 7.1 is working as expected! :-) I cannot recreate previous behaviour.
