### ISSUE TITLE
In processes time is still going after terminating a process

### ISSUE THREAD

**Issue by HappySonic** [pgadmin-org/pgadmin4#6300] opened 2023-05-19 12:07 UTC
It`s maybe a minor UI bug or it all was by design. If we we look at the processes in UI and check Time Taken column, then we can find that it doesn`t stop after terminating restore.
Steps to reproduce:
1. Start backup restore
2. Switch to processes page
3. Check Time Taken column
4. Stop backup restore
5. Check Time Taken again

Maybe it`s still terminating, but then it`s better to have distinct rows about how much time we were doing restore and process terminating.
![image](https://github.com/pgadmin-org/pgadmin4/assets/50570423/1d375842-42a8-4aea-9d3c-e1be40d9d5e0)
![image](https://github.com/pgadmin-org/pgadmin4/assets/50570423/968cf2dd-b416-4d31-bd19-7599c63c3dd5)

**Comment by adityatoshniwal** [comment] 2024-05-03 11:43
@HappySonic Are you still seeing this issue with latest pgAdmin version? We're not able to reproduce this.

**Comment by HappySonic** [comment] 2024-05-03 11:46
Hi! No, didn`t see it in a while. We updated db and now it`s fine. Thanks

**Comment by adityatoshniwal** [comment] 2024-05-03 12:08
Thanks for confirmation. Closing.

**Closed by adityatoshniwal** 2024-05-03 12:08 UTC
Labels: Bug
