### ISSUE TITLE
Registered server connection parameter "Port" is not properly displayed

### ISSUE THREAD

**Issue by prasadrahul** [pgadmin-org/pgadmin4#7278] opened 2024-03-13 07:14 UTC
Registered server connection parameter "Port" is not properly displayed

Steps:
1. Open pgAdmin web interface
2. Try to register multiple server with different host and port details.
3. Now open registered server properties and look for connection properties
4. Here Port property is always showing to 5432 , even though you saved different port

**Comment by yogeshmahajan-1903** [comment] 2024-03-20 04:18
@prasadrahul 
I am not able to reproduce the issue. Can you please share screenshot? Also when did you connect to those servers does all of them shows same version?

**Comment by anilsahoo20** [comment] 2024-03-29 11:30
As per user's comment, closing the issue.

**Closed by anilsahoo20** 2024-03-29 11:30 UTC
