### ISSUE TITLE
High Memory and CPU Usage in pgAdmin 8.12 Web Interface Causes Browser Freezing

### ISSUE THREAD

**Issue by MostafaHassanzadeh** [pgadmin-org/pgadmin4#8113] opened 2024-11-09 22:12 UTC
n version 8.12 of pgAdmin, there is a bug that causes excessive memory and CPU usage on the client side when using the web interface. This issue leads to frequent browser freezing, significantly impacting usability. It appears that the web interface consumes resources continuously, even during idle periods.

Steps to reproduce:

Open the pgAdmin 8.12 web interface in any modern browser (tested on Chrome, Firefox).
Perform any basic operations, such as viewing tables or running queries, or leave the interface idle.
Monitor memory and CPU usage, which will spike and remain high over time.
The browser becomes unresponsive or crashes after prolonged use.
Expected behavior: The web interface should maintain stable memory and CPU usage without causing the browser to freeze.

Please address this issue in future updates, as it limits the usability of pgAdmin for regular database management tasks.

**Comment by masoudChd** [comment] 2024-11-11 12:02
This is a critical problem that leads to major errors and forces an exit from the web version.

In many scenarios, I encountered this issue even in the very initial steps, not only in more complex ones. For example, it occurred when simply selecting a database or checking statistics from the dashboard.

**Comment by yogeshmahajan-1903** [comment] 2024-11-11 12:14
@masoudChd 
Can you please get us profile data from chrome? Open developer tools > Performance tool > Start recording.

**Comment by MostafaHassanzadeh** [comment] 2024-11-14 22:10
Due to security concerns, I cannot publish the profile file itself, so I'll just upload a photo of it.
![Screenshot from 2024-11-15 01-35-00](https://github.com/user-attachments/assets/886c870e-69a3-438f-944f-db908bbb59f8)

**Comment by yogeshmahajan-1903** [comment] 2024-11-22 04:32
@MostafaHassanzadeh 
Unfortunately, I am not able to reproduce the issue. Are there some specific activities that a causing this issue? Can you please try closing the dashboard and check if there is any difference in CPU usage?
Also, can you please provide more information about platform? 
Does downgrading pgadmin version eliminates this issue?

**Closed** 2024-12-06 11:18 UTC

**Comment by sourabhb2** [comment] 2024-12-19 12:43
I am using pgAdmin 8.11 and encountering a memory usage issue. After executing some SQL queries in pgAdmin, it fails to display the output, and the pod automatically restarts. Is there a solution to this issue.

**Comment by yogeshmahajan-1903** [comment] 2024-12-19 16:46
@sourabhb2 
What is CPU and memory configuration for your pods?

**Comment by RaGuL2k23** [comment] 2025-03-10 17:37
still in latest 9.1 version this issue exists my laptop became very hot . Nothing just it is idle that's it .It seems to be using a lot of cpu resource

**Comment by yogeshmahajan-1903** [comment] 2025-03-11 04:42
@RaGuL2k23 
Can you please provide CPU and memory configuration? Also graph showing CPU consumption?

**Comment by RaGuL2k23** [comment] 2025-03-12 17:14
mine is amd ryzen 5600h and 16gb ram     and for graph currently iam unable to show it as the issue appeared out randomly and mine normal usage will be between 1.9 to 2.5 ghz but at that time pgadmin alone was consuming a 15 % of my cpu at 3.89ghz which caused my laptop to go very hot and i immediately quit pgadmin quickly after seeing it
