### ISSUE TITLE
Query Tool Bugs in version 7.1

### ISSUE THREAD

**Issue by crevvy** [pgadmin-org/pgadmin4#6492] opened 2023-06-23 13:46 UTC
QUERY TOOL BUGS 
1. After editing a query and then executing, it does not see the changes in the query and instead runs the SQL that was previously in the window before the edits.  
2. After executing a query, it sometimes shows a message that a query has executed successfully but does not actually show any data from that query result. 
3. User is forced to open a new Query Tool window due to the above.

**Comment by dukesun** [comment] 2023-06-26 03:46
This is a bug.I'm having the same issue.

**Comment by dukesun** [comment] 2023-06-26 03:50
![企业微信截图_aeff69f3-d90d-41a9-9afd-654a60a61877](https://github.com/pgadmin-org/pgadmin4/assets/16145083/e1d1ad23-ab24-4dfa-b6d8-ae13f3dcbc9d)
![企业微信截图_3a5c4541-823b-4009-9b8e-aef501f574cf](https://github.com/pgadmin-org/pgadmin4/assets/16145083/308b89e4-3e0f-4427-9f45-3195f1d0f49a)

**Comment by adityatoshniwal** [comment] 2023-06-26 05:22
@crevvy  @dukesun Can you try - https://github.com/pgadmin-org/pgadmin4/issues/6163#issuecomment-1549032065?

**Comment by nikhil-mohite** [comment] 2023-06-30 11:35
Duplicate of #6163

**Closed by nikhil-mohite** 2023-06-30 11:35 UTC
