### ISSUE TITLE
Remove the usage of makeStyles

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#7363] opened 2024-04-09 08:42 UTC
The @mui/styles package is deprecated from React 18 - https://mui.com/system/styles/basics/
Use - https://mui.com/material-ui/customization/how-to-customize/#2-reusable-component.

**Comment by adityatoshniwal** [comment] 2024-06-11 09:22
Found few ui issues:
<img width="1140" alt="Pasted Graphic" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/6af2eb63-e860-435c-9308-fc4d3518e440">

<img width="970" alt="Pasted Graphic 1" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/cfb4d225-ee21-465a-8ce9-110231f2b6f0">

<img width="698" alt="§ PostgreSQL 12" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/56301de6-81e6-4a1a-841e-340b6fd6683b">

**Comment by adityatoshniwal** [comment] 2024-06-11 12:32
Shortcuts should be on the right. Please check prev styling.
![Image](https://github.com/pgadmin-org/pgadmin4/assets/31855755/a201f491-c4d5-4433-b7cd-ca057a67e73a)

**Comment by pravesh-sharma** [comment] 2024-06-12 06:44
Run explain/analyze query and move to explain tab headers are being shown as buttons.

<img width="1309" alt="Screenshot 2024-06-06 at 12 06 18 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/58602753-7aca-4770-a435-cef5741a55a9">

**Comment by adityatoshniwal** [comment] 2024-06-12 11:44
Footer should stick to bottom.

![Image](https://github.com/pgadmin-org/pgadmin4/assets/31855755/3c1ccafb-e515-4f8e-bf43-76b5830d9be2)

**Comment by anilsahoo20** [comment] 2024-06-12 13:08
Query history right side query box must take 100% width.
<img width="999" alt="Screenshot 2024-06-12 at 6 35 39 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/122535205/e923a52f-7003-47d0-803b-529271532cbc">

**Comment by yogeshmahajan-1903** [comment] 2024-06-16 06:26
> Found few ui issues: <img alt="Pasted Graphic" width="1140" src="https://private-user-images.githubusercontent.com/31855755/338521356-6af2eb63-e860-435c-9308-fc4d3518e440.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTkzMzMsIm5iZiI6MTcxODUxOTAzMywicGF0aCI6Ii8zMTg1NTc1NS8zMzg1MjEzNTYtNmFmMmViNjMtZTg2MC00MzVjLTkzMDgtZmM0ZDM1MThlNDQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA2MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwMjBlYWM1ZGMyNzE0YWQ3NTI5YzgxNDhkNjUwMTljNGJiZmVlYWU5YjU3YWQzODkwYmFmYzU0ZDk0YmJmYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h6VHHS9iCvUloVhg5Gsi6L46kPgJmYKFkiprFBAmYlM">
> 

Not able to reproduce. Tried with docker snapshot also.

> <img alt="Pasted Graphic 1" width="970" src="https://private-user-images.githubusercontent.com/31855755/338521390-cfb4d225-ee21-465a-8ce9-110231f2b6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTkzMzMsIm5iZiI6MTcxODUxOTAzMywicGF0aCI6Ii8zMTg1NTc1NS8zMzg1MjEzOTAtY2ZiNGQyMjUtZWUyMS00NjVhLThjZTktMTEwMjMxZjJiNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA2MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNWJjZWZiYWYzNTdjZDYwMzM0YmJlMzE2YTY0M2QwNzk2YzE2YWUyZTQzYjdiNzY5YmRlN2YwNDkzZTgxYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4UVQVPyEc6HzR_kQTCGA64jkGQIGKaG1f5W41jDdxOg">
Partially fixed. Left border around add icon still present. Regression due to react table changes.

 <img alt="§ PostgreSQL 12" width="698" src="https://private-user-images.githubusercontent.com/31855755/338521418-56301de6-81e6-4a1a-841e-340b6fd6683b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTkzMzMsIm5iZiI6MTcxODUxOTAzMywicGF0aCI6Ii8zMTg1NTc1NS8zMzg1MjE0MTgtNTYzMDFkZTYtODFlNi00YTFhLTg0MWUtMzQwYjZmZDY2ODNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA2MjM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMmM5NTg0OTcxYWJkMDMxNDIwY2M2YjI2NzQ1NGJmYjNmMDJjOGQzYjk4NzFmMGMzOTMyNjE4Yzc5ZTVmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.29n4d2tEHynV_e9vCWtw1L3obrGq9y8amcaMyucHsCs">
Fixed.

**Comment by yogeshmahajan-1903** [comment] 2024-06-16 06:28
> Shortcuts should be on the right. Please check prev styling. ![Image](https://private-user-images.githubusercontent.com/31855755/338583122-a201f491-c4d5-4433-b7cd-ca057a67e73a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTk1NjUsIm5iZiI6MTcxODUxOTI2NSwicGF0aCI6Ii8zMTg1NTc1NS8zMzg1ODMxMjItYTIwMWY0OTEtYzRkNS00NDMzLWI3Y2QtY2EwNTdhNjdlNzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE2VDA2Mjc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNTIyZjAyOTk5NjhkMjM4NGEyYzk1ZTU5MjI1OTZjMTg3ZjE1YjNmM2IyNDAxOWE0OWNhNmI3NzRiYjQ2ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KTOHiQfobX44_yo_0o43QPdm1Qkj3ZxhnPnN8kpSxkw)

Fixed.

**Comment by yogeshmahajan-1903** [comment] 2024-06-16 06:28
> Run the explain/analyze query and move to the explain tab, headers are being shown as buttons.
> 
> <img alt="Screenshot 2024-06-06 at 12 06 18 PM" width="1309" src="https://private-user-images.githubusercontent.com/111979571/338850838-58602753-7aca-4770-a435-cef5741a55a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTk1NjUsIm5iZiI6MTcxODUxOTI2NSwicGF0aCI6Ii8xMTE5Nzk1NzEvMzM4ODUwODM4LTU4NjAyNzUzLTdhY2EtNDc3MC1hNDM1LWNlZjU3NDFhNTVhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwNjI3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDExMTcxNDZhNjhlZGIwZjgwNDIzYzJkOTIyZGU5NGM5YWFjZDJiNWI5Y2JlNzk0N2I2MDg2ZDIyNThhMzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jWbnRMN_8xyZrXWAoT1JNuUeXGzIKyzxAbrTQZWgPwg">

Fixed.

**Comment by yogeshmahajan-1903** [comment] 2024-06-16 06:28
> Query history right side query box must take 100% width. <img alt="Screenshot 2024-06-12 at 6 35 39 PM" width="999" src="https://private-user-images.githubusercontent.com/122535205/338978410-e923a52f-7003-47d0-803b-529271532cbc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MTk1NjUsIm5iZiI6MTcxODUxOTI2NSwicGF0aCI6Ii8xMjI1MzUyMDUvMzM4OTc4NDEwLWU5MjNhNTJmLTcwMDMtNDdkMC04MDNiLTUyOTI3MTUzMmNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwNjI3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDRkZjdjZGYzM2Y5NWE0ZWY4MzEyOWJjMjVhZDllZWU4YzRlN2VmNjM5OTM1M2I5OGUzMzMyNzE5ODY4ZjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OR7sTn2A3AHToPcAyAC3kOk3GagRug8ShHRGXKjYjUA">

Fixed.

**Comment by adityatoshniwal** [comment] 2024-06-17 04:34
> Not able to reproduce. Tried with docker snapshot also.
> 

Try using dark theme on your MacOS.

**Comment by yogeshmahajan-1903** [comment] 2024-06-17 06:01
> > Not able to reproduce. Tried with docker snapshot also.
> 
> Try using dark theme on your MacOS.

I guess this is fixed with one of the above fix.

**Closed** 2024-06-27 08:41 UTC
Labels: Housekeeping, EDB Sprint 171
