### ISSUE TITLE
Explain output is displayed instead of Explain Analyze if the user presses Shift F7(Windows only)

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6480] opened 2023-06-22 08:40 UTC
Explain output is displayed instead of Explain Analyze if the user presses Shift F7. However, If the user Clicks on Explain analyze button then the actual Result is displayed.

**To Reproduce**

1. Connect to any server
2. Launch query tool Windows
3. write  (select * from pg_class;)
4. Press Shift + F7
5.  See the output ( Seq Scan on pg_class as pg_class)
6.  Explain output is displayed instead of Explain Analyze

**Expected behaviour**

The output of Explain analyze is displayed if Press Shift + F7

**Screenshots**

<img width="1070" alt="Screen Shot 2023-06-22 at 1 32 54 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/ec5a18d2-4fe2-4557-a1b5-9c281b74fc3a">

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version: [7.3]
 - Mode: [All]
 - Package type: [ALL]

**Comment by akshay-joshi** [comment] 2023-06-22 08:48
@FaharAbbasRizvi

I am not able to reproduce this.

**Comment by FaharAbbasRizvi** [comment] 2023-06-23 10:53
> @FaharAbbasRizvi
> 
> I am not able to reproduce this.

Yes, this is not reproducible on MAC OS X.

**Comment by adityatoshniwal** [comment] 2023-06-23 11:12
Closing since it is not reproducible. Re-open if reproduced again.

**Closed by adityatoshniwal** 2023-06-23 11:12 UTC
Labels: Bug
