### ISSUE TITLE
Need the ability to view Postgres log files via pgadmin4, similar to what SSMS (SQL Server Management Studio) does!

### ISSUE THREAD

**Issue by ronwildt** [pgadmin-org/pgadmin4#6696] opened 2023-08-17 13:36 UTC
**Describe the solution you'd like**
similar to what SSMS (SQL Server Management Studio) is able to do...view Postgres logs directly in the toolset
This feature would put pgadmin4 more on parity with SSMS making the toolset richer and much more useable by users needing to view log files as part of troubleshooting, etc.
**Describe alternatives you've considered**
Have to ssh into servers to see the postgres logs...very time consuming and ineffective comparatively speaking
N/A
**Additional context**
searches appear to say that pgadmin3 HAD this feature??? So not sure why it was deleted from the latest versions???
![SSMS SQL logs](https://github.com/pgadmin-org/pgadmin4/assets/29985566/29eacd99-c54c-49f4-b137-b4e632b85726)

**Comment by akshay-joshi** [comment] 2023-08-18 05:57
Duplicate of #3981

**Closed by akshay-joshi** 2023-08-18 05:57 UTC
Labels: Feature
