### ISSUE TITLE
Problem to backup DB with uWSGI

### ISSUE THREAD

**Issue by naturel-eol** [pgadmin-org/pgadmin4#6806] opened 2023-09-29 12:30 UTC
Hi,
I installed pgAdmin4 (v7.4) web with uWSGI (v2.0.15).
When I launch a backup proccess in pgAdmin UI, I have this error :
```
2023-09-29 14:25:05,482: INFO   pgadmin:        Executing the process executor with the arguments: ['/usr/bin/uwsgi-core', '/home/ubuntu/.local/lib/python3.8/site-packages/pgadmin4/pgadmin/misc/bgprocess/process_executor.py', '/usr/bin/pg_dump', '--file', '/var/lib/pgadmin4/storage/laurent.boitard_edhec.edu/bkp-schola-preprod-v336.sql', '--host', 'schola-db-preprod.cebbgxbgqc8k.eu-west-3.rds.amazonaws.com', '--port', '5432', '--username', 'lg_db_schola', '--no-password', '--verbose', '--format=c', '--blobs', 'edhec_staging']
2023-09-29 14:25:05,482: INFO   pgadmin:        Waiting for a lock.
2023-09-29 14:25:05,483: INFO   pgadmin:        Acquired a lock.
2023-09-29 14:25:05,484: INFO   pgadmin:        Released a lock.
2023-09-29 14:25:05,519: DEBUG  pgadmin:        Process Watcher Out:
2023-09-29 14:25:05,519: DEBUG  pgadmin:        Process Watcher Err:/usr/bin/uwsgi-core: option '--file' is ambiguous; possibilities: '--file-serve-mode' '--fileserve-mode' '--file-write'
getopt_long() error
``` 
How can I solve this please ?
Thank

**Comment by yogeshmahajan-1903** [comment] 2023-10-03 07:16
@naturel-eol 
I am not able to reproduce the issue. Can you please share your uWSGI ini file? Also what is package type used for uWSGI(apt or pip)?

**Comment by akshay-joshi** [comment] 2023-10-06 11:27
@naturel-eol 

Please refer to [5340](https://github.com/pgadmin-org/pgadmin4/issues/5340) and https://www.pgadmin.org/docs/pgadmin4/latest/server_deployment.html#additional-information

If the above fix the issue let us know.

**Comment by naturel-eol** [comment] 2023-10-10 07:11
Hi @akshay-joshi 
Thank for you reply.
I will try these solutions later, but for  the moment I installed à Docker version which works fine :)

**Comment by adityatoshniwal** [comment] 2023-10-10 07:12
Closing for now.

**Closed by adityatoshniwal** 2023-10-10 07:12 UTC
Labels: Bug
