### ISSUE TITLE
Cannot download file to local

### ISSUE THREAD

**Issue by olupop** [pgadmin-org/pgadmin4#5434] opened 2022-10-13 08:25 UTC
Upgraded from 6.13 to 6.14
I follow this path: Tools > Storage Manager > Clicking on file > Clicking the download button on the right top
But the file cannot be downloaded

![image](https://user-images.githubusercontent.com/60285674/195542453-b3aa0a08-ef99-4435-ac68-4ad3079bd30a.png)

Apache log:
```
[Wed Oct 12 20:45:17.091018 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171] 2022-10-12 20:45:17,090: ERROR\tpgadmin:\tdownload() got an unexpected keyword argument 'req'
[Wed Oct 12 20:45:17.091094 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171] Traceback (most recent call last):
[Wed Oct 12 20:45:17.091101 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]   File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
[Wed Oct 12 20:45:17.091107 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]     rv = self.dispatch_request()
[Wed Oct 12 20:45:17.091113 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]   File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
[Wed Oct 12 20:45:17.091118 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
[Wed Oct 12 20:45:17.091123 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]   File "/usr/pgadmin4/venv/lib64/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
[Wed Oct 12 20:45:17.091128 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]     return func(*args, **kwargs)
[Wed Oct 12 20:45:17.091133 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]   File "/usr/pgadmin4/web/pgadmin/misc/file_manager/__init__.py", line 1092, in file_manager
[Wed Oct 12 20:45:17.091139 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]     res = func(**kwargs)
[Wed Oct 12 20:45:17.091146 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171] TypeError: download() got an unexpected keyword argument 'req'
[Wed Oct 12 20:45:17.091157 2022] [wsgi:error] [pid 233714:tid 140247350355712] [remote 192.168.X.X:16171]
```
File permissions and ownerships seem right. (user apache, group apache, has read permission)

**Comment by nikhil-mohite** [comment] 2022-10-13 08:33
Duplicate of #5368

**Closed by nikhil-mohite** 2022-10-13 08:33 UTC
