### ISSUE TITLE
auto refresh

### ISSUE THREAD

**Issue by hamzatopk** [pgadmin-org/pgadmin4#7044] opened 2023-12-07 20:51 UTC
from a qt5 app i made changes in a qtableview widget and submitting changes to postgresql db;  those changes are propagated but they are not visible in pgadmin4 even when using the refresh option in the browser, and the only solution to see changes is by hitting  view/edit data and choosing "all rows".

**Comment by adityatoshniwal** [comment] 2023-12-08 04:38
Its not clear what the issue is. Please provide details like OS details, pgAdmin version and if possible a screen recording to explain the issue, screenshots, and exact reproduction steps.

**Comment by hamzatopk** [comment] 2023-12-08 16:19
![Capturepgadmin](https://github.com/pgadmin-org/pgadmin4/assets/150580288/79abcca5-ae41-4c68-ac88-6dbb4b282143)

**Comment by hamzatopk** [comment] 2023-12-08 16:21
the issue is that the refresh feature don't work!.

**Comment by adityatoshniwal** [comment] 2023-12-22 11:44
Hi @hamzatopk,
Which refresh feature are you talking about? If you're saying about the object explorer refresh, then it will refresh the objects listed in the tree and not the actual data of the table.
This is not a bug, closing.
Thanks.

**Closed by adityatoshniwal** 2023-12-22 11:44 UTC
