### ISSUE TITLE
pgadmin4 generated 243.5 GB of Crash Report files

### ISSUE THREAD

**Issue by vlahovivan** [pgadmin-org/pgadmin4#5601] opened 2022-12-02 10:41 UTC
![image](https://user-images.githubusercontent.com/30372377/205274243-d547bba2-7823-42e0-9b8a-64cf7342d070.png)

pgadmin4 just generated 243.5 GB of Crash Report files, causing my laptop to overheat and not work properly. I have installed it yesterday, so I guess I have the latest version (I don't know how to check). Also, since I've deleted all of the log files to make my laptop work again, I don't have any of those to attach here.

**Comment by khushboovashi** [comment] 2022-12-02 11:30
On which OS and how you have to installed pgAdmin ?

**Comment by vlahovivan** [comment] 2022-12-02 11:33
I'm on Ubuntu 20.04, I have installed it following these commands https://www.pgadmin.org/download/pgadmin-4-apt/

**Comment by pravesh-sharma** [comment] 2022-12-09 11:13
@vlahovivan 
We are not able to reproduce this. Have you tried to read the crash report? If yes have you figured out something.

**Comment by vlahovivan** [comment] 2022-12-09 11:27
Unfortunately no, because my computer didn't work properly until I deleted everything.

**Comment by yogeshmahajan-1903** [comment] 2022-12-23 11:05
Please feel free to reopen the issue if occurs again. Closing for now.

**Closed by yogeshmahajan-1903** 2022-12-23 11:05 UTC
