### ISSUE TITLE
SchemaDiff: Issue When Comparing CHECK CONSTRAINT

### ISSUE THREAD

**Issue by bking-encodia** [pgadmin-org/pgadmin4#7335] opened 2024-04-01 19:29 UTC
Running schema diff, get a diff result for tables with a string column with CHECK CONSTRAINTS applied, for example: (Both source and target were created by same script)

Source:
```
CREATE TABLE public.device
(
 	status character varying(25) COLLATE pg_catalog."default",
 	CONSTRAINT device_status_check CHECK (status::text = ANY (ARRAY['RUNNING'::character varying, 'COMPLETED'::character varying, 'UNKNOWN'::character varying]::text[]))

)
```
Target:
```
CREATE TABLE public.device
(
 	status character varying(25) COLLATE pg_catalog."default",
	CONSTRAINT device_status_check CHECK (status::text = ANY (ARRAY['RUNNING'::character varying::text, 'COMPLETED'::character varying::text, 'UNKNOWN'::character varying::text]))
)

```

Difference:
```
ALTER TABLE IF EXISTS public.device DROP CONSTRAINT IF EXISTS device_status_check;

ALTER TABLE IF EXISTS public.device
    ADD CONSTRAINT device_status_check CHECK (status::text = ANY (ARRAY['RUNNING'::character varying, 'COMPLETED'::character varying, 'UNKNOWN'::character varying]::text[]));
```

Source Database: PostgreSQL Version: 15 (MacOS)
Target Database: PostgreSQL Version: 15 (Windows)

Even after applying the diff the same differences keep appearing when diff is re-run

**Expected behavior**
The diff is applied correctly.

OS: Mac OS Sonoma
PostgreSQL Version: 15
agAdmin Version: 8.4
Mode: Desktop

**Comment by akshay-joshi** [comment] 2024-04-09 06:07
Hi @bking-encodia 

I am unable to reproduce this issue with the latest pgAdmin v8.5. Can you please test on the latest pgAdmin?

<img width="1346" alt="Screenshot 2024-04-09 at 11 35 53 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/8e7352c6-413b-48b7-80a2-eea8cf33e1ff">

**Comment by bking-encodia** [comment] 2024-04-10 16:51
I did a test with 8.5 and still getting the issue, a difference found in the formatting of the check constraint:
Source:
`CONSTRAINT device_status_check CHECK (async_status::text = ANY (ARRAY['PENDING'::character varying, 'VERIFY_SUCCESS'::character varying, 'SAVE_SUCCESS'::character varying, 'ERROR'::character varying]::text[]))`
Target:
`CONSTRAINT device_status_check CHECK (async_status::text = ANY (ARRAY['PENDING'::character varying::text, 'VERIFY_SUCCESS'::character varying::text, 'SAVE_SUCCESS'::character varying::text, 'ERROR'::character varying::text]))`

I execute the diff script to make target match source, then re-run the diff and the same diff is found again. Could it be because source/target are different platforms (Mac/Windows) and each has a slightly different way of handling constraints?

**Comment by akshay-joshi** [comment] 2024-04-19 10:45
@bking-encodia 

I have tried on a different platform as well, but still unable to reproduce it.

**Comment by bking-encodia** [comment] 2024-04-24 17:54
Okay if I create 2 new databases and create 1 table in each:

Database #1
```
CREATE TABLE public.test
(
   	work_status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT work_status_check CHECK (work_status::text = ANY (ARRAY['PASS'::character varying, 'FAIL'::character varying]::text[]))
)
```

Database #2
```
CREATE TABLE public.test
(
   	work_status character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT work_status_check CHECK (work_status::text = ANY (ARRAY['PASS'::character varying::text, 'FAIL'::character varying::text]))
)
```

If I then compare these databases then no difference is found. So I am unable to reproduce when testing CONSTRAINT in isolation, so this may be related to the overall table definition. I'm starting to think this could somehow be related to: 

https://github.com/pgadmin-org/pgadmin4/issues/7405 

where differences are found when there are none.

**Comment by akshay-joshi** [comment] 2024-04-25 06:16
@bking-encodia 

We are unable to reproduce #7405 either. Waiting for the author's response on that. If it is not reproducible can we close this issue?

**Comment by bking-encodia** [comment] 2024-04-25 15:56
@akshay-joshi yes, thank you for looking into it

**Closed** 2024-04-26 06:15 UTC
Labels: Bug
