### ISSUE TITLE
Cannot connect to previously added server with SSH tunneling

### ISSUE THREAD

**Issue by PedroMTSilva** [pgadmin-org/pgadmin4#6358] opened 2023-06-04 15:32 UTC
Bug description:

As of update 7.2 i can no longer access the server that i had on my server list. I am currently using:

version: pgAdmin4 7.2
OS: Pop!_OS 22-04 LTS x84_64 (jammy)
Package type: APT
Mode: desktop
Browser: Firefox

Using the exact same credentials on desktop and on web, can only access the server via the web interface. On desktop, i have been getting the following error:

`Unable to connect to server: Failed to decrypt the SSH tunel password. Error: 'ServerManager' object has no attribute 'manager'`

**To Reproduce**

1. Open the pgAdmin desktop aplication
2. Right click on servers -> Register...
3. Enter credentials and press save
4. Error above pops up

**Expected behavior**

After inserting the credentials, the user should be able to connect, since its possible in pgAdmin-web.

**Error message**
`Unable to connect to server: Failed to decrypt the SSH tunel password. Error: 'ServerManager' object has no attribute 'manager'`

**Comment by globalistas** [comment] 2023-06-05 06:29
Can confirm this highly frustrating issue. Bascially locked me out of my DB servers.

**Comment by akshay-joshi** [comment] 2023-06-05 06:49
Duplicate of #6341. We have fixed this issue and will be available in the next release v7.3. Will try to release it asap maybe in 2-3 days.

**Closed by akshay-joshi** 2023-06-05 06:49 UTC
Labels: Bug
