### ISSUE TITLE
pgAdmin 7.1 query results do not display after several queries are run

### ISSUE THREAD

**Issue by anthonydb** [pgadmin-org/pgadmin4#6251] opened 2023-05-05 19:10 UTC
**Describe the bug**

I upgraded to version 7.1 today. When I run several queries, the first couple of queries execute normally and display results in the results grid as expected. However, after three or four queries, executing a query leads to the results grid highlighting the messages tab only, and the results grid only shows the results of the last successful query.

This may be related to another report: https://github.com/pgadmin-org/pgadmin4/issues/6250

**To Reproduce**

* Open the query tool.
* Run multiple queries.

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Version: 7.1
 - Mode: Desktop

**Comment by 0xMoJo7** [comment] 2023-05-15 19:41
I am having the same issue.

**Comment by JeffKulon** [comment] 2023-05-15 22:54
This has been happening to me as well.  Looking at https://github.com/pgadmin-org/pgadmin4/issues/6250, mentioned above as a possible duplicate, I followed some instructions to view the pgAdmin logs.   When the Query Tool starts behaving as already described, I see logs like this:
```
2023-05-15 15:48:06,199: ERROR	pgadmin:	<asyncio.locks.Lock object at 0x000001AEDB4F7D90 [unlocked, waiters:1]> is bound to a different event loop
Traceback (most recent call last):
  File "C:\Users\[redacted]\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\cursor.py", line 281, in execute
    return asyncio.run(self._execute(query, params))
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Users\[redacted]\AppData\Local\Programs\pgAdmin 4\v7\web\pgadmin\utils\driver\psycopg3\cursor.py", line 292, in _execute
    return await _async_cursor.execute(self, query, params)
  File "C:\Users\[redacted]\AppData\Local\Programs\pgAdmin 4\v7\python\lib\site-packages\psycopg\cursor_async.py", line 89, in execute
    async with self._conn.lock:
  File "asyncio\locks.py", line 14, in __aenter__
  File "asyncio\locks.py", line 106, in acquire
  File "asyncio\mixins.py", line 30, in _get_loop
RuntimeError: <asyncio.locks.Lock object at 0x000001AEDB4F7D90 [unlocked, waiters:1]> is bound to a different event loop
```

**Comment by adityatoshniwal** [comment] 2023-05-16 05:50
HI @anthonydb @JeffKulon,

Can you try disabling File->Preferences->Auto Completion->Autocomplete on key press please?
Meanwhile, we're looking into it.

Thanks.

**Comment by anthonydb** [comment] 2023-05-17 20:17
@adityatoshniwal 

OK, I disabled Autocomplete on key press and was able to run multiple queries this afternoon without seeing this issue recur, so that looks like a solid workaround for now. Thanks.

**Comment by yogeshmahajan-1903** [comment] 2023-05-19 11:55
Duplicate of #6163

**Closed by yogeshmahajan-1903** 2023-05-19 11:55 UTC
Labels: Bug
