### ISSUE TITLE
Save results to file (F8 Save) writes empty CSV file

### ISSUE THREAD

**Issue by Adventurer2021** [pgadmin-org/pgadmin4#5808] opened 2023-02-01 15:35 UTC
Using pgAdmin4 V6.15 in client mode (**not running from chrome browser session**) and PostgreSQL V15 on Windows 11 Pro:

I ran query that produced 3,789,839 records (16 columns). However, when I attempted to save the output using PgAdmin4 (F8 Save results to file) the process went into the "Downloading results..." (which took about 2.5 minutes) and then the file manager window opened to select destination folder and file name and file type. I chose Microsoft Excel comma separated file type. I clicked "save" and the window closed and I was back to PgAdmin4 but the file written had zero data in it. I received no errors from pgAdmin4.

Running queries that produced much less data out I've had no issues writing the file. 

I can create the output file using other PostgreSQL clients without issue.

**To Reproduce**

1. Run any query that would produce > 8 million records, at least 16 columns wide.
2. In Pgadmin4 data output panel, click "save results to file (F8)"
3."Downloading results" runs with spinning circle wait state displayed 
4. When file manager "save file" displays, choose .csv file type and click OK
5. Output file will be created but it is empty.

I opened a similar bug on 12/22/2022 (#5670) but it was closed with comment "[adityatoshniwal](https://github.com/adityatoshniwal) closed this as [not planned](https://github.com/pgadmin-org/pgadmin4/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22)" as it appeared to be related to a browser issue but 

I am not running pgAdmin via a browser session. I do have Brave as my default browser in Windows 11 but it's beyond me why my browser would have any impact while running pgAdmin4 in client mode without going through a browser? 

Please investigate this as I would prefer to use pgAdmin vs. other client that works for this requirement to write large csv files.

**Comment by adityatoshniwal** [comment] 2023-02-02 05:30
Hi @Adventurer2021,

pgAdmin desktop version runs in NW.js container. NW.js is as good as a browser which is chromium based.
It is not related to the browsers you have installed.

Thanks.

**Comment by Adventurer2021** [comment] 2023-02-02 19:42
Thanks, I really didn't think pgAdmin was using my default browser on my system (Brave). Your clarification that NW.js is based on it was chromium based is probably where the "related to chrome" comment came from on #5670 I didn't understand why #5670 was closed with a label of "not planned"? What does this mean? I also see that [#3369](https://github.com/pgadmin-org/pgadmin4/issues/3369) is related to this isue but that issue was opened in 2020 (if I'm reading this right)?

**Comment by adityatoshniwal** [comment] 2023-02-03 05:56
Hi @Adventurer2021,
#5670 was closed as it is duplicate of #3369 and both are related to empty CSV file. Basically, chrome is not able to handle large CSV files.
Even this issue is being closed for the same reason. "not planned" is what github adds when we close a duplicate. No need to worry about that.

Thanks.

**Closed by adityatoshniwal** 2023-02-03 05:56 UTC
Labels: Bug
