### ISSUE TITLE
Apparent Python Error when attempting a backup function

### ISSUE THREAD

**Issue by Derek-Powell** [pgadmin-org/pgadmin4#6916] opened 2023-11-01 01:53 UTC
Designing a repeatable multi-server/multi-purpose environment via docker compose as a modeling platform...

Initially the only application to leverage the SQL is WikiJS, others will follow as we progress.

Baseline PostgreSQL FROM docker.io/postgres:15.4
Baseline PGAdmin4 FROM docker.io/dpage/pgadmin4:latest
Baseline WIkiJS FROM lscr.io/linuxserver/wikijs:2.5.300

With all default OOB containers all is well, log into WikiJS which populates SQL backend, PGAdmin sees everything.

PROBLEM: When I attempt a backup of a database, I get this error in the image which implies python. Since I'm using published container images without modifications, I don't think this is misconfiguration, but I need some experienced eyes/direction....thanks in advance.

![image](https://github.com/pgadmin-org/pgadmin4/assets/135035071/a66aabee-876b-4e4c-ad5a-93deb8feef8d)

**Comment by yogeshmahajan-1903** [comment] 2023-11-01 10:46
@Derek-Powell 

Can you please share your docker-compose yaml file to reproduce the issue?

**Comment by Derek-Powell** [comment] 2023-11-03 22:21
Yogesh, please see readme in the tar file, 
[sterile.tar.gz](https://github.com/pgadmin-org/pgadmin4/files/13255084/sterile.tar.gz)
thanks in advance.

**Comment by yogeshmahajan-1903** [comment] 2023-11-06 11:48
@Derek-Powell 
Thanks for sharing the config yaml. Issue is reproducible and fixed. Duplicate of #6820

**Closed by yogeshmahajan-1903** 2023-11-06 11:48 UTC
Labels: Bug

**Comment by Derek-Powell** [comment] 2023-11-06 15:14
Thanks, Yogesh. So will this pull capture the fixed changed? 

FROM docker.io/dpage/pgadmin4:7

**Comment by Derek-Powell** [comment] 2023-11-06 16:32
@yogeshmahajan-1903  thanks.

So I've tried pulling :latest and :snapshot, neither seems to include the "fixed" instance. Any advice on how to get the fixed build?

**Comment by yogeshmahajan-1903** [comment] 2023-11-07 07:14
@Derek-Powell 
Fix is available in today's snapshot. To test this please use :snapshot. 
:latest will provide you last released image.
