### ISSUE TITLE
Erro.

### ISSUE THREAD

**Issue by jerfex** [pgadmin-org/pgadmin4#6590] opened 2023-07-19 12:28 UTC
From ph 7.4 on ubuntu 22.4 lts I'm having this error when doing select I've tried to solve the problem but without success I saw that it's referring to this new version.

missing FROM-clause entry for table "rel"
LINE 8: ...ER JOIN pg_catalog.pg_constraint con ON con.conrelid=rel.oid
                                                                ^

**Comment by yogeshmahajan-1903** [comment] 2023-07-19 13:18
@jerfex 

Can you please elaborate more about the issue and how to reproduce?

**Comment by Tolli81** [comment] 2023-07-26 09:03
Having the same issue on Windows 11 after upgrading from 7.1 (working fine) to 7.4.  Seems to be in multiple places/scenarios, but also dependant on remote server version.

Fails when connected to version 13, works when connected to version 15.

A: Navigate to any table -> Right click -> View/Edit Data -> All rows
B: Launch Query Tool -> Execute any simple SELECT ("SELECT name FROM mot.k_centers" or "SELECT * FROM pg_class") -> Execute

**Comment by anilsahoo20** [comment] 2023-07-28 11:42
Hi @jerfex and @Tolli81,
We have released pgAdmin 4 v7.5, Please try it once.

**Comment by Tolli81** [comment] 2023-08-02 08:25
Seems like all is fixed now, thanks. 👍

**Comment by akshay-joshi** [comment] 2023-08-04 07:55
Fixed as per user comment.

**Closed by akshay-joshi** 2023-08-04 07:55 UTC
