### ISSUE TITLE
pgAdmin 7.5 No output for CREATE SCRIPT (table or column)

### ISSUE THREAD

**Issue by MathiasZaja** [pgadmin-org/pgadmin4#6654] opened 2023-08-03 13:34 UTC

**Comment by MathiasZaja** [comment] 2023-08-03 13:38
Bug description.
pgAdmin Version: 7.5
environment: desktop Windows 10
To reproduce:
Go on any table (or table column)
Right-click
Select Scripts -> CREATE SCRIPT
Expected output: sql script
Result: No data output. Execute a query to get output.

**Comment by firstDismay** [comment] 2023-08-03 16:57
Didn't want to update, but you just intrigued me. Updated 7.4->7.5
Operating system: Windows Pro x64 ver 22H2 сборка 19045.3208
The problem is not reproduced.

**Comment by MathiasZaja** [comment] 2023-08-03 17:07
In fact the problem was related to pgAdmin
      layout which changed somehow.
      After File -> Reset Layout it displays fine again.
      You can close the issue which is not related to the version 7.5
      
      Sorry
    
    Le 03.08.2023 à 18:57, Dmitry Ivanov a
      écrit :
    
    
      
      Didn't want to update, but you just intrigued me.
        Updated 7.4->7.5
        Operating system: Windows Pro x64 ver 22H2 сборка 19045.3208
        The problem is not reproduced.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/pgadmin-org/pgadmin4/issues/6654#issuecomment-1664324855",
"url": "https://github.com/pgadmin-org/pgadmin4/issues/6654#issuecomment-1664324855",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    -- 
      Mathias Zajaczkowski
      Ubik S.A.
      Chemin du Signal 22
      1296 Coppet
      (+) 41 22 960 03 91
      ***@***.***

**Comment by adityatoshniwal** [comment] 2023-08-04 03:44
Closing per user confirmation.

**Closed by adityatoshniwal** 2023-08-04 03:44 UTC
