### ISSUE TITLE
Queries longer than 1 minute get stuck - Container 7.1

### ISSUE THREAD

**Issue by matheus-dr** [pgadmin-org/pgadmin4#6317] opened 2023-05-23 18:14 UTC
**Describe the bug**

Hello, well here in my development team we use pgadmin, and we used the version 6.21 until last week, then we upgraded it to version 7.1, but when we execute queries that take more than one second they get stuck in the page, in the bottom they appear stuck at 1 minute, and don't return anything, so this way we cannot execute queries that take longer than 1 minute, but we need for testing and optimization purposes.

**To Reproduce**

1. Login pgadmin
2. Enter query tool for a database
3. Run pg_sleep(62)
![image](https://github.com/pgadmin-org/pgadmin4/assets/81092363/6777a5a6-9f81-4f51-8fb8-d657affeaf27)

**Expected behavior**

Can run queries longer than 1 minute, like the old version could.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 7.1
 - Mode: Server
 - Browser Brave (Chrome)
 - Package type: Container

**Additional context**

The container is running in a Kubernetes cluster and volume is a EBS volume, but even in docker compose had this problem.

**Comment by Arunamanivannan** [comment] 2023-05-24 17:09
Hi Team, Yes we are facing the same issue. Queries are not getting executed beyond 1 minute and no results in UI page as well after upgrading from 6.17 to 7.1 version.

**Comment by yogeshmahajan-1903** [comment] 2023-05-26 04:42
@Arunamanivannan , @matheus-dr ,

Could you please share pgadmin logs?

**Comment by Arunamanivannan** [comment] 2023-05-29 15:34
@yogeshmahajan-1903 In our environment  'Autocomplete on key press' from preferences Query Tool > Auto Completion` was already disabled. Please find the attached log file while running the "select pg_sleep(300);"  which was completed it in 1 minute. 
[pgadmin.log](https://github.com/pgadmin-org/pgadmin4/files/11592840/pgadmin.log)
![image](https://github.com/pgadmin-org/pgadmin4/assets/33642156/4ce1327e-453c-46bb-98e9-c2152dbff110)

**Comment by khushboovashi** [comment] 2023-05-30 04:56
Hi, @Arunamanivannan, 

If pgAdmin runs behind Apache, try to increase the request timeout in Apache config.
The path (on RHEL) would be /etc/httpd/conf.d/pgadmin4.conf

Syntax for the Timeout directive is:

TimeOut 600

This would increase the gateway timeout to 600 seconds.

**Comment by khushboovashi** [comment] 2023-05-30 05:02
@matheus-dr, does pgAdmin run behind any web server like Nginx, or is it the default configuration provided by pgAdmin?

**Comment by Arunamanivannan** [comment] 2023-05-30 18:02
@khushboovashi In our environment, pgadmin4 is running in kubernetes cluster and it is having default configuration provided by pgadmin. Thanks. 

/pgadmin4 $ ps -ef | grep gunicorn
    1 pgadmin   0:36 {gunicorn} /venv/bin/python3 /venv/bin/gunicorn --limit-request-line 8190 --timeout 86400 --bind [::]:80 -w 1 --threads 25 --access-logfile - -c gunicorn_config.py run_pgadmin:app
   86 pgadmin   4:09 {gunicorn} /venv/bin/python3 /venv/bin/gunicorn --limit-request-line 8190 --timeout 86400 --bind [::]:80 -w 1 --threads 25 --access-logfile - -c gunicorn_config.py run_pgadmin:app
15449 pgadmin   0:00 grep gunicorn
/pgadmin4 $

**Comment by Arunamanivannan** [comment] 2023-06-01 14:19
@khushboovashi Hope you are doing good. When you find time, could you please help on this ? Thank you.

**Comment by yogeshmahajan-1903** [comment] 2023-06-05 07:20
@Arunamanivannan 

Would you mind sharing pgadmin deployment config yaml? I am not able to reproduce the issue if auto-complete is disabled and user did not press cmd+space for auto completion.

**Comment by Arunamanivannan** [comment] 2023-06-05 13:13
Hi @yogeshmahajan-1903 , Please find the attached yaml file. Thanks.

**Comment by yogeshmahajan-1903** [comment] 2023-06-07 09:20
@matheus-dr 
Attached zip file is empty.

**Comment by matheus-dr** [comment] 2023-06-07 14:41
[pgadmin-k8s.zip](https://github.com/pgadmin-org/pgadmin4/files/11678787/pgadmin-k8s.zip)
Sorry, can you verify now?

**Comment by Arunamanivannan** [comment] 2023-06-13 14:30
@khushboovashi @yogeshmahajan-1903 May I know is there any update we have ? Thank you.

**Comment by Arunamanivannan** [comment] 2023-06-27 13:46
@akshay-joshi @nikhil-mohite Based on the above messages, in my understanding that there was a fix committed for this issue and we can expect it to be available in version 7.5. Kindly confirm. Thank you.

**Comment by akshay-joshi** [comment] 2023-06-28 05:21
@Arunamanivannan 

Fix not committed yet, still have to fix other issues. We are working on it and the fix will be available in v7.5. We will release v7.4 tomorrow

**Comment by FaharAbbasRizvi** [comment] 2023-07-18 11:25
This issue has been tested and fixed in the latest snapshot build:
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-07-18/

**Closed by FaharAbbasRizvi** 2023-07-18 11:25 UTC
Labels: Bug, EDB Sprint 146

**Comment by Arunamanivannan** [comment] 2023-07-18 16:34
@FaharAbbasRizvi I have tested the issue with the recent snapshot image. I dont find the issue has been resolved. Or may be I am missing something. Here are the details 
pgadmin is running as statefulset in our environment. 
Image:          dpage/pgadmin4:snapshot
When I compared the config.py file between 7.1 & 7.4 I found that there is a parameter MASTER_PASSWORD_HOOK = None . Other than that no difference. . 
Executed to the query "select pg_sleep(90);" but it gets completed after 62 or 63 seconds. Try several times. 
Please find the below screen shot. 
![image](https://github.com/pgadmin-org/pgadmin4/assets/33642156/a427277e-77e9-4f37-9ace-88a88cfef43a)

Is this the correct test which I am doing ? Please advise otherwise. Thanks.

**Comment by FaharAbbasRizvi** [comment] 2023-07-19 04:50
@Arunamanivannan 

The issue is not reproducible on the latest docker snapshot build, Can you please stop your previous docker instance and start a new docker instance after doing -d dpage/pgadmin4:snapshot

<img width="1672" alt="Screen Shot 2023-07-19 at 9 43 22 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/43006122/cd3b4182-0776-407b-99a2-a38112ecd635">

If you are still facing an issue, please report the issue separately with proper steps to reproduce.

**Comment by Arunamanivannan** [comment] 2023-07-19 14:27
Hi @FaharAbbasRizvi , 
Have downloaded the new snapshot image in order to get the new instance of pgadmin. Please find the events below 

Events:
  Type     Reason                  Age                From                          Message
  ----     ------                  ----               ----                          -------
  Normal   Scheduled               114s               default-scheduler             Successfully assigned atmos-system/pgadmin-sts-0 to <node-name>
  Normal   SuccessfulAttachVolume  112s               attachdetach-controller       AttachVolume.Attach succeeded for volume "pvc"
  Normal   Pulling                 96s                kubelet, <node-name>          Pulling image "busybox"
  Normal   Pulled                  94s                kubelet, <node-name>          Successfully pulled image "busybox" in 1.818947654s (1.818960906s including waiting)
  Normal   Created                 94s                kubelet, <node-name>          Created container pgadmin-mount-permission
  Normal   Started                 94s                kubelet, <node-name>          Started container pgadmin-mount-permission
  Normal   Pulling                 87s                kubelet, <node-name>          Pulling image "dpage/pgadmin4:snapshot"
  Normal   Pulled                  74s                kubelet, <node-name>          Successfully pulled image "dpage/pgadmin4:snapshot" in 13.329997567s (13.330003452s including waiting)
  Normal   Created                 74s                kubelet, <node-name>          Created container pgadmin
  Normal   Started                 74s                kubelet, <node-name>          Started container pgadmin
  
It works today as expected. Yesterday also have followed the same and noticed the event same as above not sure why it was not working. 
However I can confirm that the issue has been resolved.  Thank you for your support. 
![image](https://github.com/pgadmin-org/pgadmin4/assets/33642156/7895b7ff-9c70-4467-a455-d34aec0e0330)
