### ISSUE TITLE
Result grid: Not show vertical line between 2 columns (RM #7612)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5255] opened 2022-08-13 13:13 UTC
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7612***
*Originally created by **Vy Donhu** at 2022-08-13 13:13:25 UTC.*

Result grid: Not show vertical line between 2 columns

**Comment by akshay-joshi** [comment] 2022-09-26 11:32
Duplicate of #5068

**Closed by akshay-joshi** 2022-09-26 11:32 UTC
Labels: Bug, Ready
