### ISSUE TITLE
getting 

### ISSUE THREAD

**Issue by Jatin-Prakash** [pgadmin-org/pgadmin4#5885] opened 2023-02-21 06:57 UTC
![pgAdmin-issue](https://user-images.githubusercontent.com/12675946/220269780-0d6fc93c-3827-4022-9c98-20b55c79fc3d.png)

Hi,

I am trying to make a new server, but not able to proceed. I have added the screen shot, of the issue I am getting. I have already tried with modifying pg_hba.conf file. 

Can any one please help me in proceeding.
NOTE :  I am provinding with correct password

**Comment by yogeshmahajan-1903** [comment] 2023-02-21 08:49
Duplicate of #5886

**Closed by yogeshmahajan-1903** 2023-02-21 08:49 UTC
