### ISSUE TITLE
Unable to persist servers configuration.

### ISSUE THREAD

**Issue by oussemabhouri** [pgadmin-org/pgadmin4#5895] opened 2023-02-24 10:47 UTC
I m using pgadmin as a deployment in my k8s cluster. 
Im attaching a PVC to it.
```
`resource "kubernetes_persistent_volume_claim" "pgadmin_volume" {
  metadata {
    name = "pgadmin-volume"
  }

  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = "5Gi"
      }
    }
  }
  wait_until_bound = false
}`
```
with the mountpath: 

```
`          volume_mount {
            name       = "pgadmin-volume"
            mount_path = "/var/lib/pgadmin/"
          }`
```
My goal here is to persist the created servers that were created from UI so that on a pod restart, those servers persist. at the moment, I lose them at every pgadmin pod restart. I know that all servers are stored in `/var/lib/pgadmin/sessions`, if I change the mount_path to `/var/lib/pgadmin/sessions` it will throw a permission error as Im running container as rootless. Besides the fact that I dont know what is the root password for it, I dont want to give full rw permission to `/var/lib/pgadmin/` , so I was thinking about changing DATA_DIR located in config.py file! but so far, I could not do it with terraform.

The error that I get is: 
```

`WARNING: Failed to set ACL on the directory containing the configuration database:
           [Errno 1] Operation not permitted: '/var/lib/pgadmin'
HINT   : You may need to manually set the permissions on
         /var/lib/pgadmin to allow pgadmin to write to it.
ERROR  : Failed to create the directory /var/lib/pgadmin/sessions:
           [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
HINT   : Create the directory /var/lib/pgadmin/sessions, ensure it is writeable by
         'pgadmin', and try again, or, create a config_local.py file
         and override the SESSION_DB_PATH setting per
         https://www.pgadmin.org/docs/pgadmin4/4.30/config_py.html`

```
Any ideas, suggestions.. are more than welcome. Thanks!

**Comment by pravesh-sharma** [comment] 2023-02-24 11:49
Hi @oussemabhouri ,

Which version of pgAdmin 4 you are using?

**Comment by oussemabhouri** [comment] 2023-02-24 11:52
4 normally!

**Comment by pravesh-sharma** [comment] 2023-02-24 12:10
@oussemabhouri Can you please try with the latest version 6.20 https://hub.docker.com/layers/dpage/pgadmin4/latest/images/sha256-2efd6d20c528e939f28257bdb0160b3907a677151199a11a4e72c9704697ab70?context=explore

**Comment by oussemabhouri** [comment] 2023-02-24 12:16
now im getting: 
```
`NameError: name 'sys' is not defined
[2023-02-24 12:15:37 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-02-24 12:15:37 +0000] [1] [INFO] Listening at: http://[::]:5050 (1)
[2023-02-24 12:15:37 +0000] [1] [INFO] Using worker: gthread
[2023-02-24 12:15:37 +0000] [96] [INFO] Booting worker with pid: 96
[2023-02-24 12:15:39 +0000] [96] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 82, in create_app_data_directory
    _create_directory_if_not_exists(config.SESSION_DB_PATH)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 20, in _create_directory_if_not_exists
    os.mkdir(_path)
PermissionError: [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 93, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 267, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 94, in create_app_data_directory
    sys.exit(1)`
```

**Comment by oussemabhouri** [comment] 2023-02-24 12:47
and when changing the mountpath to `/pgadmin` for example, it works. but of course doesnt persist any newly created server on pod restart

**Comment by oussemabhouri** [comment] 2023-02-24 13:04
Also, what is the default password for root user ?

**Comment by oussemabhouri** [comment] 2023-02-27 23:22
cc @dpage 
is overwriting SESSION_DB_PATH in config_distro.py will solve the problem? if yes, how?

**Comment by yogeshmahajan-1903** [comment] 2023-02-28 03:33
@oussemabhouri 
Could you please share container logs when you change mount path to /pgadmin? There is no reason for not to persist server configuration when PV is used. Would you mind to share complete Kubernetes configuration file?

**Comment by oussemabhouri** [comment] 2023-02-28 08:51
Just normal logs with no error. And I think there is actually a reason for losing the servers! because the ones that are newly created will be stored in /var/lib/pgadmin/sessions, so it doesnt make any sense to mount the PVC path in /pgadmin ...

**Comment by oussemabhouri** [comment] 2023-02-28 08:53
so maybe you can provide me a way on how to use SESSION_DB_PATH and change it to /pgadmin for example, or anyother workaround please.

**Comment by dpage** [comment] 2023-02-28 09:13
You don't need to change any config values to do what you're trying to do (and definitely don't try to change config_distro.py as those changes may get overwritten).

Just map /var/lib/pgadmin to persistent storage, per the docs at https://www.pgadmin.org/docs/pgadmin4/6.20/container_deployment.html#mapped-files-and-directories, but you *must* ensure the UID under which the container runs (5050 by default) has permission to write to that volume.

**Comment by oussemabhouri** [comment] 2023-02-28 09:50
so if I map  /var/lib/pgadmin to my persistent storage, I get 
```
``WARNING: Failed to set ACL on the directory containing the configuration database:
           [Errno 1] Operation not permitted: '/var/lib/pgadmin'
HINT   : You may need to manually set the permissions on
         /var/lib/pgadmin to allow pgadmin to write to it.
ERROR  : Failed to create the directory /var/lib/pgadmin/sessions:
           [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
HINT   : Create the directory /var/lib/pgadmin/sessions, ensure it is writeable by
         'pgadmin', and try again, or, create a config_local.py file
         and override the SESSION_DB_PATH setting per
         https://www.pgadmin.org/docs/pgadmin4/4.30/config_py.html`
```

**Comment by dpage** [comment] 2023-02-28 10:14
If you're getting the message text above, then you're running v4.30 - which hasn't been supported for over 2 years. So, please update.

That said, the message you see is telling us that the user ID under which pgAdmin is running cannot write to the persistent storage you've mapped (assuming it is properly mapped). You need to adjust the permissions on the volume to fix that.

**Comment by oussemabhouri** [comment] 2023-02-28 10:25
```
locals {
  app_name = var.is_partner ? "pgadmin-beta" : "pgadmin"
}

resource "kubernetes_deployment" "pgadmin_deployment" {
  count = var.perform_deployment ? 1 : 0

  depends_on = [var.cluster]

  metadata {
    name      = local.app_name
    namespace = "default"
    labels = {
      app = local.app_name
    }
  }

  spec {
    replicas = 1

    selector {
      match_labels = {
        app = local.app_name
      }
    }

    template {
      metadata {
        labels = {
          app = local.app_name
        }
      }

      spec {
        volume {
          name = "pgadmin-volume"
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim.pgadmin_volume.metadata.0.name
          }
        }
        volume {
          name = "config-volume"
          config_map {
            name         = "${local.app_name}-config"
            default_mode = "0555"
          }
        }
        container {
          image             = "dpage/pgadmin4:6"
          image_pull_policy = "IfNotPresent"
          name              = "app"

          port {
            container_port = 5050
          }

          env {
            name  = "PGADMIN_DEFAULT_EMAIL"
            value = "admin@live.com"
          }

          env {
            name  = "PGADMIN_DEFAULT_PASSWORD"
            value = "admin"
          }

          env {
            name  = "PGADMIN_LISTEN_PORT"
            value = "5050"
          }

          env {
            name  = "PGPASSWORD"
            value = var.master_password
          }

          env {
            name  = "DATABASE_HOST"
            value = var.db_host
          }

          env {
            name  = "DATABASE_USER"
            value = var.master_username
          }

          env {
            name  = "DATABASE_PORT"
            value = "5432"
          }

          env {
            name  = "DATABASE_NAME"
            value = "postgres"
          }

          liveness_probe {
            http_get {
              path = "/"
              port = 5050
            }

            failure_threshold = 3
          }

          readiness_probe {
            http_get {
              path = "/"
              port = 5050
            }

            failure_threshold = 3
          }

          lifecycle {
            post_start {
              exec {
                command = ["/bin/sh", "-c", "/usr/bootstrap/bootstrap.sh ${var.db_host} ${var.master_username}"]
              }
            }
          }

          volume_mount {
            name       = "config-volume"
            mount_path = "/usr/bootstrap/"
            read_only  = true
          }
          volume_mount {
            name       = "pgadmin-volume"
            mount_path = "/var/lib/pgadmin"
          }
        }
      }
    }
  }
}

resource "kubernetes_service" "pgadmin_service" {
  count = var.perform_deployment ? 1 : 0

  metadata {
    name = "${local.app_name}-service"
    labels = {
      app = local.app_name
    }
  }
  spec {
    selector = {
      app = local.app_name
    }
    port {
      port = 5050
      name = "http"
    }

    type = "ClusterIP"
  }
}

resource "kubernetes_persistent_volume_claim" "pgadmin_volume" {
  metadata {
    name = "pgadmin-volume"
  }

  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = "8Gi"
      }
    }
  }
  wait_until_bound = false
}

resource "kubernetes_config_map" "pgadmin_config" {
  count = var.perform_deployment ? 1 : 0

  metadata {
    name = "${local.app_name}-config"
  }

  data = {
    "bootstrap.sh"             = file("${path.module}/scripts/bootstrap.sh")
    "user.sql"                 = var.use_readonly_user == true ? file("${path.module}/scripts/create-ro-user.sql") : file("${path.module}/scripts/create-rw-user.sql")
    "grant-permissions.sql"    = var.use_readonly_user == true ? file("${path.module}/scripts/grant-ro-permissions.sql") : file("${path.module}/scripts/grant-rw-permissions.sql")
    "permissions.py"           = file("${path.module}/scripts/permissions.py")
    "permissions_for_teams.py" = file("${path.module}/scripts/permissions_for_teams.py")
    "serverlist.json"          = <<-EOT
{
"Servers": {
    "1": {
        "Name": "postgres",
        "Group": "Servers",
        "Port": 5432,
        "Username": "${var.use_readonly_user == true ? "postgres_ro" : "postgres_rw"}" ,
        "Host": "${var.db_host}",
        "SSLMode": "prefer",
        "MaintenanceDB": "postgres"
    }
  }
}
EOT
  }
}

```

So this is my terraform code.
As you can see, Im attaching `pvc-volume` to my deployment.
And still, Im getting: 


```
`
Traceback (most recent call last):
  File "/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/pgadmin4/run_pgadmin.py", line 4, in <module>
    from pgAdmin4 import app
  File "/pgadmin4/pgAdmin4.py", line 93, in <module>
    app = create_app()
  File "/pgadmin4/pgadmin/__init__.py", line 267, in create_app
    create_app_data_directory(config)
  File "/pgadmin4/pgadmin/setup/data_directory.py", line 94, in create_app_data_directory
    sys.exit(1)
NameError: name 'sys' is not defined
[2023-02-28 10:22:16 +0000] [95] [INFO] Worker exiting (pid: 95)
ERROR  : Failed to create the directory /var/lib/pgadmin/sessions:
           [Errno 13] Permission denied: '/var/lib/pgadmin/sessions'
HINT   : Create the directory /var/lib/pgadmin/sessions, ensure it is writeable by
         'pgadmin', and try again, or, create a config_local.py file
         and override the SESSION_DB_PATH setting per
         https://www.pgadmin.org/docs/pgadmin4/6.20/config_py.html
[2023-02-28 10:22:16 +0000] [1] [INFO] Shutting down: Master
[2023-02-28 10:22:16 +0000] [1] [INFO] Reason: Worker failed to boot.`
```

**Comment by dpage** [comment] 2023-02-28 10:42
The "NameError: name 'sys' is not defined" is a minor bug that I've just fixed. It is not the cause of the problem you see here (it happens when cleaning up after the actual problem).

The actual problem remains the same; the user that pgAdmin is running as cannot write to the persistent storage. We cannot tell you why (or debug your Terraform template), however, I would suggest:

1) Deploy the container.
2) Start a shell session in the container.
3) Figure out what user the application is running as (the id command, unless you start the shell session as a different user).
4) Check the ownership and permissions on /var/lib/pgadmin
5) Fix the permissions/ownership in your Terraform template as required.

**Comment by oussemabhouri** [comment] 2023-02-28 13:05
Is there any other way of preserving manually created servers other than using PVC ? @dpage

**Comment by oussemabhouri** [comment] 2023-02-28 16:02
Honestly I am a little bit confused. 
1- Any mounted path on my PVC should be mountable.
2- Whatever operation on /var/lib/pgadmin/sessions inside the container by pgadmin user will be refused because or permissions. 
3- I also tried a symbolic link between /var/lib/pgadmin/sessions and /pgadmin-sessions for example and mounted my PVC to /pgadmin-sessions , and still got the same permissions errors..

**Comment by oussemabhouri** [comment] 2023-02-28 17:36
Okay I used an init container to overcome this issue.

**Comment by oussemabhouri** [comment] 2023-02-28 17:58
okay issue fixed by using an init container that changes the ownership of the PVC volume mounted! 
thanks for the support @dpage

**Comment by yogeshmahajan-1903** [comment] 2023-03-01 05:07
As per author issue is resolved, hence closing the issue.

**Closed by yogeshmahajan-1903** 2023-03-01 05:07 UTC
