### ISSUE TITLE
Support for multiple result set tabs in single connection "Data output" window.

### ISSUE THREAD

**Issue by tiniwings** [pgadmin-org/pgadmin4#8000] opened 2024-10-02 17:53 UTC
**Describe the solution you'd like**
Current "Data output" window only supports one active result set tab. 
If user have to check results and compare the data between multiple queries, they have to resubmit the queries again to compare them in single session query tool.

**Comment by anilsahoo20** [comment] 2024-10-04 11:29
Duplicate of #6776

**Closed by anilsahoo20** 2024-10-04 11:29 UTC
Labels: Feature
