### ISSUE TITLE
pgAdmin 6.9 - Query Tool Results Grid Rows Missing Border Styling (RM #7382)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5068] opened 2022-05-15 22:01 UTC
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7382***
*Originally created by **Anthony DeBarros** at 2022-05-15 22:01:45 UTC.*

On pgAdmin 6.9 using a Windows 11 machine, the border styling of each row does not display as expected (e.g., there aren't borders around every row). This happens with both Standard and Dark themes.

Please see attached screen grabs.

**Comment by nl-savills-insightdata** [comment] 2023-04-01 09:28
@akshay-joshi Is it possible to investigate if this issue can be resolved in the next version? The bug has been present for some time now, and it's unfortunate as it affects the data table, which is one of the most crucial UI elements of the software.

**Comment by akshay-joshi** [comment] 2023-04-03 05:12
@nl-savills-insightdata 

v7.0 will release this week, so not possible in this release but will try to fix it in the next release after 7.0

**Comment by nl-savills-insightdata** [comment] 2023-04-05 15:19
@akshay-joshi Thanks a lot 👍

**Comment by SaiyamK** [comment] 2023-06-05 06:56
As a developer too, I understand that sometimes these things can take time but any updates on this?
Issue is still present in V7.2

**Comment by adityatoshniwal** [comment] 2023-06-05 07:31
HI @SaiyamK,
We're not able to reproduce this on our dev env unfortunately.

**Comment by yogeshmahajan-1903** [comment] 2023-06-05 08:29
@SaiyamK 
Could you please share an example for content result grid?

**Comment by SaiyamK** [comment] 2023-06-05 11:00
I was able to reproduce easily by using the same query again given by @dpage, 

with test_data(aa, bb, cc, dd, ee) AS (
VALUES
(13, 'abc'::varchar, 14, 'def'::varchar, 15),
(16, 'ghi'::varchar, 17, 'jkl'::varchar, 18)
)
SELECT * from test_data

![image](https://github.com/pgadmin-org/pgadmin4/assets/65128538/059cfde0-481d-4e3c-8782-8c81e9f42ef1)
![image](https://github.com/pgadmin-org/pgadmin4/assets/65128538/c3f4a6b7-386d-4c42-bf85-3c16a910fd13)

**Comment by akshay-joshi** [comment] 2024-04-25 06:22
Hi All,

We have tried on a couple of systems to reproduce this issue but it is not reproducible at all.

<img width="989" alt="Screenshot 2024-04-25 at 11 50 24 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/23e3df5d-16bb-427e-b0e5-e8ccd4db1a5e">
 
Closing this issue until we find exact steps to reproduce it.

**Closed by akshay-joshi** 2024-04-25 06:22 UTC
Labels: Bug, EDB Sprint 167
