### ISSUE TITLE
The pgAdmin 4 server could not be contacted

### ISSUE THREAD

**Issue by tanmwork** [pgadmin-org/pgadmin4#7250] opened 2024-02-29 06:46 UTC
![831](https://github.com/pgadmin-org/pgadmin4/assets/158553055/4b8e5cd4-b1f9-42d5-baa8-95155552187f)

Hello, 

Not sure why but we're getting an error prompt while launching the pgAdmin 4 post 8.0 version. The prompt says, 'The pgAdmin 4 server could not be contacted'. And this isn't the case for all machines, we're not getting this error prompt in all of our machines.

Do we have any idea why is this happening and how to resolve this?

**Comment by adityatoshniwal** [comment] 2024-02-29 06:55
@tanmwork Please share the complete log.

**Comment by tanmwork** [comment] 2024-02-29 07:13
[pgAdmin 4 8.0 - installer install.log](https://github.com/pgadmin-org/pgadmin4/files/14444189/pgAdmin.4.8.0.-.installer.install.log)

Here's the complete installer log.

**Comment by akshay-joshi** [comment] 2024-03-01 10:41
@tanmwork 

Could you kindly provide the logs from the "<APPDATA>\Roaming\pgadmin\pgadmin4.log" file and the file of the "<APPDATA>\Local\pgadmin\" folder?

**Comment by tanmwork** [comment] 2024-03-01 11:28
We download the installer from https://www.postgresql.org/ftp/pgadmin/pgadmin4/.

I'll get back with the logs shortly.

**Comment by tanmwork** [comment] 2024-03-01 11:31
[pgadmin4.log](https://github.com/pgadmin-org/pgadmin4/files/14460453/pgadmin4.log)

Here's the log from "\Roaming\pgadmin\pgadmin4.log".

**Comment by tanmwork** [comment] 2024-03-07 11:19
Hello, checking for any updates here.

Also, at '\Local\pgadmin', we have the downloaded installer and our internal developed file.json which holds the silent parameters which takes case of installing the app via command line.

**Comment by anilsahoo20** [comment] 2024-03-29 11:33
No reply from author, hence closing the issue.

**Comment by tanmwork** [comment] 2024-04-10 06:02
Hello, apologies for delayed response here.

As an update we tested the app in a new build machine and that specific user still got the same error after launching the app as mentioned above.

OS of that machine is - Windows 10 22H2 version.

**Comment by tanmwork** [comment] 2024-04-12 10:24
Hi @anilsahoo20 / @adityatoshniwal , could you please check?

**Comment by tanmwork** [comment] 2024-04-17 09:17
Hello, checking for any updates here.

**Comment by anilsahoo20** [comment] 2024-04-19 11:59
Hi @tanmwork,

Unfortunately we are not able to reproduce this. 
This looks like issue with specific Windows versions.

Please provide the screenshot of the complete OS details including the build version.

**Comment by adityatoshniwal** [comment] 2024-04-22 04:53
@tanmwork What your system processor? If its AMD then it may be related to https://github.com/nwjs/nw.js/issues/8008.

**Comment by tanmwork** [comment] 2024-04-22 06:08
Here's the OS & Processor details:

![image](https://github.com/pgadmin-org/pgadmin4/assets/158553055/cbe1e10f-8b12-4bbd-bd7e-9f3cede1eb19)

Processor - 12th Gen Intel(R) Core(TM) i7-12700   2.10 GHz

**Comment by tanmwork** [comment] 2024-04-26 06:57
We have this version of windows common to all workstations & VMs but we're getting this error on some machines only.

Doesn't seems like windows specific issue.

**Comment by akshay-joshi** [comment] 2024-04-26 11:15
We are not able to reproduce this and as per the author it's reproducible only on some machines, it's been difficult to reproduce the issue.

**Closed by akshay-joshi** 2024-04-26 11:15 UTC
