### ISSUE TITLE
pgadmin4 install failed - no valid openPGP-data found

### ISSUE THREAD

**Issue by Elepfant** [pgadmin-org/pgadmin4#7788] opened 2024-08-06 10:06 UTC
Hi,

I tried to follow the instructions from here https://www.pgadmin.org/download/pgadmin-4-apt/ to install pgadmin4. When I try to create the repo config file, it responds:

`curl: (28) failed to connect to [www.pgadmin.org](http://www.pgadmin.org/) port 443 after 129783 ms: couldn_t connect to server gpg: keine gültige OpenPGP-Daten gefunden (no valid openpgp data found)`

When I try 

`sudo apt update`

it says:

`E: The repository 'https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/bookworm pgadmin4 InRelease is not signed` 

Thanks for any hints how to solve this and install pgadmin4!

**Comment by dennislebedev** [comment] 2024-08-09 06:37
Having similar issue. Trying to install pgAdmin4 on Ubuntu 24.04 LTS using instructions, keep getting the error:
`Failed to fetch https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/noble/dists/pgadmin4/main/binary-amd64/pgadmin4-server_8.10_amd64.deb  Could not handshake: Error in the pull function.`

**Comment by yogeshmahajan-1903** [comment] 2024-08-09 07:22
Currently , pgAdmin4 installers is not supported on linux arm machines. Alternatively , you can use pip installation.
Duplicate of [#4780](https://github.com/pgadmin-org/pgadmin4/issues/4780)

**Closed by yogeshmahajan-1903** 2024-08-09 07:22 UTC
Labels: Bug

**Comment by dennislebedev** [comment] 2024-08-09 07:33
I'm using x86-64
