### ISSUE TITLE
Schema diff

### ISSUE THREAD

**Issue by king2** [pgadmin-org/pgadmin4#6523] opened 2023-07-03 04:57 UTC
When trying to compare schemas (version 7.4), schema diff function sometimes wants to change schema that is already identical.
For example, it wants to re-create a trigger, when trigger already exists with exact same DDL.

![Screenshot_12](https://github.com/pgadmin-org/pgadmin4/assets/2644588/2a0e74d9-8aac-4748-a55a-82f6a2010e42)

**Comment by akshay-joshi** [comment] 2023-07-03 05:54
@king2 

Can you please provide the exact DDL for Table and Trigger on Source and Target Database?

**Comment by king2** [comment] 2023-07-03 06:56
Same DDL except of owner (copy-pasted from schema diff window, and another file if from CREATE SCRIPT):
[ddl.zip](https://github.com/pgadmin-org/pgadmin4/files/11933954/ddl.zip)

p.s. Another database works fine, no changes found. DDL is same again, except of table owner.

**Comment by akshay-joshi** [comment] 2023-07-03 07:01
@king2 

Please select 'Ignore Owner' from the drop-down near Compare button and try again.
<img width="1050" alt="Screenshot 2023-07-03 at 12 29 40 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/868b75c9-9dd8-4f7f-9bd7-d37155db1855">

If it works then please close the issue.

**Comment by king2** [comment] 2023-07-03 09:23
'Ignore owner' turned on (of course), so schema diff does not wants to change owner.
It just wants to change a trigger :(

Maybe I have to provide some additional information about databases?
I compare source database to target1 and target2, with target1 it wants to re-create a trigger, but with target2 everything is ok (same DDL in both cases).

**Comment by akshay-joshi** [comment] 2023-07-04 05:09
@king2 

I have tried with the DDL that you have provided in the zip file, also created two identical trigger functions "public.mark_product_search_product()" and "public.mark_row_modified()" in source and target database. I am not able to reproduce the issue.

<img width="1227" alt="Screenshot 2023-07-04 at 10 34 23 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/3040994f-b7f8-4bb5-9961-a0d24eab5051">

Can you please check the definition of the trigger function "public.mark_product_search_product()" and "public.mark_row_modified()"? if it is different then the behaviour is expected. Please try with 'Ignore Whitespace' option as well.

**Comment by akshay-joshi** [comment] 2023-07-20 07:08
No response from the author, hence closing it.

**Closed by akshay-joshi** 2023-07-20 07:08 UTC
Labels: Bug
