### ISSUE TITLE
Shared server connections are using the wrong credentials when accessing the Query Tool 

### ISSUE THREAD

**Issue by kpestaina** [pgadmin-org/pgadmin4#5562] opened 2022-11-22 17:49 UTC
Running Pgadmin4 server, v6.15 
Issue:
- As an Admin, I create a shared connection. I must specify a user at this time. 
- Log out (of pgadmin)
- Log in as a user and connect using the shared server (with my own unique credentials). I connect successfully.
- I select a database and open the query tool. The tool shows 'disconnected' and I get no results when running a query.

Logs on the pgadmin server show my successful connection to the db. When I open the query tool, the logs show that I am attempting to connect as the original user (that the admin used at shared server creation). Since I used my own unique credentials, this of course doesn't work and the tool is not usable. 
Unless I am doing something incorrectly, it seems that the query tool should be using my (user) credentials, which of course are valid. Thanks for any assistance you can provide.

**Comment by yogeshmahajan-1903** [comment] 2022-11-23 04:21
@kpestaina 
Can you please try on v6.16 release on 19 Nov. The issue is fixed in version 6.16

**Comment by akshay-joshi** [comment] 2022-11-25 11:37
Duplicate of #5533

**Closed by akshay-joshi** 2022-11-25 11:37 UTC
