### ISSUE TITLE
Schema Diff ignore grants option

### ISSUE THREAD

**Issue by ddjuric1** [pgadmin-org/pgadmin4#5759] opened 2023-01-18 18:14 UTC
When comparing two schemas on different servers/databases and different name,
can it be possible to ignore grants, like we already can ignore owner?

Regards

**Comment by adityatoshniwal** [comment] 2023-01-19 04:32
@ddjuric1 Did you try v6.19? As the owner is ignored, the grants should also be because they're based on owner. This change is included in 6.19.

**Comment by ddjuric1** [comment] 2023-01-19 09:22
@adityatoshniwal  I'm using v6.19. I have two servers. On both of them I have databases with the same name an with differently named schemas and different owners.  As can be seen in the pictures, some objects still shows different attributes because of different owners, and also grants.

Regards

![Capture1](https://user-images.githubusercontent.com/87120049/213403969-aa68d956-0f93-4cb1-9da8-0fc71f4fcf25.JPG)
![Capture2](https://user-images.githubusercontent.com/87120049/213403987-500e94b5-7f22-465c-9510-53d85b93601f.JPG)

**Comment by akshay-joshi** [comment] 2023-01-19 10:21
@ddjuric1 'Ignore owner' is working fine can you please uncheck/check again and click on the 'Compare' button? 
For grants, it seems to duplicate of #5695

**Comment by ddjuric1** [comment] 2023-01-19 10:43
Hi @akshay-joshi 

I did as you asked (and more), I turned off "Ignore owner" and click Compare and got all objects from both schemas as different, then, turned on "Ignore owner", click Compare and again got different objects as shown in the above images. The "Ignore grants" option would be useful even if the schemas and owners were the same. Grants are not the same category as Owner.

Regards

**Comment by yogeshmahajan-1903** [comment] 2023-08-23 05:23
Working fine.

**Closed by yogeshmahajan-1903** 2023-08-23 05:23 UTC
Labels: Feature, EDB Sprint 149
