### ISSUE TITLE
Add option to only show nodes with content

### ISSUE THREAD

**Issue by indiketa** [pgadmin-org/pgadmin4#5826] opened 2023-02-05 16:19 UTC
Navigating through the nodes of the database tree becomes very tedious if you have several schemas you are forced to do a lot of scroll between object types when most of them are empty.

It would a greatly navigation simplification to add an option to only show nodes that have objects inside.

**Comment by yogeshmahajan-1903** [comment] 2023-02-10 11:35
Duplicate of #5048

**Closed by yogeshmahajan-1903** 2023-02-10 11:35 UTC
Labels: Feature
