### ISSUE TITLE
PgAdmin 7.5 dont download big data

### ISSUE THREAD

**Issue by tiitmats** [pgadmin-org/pgadmin4#6687] opened 2023-08-16 06:34 UTC
**Describe the bug**
If I do query where results are more than 1 million row. Then I can not able to save this in my computer. 
Downloading newer ending

**To Reproduce**
1. Connect remote database
2. Open Query Tool (Click on 'Query Tool')
3. Write query
4. Execute query (Click on 'Execute/Refresh'
5. Wait to finish query
6. Download result table (Click on 'Save results to file')

**Expected behavior**
Pop up 'Save file' dialog window to save file

**Error message**
There is not error messages.

**Screenshots**
![pgadmin](https://github.com/pgadmin-org/pgadmin4/assets/31690333/874e95c2-9ba7-4011-bd1a-1115fa3a6586)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 22H2
 - Mode: Desktop
 - Browser (if running in server mode): Chromium 115.0.5790.98
 - Package type: ?

**Comment by nikhil-mohite** [comment] 2023-08-25 12:02
Duplicate of #3369

**Closed by nikhil-mohite** 2023-08-25 12:02 UTC
Labels: Bug
