### ISSUE TITLE
Proper Application-Update function

### ISSUE THREAD

**Issue by Hypernut** [pgadmin-org/pgadmin4#6995] opened 2023-11-23 15:41 UTC
**Describe the solution you'd like**

The usual: 
When a new version is available, PGadmin should offer to update the application and ask whether to keep settings and server config. 
The update process should be running without any further user action required in the original installation path, even if that wasn't the default path.

**Comment by yogeshmahajan-1903** [comment] 2023-11-24 11:14
Duplicate of #5766

**Closed by yogeshmahajan-1903** 2023-11-24 11:14 UTC
Labels: Feature
