### ISSUE TITLE
pgAdmin 4.6.17 completely crashes iMAC running Monterey 12.6.1

### ISSUE THREAD

**Issue by SoftImp** [pgadmin-org/pgadmin4#5619] opened 2022-12-08 06:15 UTC
Have successfully setup Postgres 15.1 on MacOS Monterey 12.6.1 - separately to a legacy Postgres 10.3 version.  Successfully downloaded and installed pgAdmin 4.6.17.  Started up pgAdmin and it listed all unconnected/connected servers associated with Postgres 10.2 and 15.1.  All seemed OK until I tried to open a server group.  Everything completely crashed - it takes several minutes for the iMAC to restart.  This happened a few times before I decided to remove the data directory containing the Posgres 10.2 stuff.   Still the same problem.  I then removed pgAdmin 4.6.17 and installed 4.6.10 instead.  This seems to have fixed the problem, but the legacy server list is still there.  However, I can now at least remove the ones I don't need.  Haven't done much testing regarding the stability of pgAdmin 4.6.10 with Postgres 15.1.  BTW, I've been using MacOS since version 10.1 (circa 2000).  I can count on one hand the number of times I've experienced any crash let alone one as serious as what I've experienced with pgAdmin 4.6.17.

**Comment by pravesh-sharma** [comment] 2022-12-09 11:36
@SoftImp 

Can you please share log file with us.

Go to: File -> Runtime -> View log

<img width="1435" alt="Screenshot 2022-12-09 at 5 04 02 PM" src="https://user-images.githubusercontent.com/111979571/206693941-b982c703-067a-4e04-b55a-ee254291b828.png">

**Comment by SoftImp** [comment] 2022-12-09 23:13
Pravesh,

This may be a bit awkward because I have now replaced pgAdmin. 4.6.17 with 4.6.10 which (so far) doesn’t seem to possess the same problem.  With 4.6.10 I can at least open DB Servers containing PostgreSQL 10.2 stuff.  I simply couldn’t do that when using 4.6.17.  In fact, the environment was so unstable that I couldn’t create anything for PostgreSQL 15 either, except for a new server group.
I did think to look at the log, but I didn’t see anything there that could help me to but then I’m no expert at reading/interpreting pgAmin logs - simply because I’ve never had any problems with the product previously when working on earlier versions of both MacOS and pgAmin.  It’s been a really great product!  So you can imagine the ‘shock’ I experienced with this issue.
My current feeling is that I don’t really want to reset up 4.6.17 to just obtain a log output.
Perhaps, my circumstances are unique, but I would guess that someone else is likely to experience the same problem at some time.  My experience can at least alert you to the possibility.🥴

Regards.

Clive.

Dr Clive Boughton
Software Improvements
BYWONG NSW

**Comment by khushboovashi** [comment] 2022-12-12 05:10
Closing the ticket as we couldn't find the root cause without logs.

**Closed by khushboovashi** 2022-12-12 05:10 UTC
