### ISSUE TITLE
Data load when selecting column for the GIS viewer is silent (RM #7352)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5044] opened 2022-05-03 12:21 UTC
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7352***
*Originally created by **Dave Page** at 2022-05-03 12:21:01 UTC.*

When a column is selected for viewing in the GIS viewer, we load all rows. However, no activity indication is given, so pgAdmin seems to hang for a few seconds if there is a lot of data.

**Comment by jimmy-citian** [comment] 2023-04-23 18:43
Have there been any updates? I'm unable to update to pgAdmin 6.9 or later versions because of this issue or a similar one.  
On pgAdmin 6.9 or above if I query a table and just select the geometry to view in the Geometry Viewer, the Geometry Viewer loads quickly without issue. For example:
```sql 
SELECT 
    geometry
FROM table_1
``` 
However, specifying any other columns will lead to hanging when using the Geometry Viewer. Also the duration of the hanging seems to increase if more rows are selected. For example:
```sql
SELECT 
    geometry,
    1 AS table_id
FROM table_1
``` 

On pgAdmin 6.8, I can run the above query and use the Geometry Viewer **instantly** without an issue. Meanwhile on pgAdmin 6.9 and later, I have to wait seconds, minutes, or even longer depending on the amount of rows being queried.

**Comment by yogeshmahajan-1903** [comment] 2023-04-24 05:04
@jimmy-citian 
Could you please try updating pgAdmin to 7.0?

**Comment by jimmy-citian** [comment] 2023-04-24 12:58
Sure, I've tried 7.0 and still have the same issue. Viewing just geometry is fine, but viewing geometry as well as other columns will result in hanging.

**Comment by adityatoshniwal** [comment] 2023-04-24 13:13
Hi @jimmy-citian,

We understood the issue, but just to make sure - can you share a screen recording of the issue?

**Comment by jimmy-citian** [comment] 2023-04-24 14:20
Here's a recording using pgAdmin 7.0. It takes a few minutes before the hanging stops.

https://user-images.githubusercontent.com/89405174/234024321-53a8b9b8-24b1-43b1-ba97-79238e618917.mp4

**Comment by anthonydb** [comment] 2023-04-25 10:52
I can confirm similar behavior using pgAdmin 7.0, PostgreSQL 15.2. e.g., adding additional data columns results in a significant delay in rendering the viewer.

**Comment by khushboovashi** [comment] 2023-04-28 08:55
It's fixed on the latest candidate build. 

On my system, I couldn't reproduce the huge delay but just 1 to 2 seconds on older pgAdmin and with this fix, there is no delay.

**Closed by khushboovashi** 2023-04-28 08:55 UTC
Labels: Bug, EDB Sprint 141
