### ISSUE TITLE
Unable to Delete Row with UUID Primary Key in PgAdmin UI on Ubuntu 22.04

### ISSUE THREAD

**Issue by elarte** [pgadmin-org/pgadmin4#6226] opened 2023-05-01 09:41 UTC
Subject: Unable to Delete Row with UUID Primary Key in PgAdmin UI on Ubuntu 22.04

Describe the bug

When using the PgAdmin interface on Ubuntu 22.04 with the pgadmin-desktop package to delete a row in a table with a UUID primary key, the deletion operation fails due to an error in handling the UUID value. The required single quotes around the UUID primary key value are omitted when the DELETE command is executed internally.

To Reproduce

Open PgAdmin on Ubuntu 22.04 and connect to a database containing a table with a UUID primary key.
Navigate to the table that contains the row you want to delete.
Right-click on the table and select "View/Edit Data" -> "All Rows" or "Filtered Rows..." if you want to apply a filter.
Locate the row you want to delete.
Select "Delete/Drop Row" from the bar menu.
See the error message: "Trailing junk after numeric literal at or near "96c" LINE 3: (96c03a01-ba1a-4b53-b4d5-c45e17bd7eb2);"
Expected behavior

The row should be deleted successfully without any error message.

Error message

Trailing junk after numeric literal at or near "96c"
LINE 3: (96c03a01-ba1a-4b53-b4d5-c45e17bd7eb2);

Desktop (please complete the following information):

OS: Ubuntu 22.04
PgAdmin Version: pgadmin4-desktop 
Mode: Desktop
Package type: DEB
Additional context

As a workaround, executing the DELETE query manually using the Query Tool with the single quotes around the UUID value successfully deletes the row. It would be helpful to have this issue resolved in a future update.

**Comment by ChrisDoesCode** [comment] 2023-05-01 20:41
Confirming this issue as well on mac using pgAdmin 4 - 7.0

**Comment by yogeshmahajan-1903** [comment] 2023-05-02 04:01
Duplicate of #6130. Fix will be available in 7.1 version.

**Closed by yogeshmahajan-1903** 2023-05-02 04:01 UTC
Labels: Bug
