### ISSUE TITLE
Unable to login with password with special characters

### ISSUE THREAD

**Issue by vllama** [pgadmin-org/pgadmin4#5902] opened 2023-02-28 09:42 UTC
Unable to log in with a password with special characters.

Having a password that contains (starts with in my case) a single quote does not work. 
It also echoes the password in plaintext to the screen which is not desirable.    The password was saved and was echoed to the screen first time I tried to log in to this particular connection after upgrading to 6.20.

![image](https://user-images.githubusercontent.com/43180217/221813912-0ecfafbf-21f4-4952-b67b-a0abcbbed6ca.png)

PGADMIN Version: 6.20
This seemed to work in previous versions.

**Comment by yogeshmahajan-1903** [comment] 2023-02-28 10:47
@vllama 
Seems to be duplicate of #5862. Fix will be available in next release.
By the time you can check on nightly build from here https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/

**Closed by yogeshmahajan-1903** 2023-02-28 10:47 UTC
