### ISSUE TITLE
Frequent 'Something went wrong' on getting/setting properties of relations in the tree view

### ISSUE THREAD

**Issue by janhec** [pgadmin-org/pgadmin4#5896] opened 2023-02-24 12:11 UTC
Version 6.20:
![image](https://user-images.githubusercontent.com/15078319/221175163-fd2a8c75-84b8-497c-b9af-bbb03ca9381c.png)
postgresql server version 14.4.
email: jan.heckman at gmail.com.
Problem after editing properties on one or (usually) several relations I get
![image](https://user-images.githubusercontent.com/15078319/221175590-32f4afb3-c4ab-4e1b-838b-ee3fd680e33c.png)
It requires quitting pgadmin, restarting pgadmin, logging in and scrolling back to the intended relation.
This happens so frequently that it disturbs a normal workflow,  e.g.  when adding or editing comments on my relations.
It would help me greatly if this problem is solved.

**Comment by akshay-joshi** [comment] 2023-02-27 05:28
@janhec 

Can you please provide the DDL of such objects where you have faced this issue?

**Comment by janhec** [comment] 2023-02-27 09:04
@akshay-joshi 
They are rather straightforward, e.g.
-- View: sk.lpgkgl

-- DROP MATERIALIZED VIEW IF EXISTS sk.lpgkgl;

CREATE MATERIALIZED VIEW IF NOT EXISTS sk.lpgkgl
TABLESPACE pg_default
AS
 SELECT DISTINCT ON (k.pandid) k.pandid,
    k.pandstatus,
    k.huisnrs,
    k.hoogte,
    k.oppervlak,
    k.naam,
    k.kw_bevi,
    k.kwetsbaar,
    k.kw_bg,
    k.besluitstatus,
    k.populatie_totaal,
    k.wonend,
    k.bijeen,
    k.cel,
    k.gezond,
    k.industrie,
    k.kantoor,
    k.logies,
    k.onderwijs,
    k.sport,
    k.winkel,
    k.kinder,
    k.categorieen,
    k.activiteiten,
    k.perceel,
    k.polygon,
    l.eind_geldigheid,
    l.rrgs_id
   FROM kwetsbaar.gebouwen_sk k
     JOIN sk.lpgcontour_6_vol l ON st_intersects(k.polygon, l.contour_6_geendeken)
WITH DATA;

ALTER TABLE IF EXISTS sk.lpgkgl
    OWNER TO postgres;

COMMENT ON MATERIALIZED VIEW sk.lpgkgl
    IS 'Objecten uit KGL (deels) binnen de maximale ''geendeken'' afstand.';

GRANT SELECT ON TABLE sk.lpgkgl TO baguser;
GRANT ALL ON TABLE sk.lpgkgl TO postgres;
GRANT SELECT ON TABLE sk.lpgkgl TO rkuser;

CREATE UNIQUE INDEX lpgkgl_pandid
    ON sk.lpgkgl USING btree
    (pandid COLLATE pg_catalog."default")
    TABLESPACE pg_default;

Here is (maybe helpful) a treeview
![image](https://user-images.githubusercontent.com/15078319/221519836-1299cb2b-25bc-4e7b-94b4-be18d0379f6b.png)

**Comment by pravesh-sharma** [comment] 2023-03-03 09:57
Hi @janhec,

I am not able to reproduce the issue, can you please share pgAdmin4 logs.

**Comment by janhec** [comment] 2023-03-03 11:01
Hi Pravesh,
See attached.
Regards,
Jan

**Comment by janhec** [comment] 2023-03-03 13:00
I'll retry this way.
[pgadmin.zip](https://github.com/pgadmin-org/pgadmin4/files/10882138/pgadmin.zip)

**Comment by pravesh-sharma** [comment] 2023-03-06 13:57
Hi @janhec 

Can you please try reproducing this issue again and share the browser console output, you can open the app in browser, I have attached an screenshot for help.
<img width="1784" alt="Screenshot 2023-03-06 at 7 26 20 PM" src="https://user-images.githubusercontent.com/111979571/223130326-78e37d4b-1724-4878-b951-4983ce5b6a88.png">

**Comment by janhec** [comment] 2023-03-09 17:14
Hi, I found a work-around. I need, with SQL menu item active, to hit another view or table in the TOC, before (re)opening the properties of a view. Doing that I did not have the problem recurring.
I am sorry for not answering quicker, but what you suggested is really not easy on a windows installation, or I could not get it to work with the image you helpfully supplied.

**Comment by adityatoshniwal** [comment] 2023-03-17 11:27
Hi @janhec ,

As per the DDL of your view it has the following tables:
```
FROM kwetsbaar.gebouwen_sk k
JOIN sk.lpgcontour_6_vol l ON st_intersects(k.polygon, l.contour_6_geendeken)
```
So can you please also share the table DDLs to see if we it is reproducible?

**Comment by adityatoshniwal** [comment] 2023-03-20 12:48
Hi @janhec,

We tried all possible ways to reproduce the issue but was not able to. If the issue persists very frequently then I'd suggest uninstalling pgAdmin, remove all the installed files and install again. I am closing the issue.

Thanks.

**Closed by adityatoshniwal** 2023-03-20 12:48 UTC
Labels: Bug
