### ISSUE TITLE
pgAdmin window gets wider when re-opened.

### ISSUE THREAD

**Issue by simon-kempster** [pgadmin-org/pgadmin4#5755] opened 2023-01-18 09:40 UTC
Every time I open pgAdmin, its window is 16 pixels wider than when it was closed.

Steps to reproduce the behaviour:
1. Open pgAdmin.
2. Note size of window (I use WinSize 1.6 Beta 1).
3. Close pgAdmin.
4. Open pgAdmin.
5. Note size of window is now 16 pixels wider than in step 2.

When re-opening pgAdmin, I expect the window to be the same size as when it was last closed.

 - OS: Windows Server 2019 1809 Build 17763.3887
 - Version: Started in 6.17, I believe, still present in 6.19.
 - Mode: Desktop

I connect to a remote virtual machine to work on.  The local machine has 3 monitors, each 1920x1080, set up using Nvidia Surround to appear as one monitor of 5760x1080.

**Comment by simon-kempster** [comment] 2023-06-15 12:30
Update: still present in version 7.3.

**Comment by thomasgodart** [comment] 2023-06-18 04:11
I just submitted https://github.com/pgadmin-org/pgadmin4/issues/6464 for MacOS. Might or might not be related

**Comment by akshay-joshi** [comment] 2024-04-26 11:51
Not able to reproduce with the latest version, hence closing it.

**Comment by simon-kempster** [comment] 2024-04-26 13:05
I'm still seeing this issue up to 8.5,  What resolution screen are you testing this on?

**Comment by akshay-joshi** [comment] 2024-04-29 08:15
@simon-kempster 

I have reopened #6464, we will check it on Windows as well.

**Comment by akshay-joshi** [comment] 2024-05-03 05:45
As i mentioned we will take care of this as a part of #6464

**Closed by akshay-joshi** 2024-05-03 05:45 UTC
Labels: Bug
