### ISSUE TITLE
when trying to delete an row/entry from the table using pgAdmin, it's throwing an Error

### ISSUE THREAD

**Issue by dhavalveera** [pgadmin-org/pgadmin4#6235] opened 2023-05-03 07:30 UTC
Hello,

I am using the latest version of `pgAdmin` which is v4 7.0, where I am trying to delete an Entry/Row from the Table, I am unable to do it, and I am getting below Error.

pgAdmin Version => v4 7.0
Windows 11 - Version 22H2

![image](https://user-images.githubusercontent.com/32231977/235855138-b4aa2a7e-d4e7-4241-9d5e-ad68230c1f39.png)

then Steps I am following to Delete a Row:

- Select Row
- clicking on Delete Icon
- then clicking on Save Icon,

and afterward I am getting the above error, and also I tried reinstalling the pgAdmin v4 7.0, but getting the same error.

please help me

**Comment by ilrobyt** [comment] 2023-05-03 07:58
Hi, i've same problem to delete a row: pgadmin4 take the value of the first column as a column name..
![immagine](https://user-images.githubusercontent.com/39186354/235860832-5c055a76-d895-447d-93a0-5db3fee25d9b.png)
![immagine](https://user-images.githubusercontent.com/39186354/235860938-323626e7-3630-4a1c-a57b-c532a78f2973.png)

**Comment by nikhil-mohite** [comment] 2023-05-03 08:11
Duplicate of https://github.com/pgadmin-org/pgadmin4/issues/6130. A fix will be available in the 7.1 version.

**Closed by nikhil-mohite** 2023-05-03 08:11 UTC
