### ISSUE TITLE
MAX_QUERY_HIST_STORED from config_local.py is ignored

### ISSUE THREAD

**Issue by vnicolici** [pgadmin-org/pgadmin4#6533] opened 2023-07-05 18:40 UTC
pgAdmin 7.3 ignores the MAX_QUERY_HIST_STORED setting from the "C:\Program Files\pgAdmin 4\v7\web\config_local.py" file, and defaults to 20 regardless of the actual value from the file.

1. Create a file with this content at "C:\Program Files\pgAdmin 4\v7\web\config_local.py":

```
MASTER_PASSWORD_REQUIRED=False
MAX_QUERY_HIST_STORED=1000
```

2. Start pgAdmin
3. Run 25 distinct queries on a database
4. The first 5 queries will no longer show up in the query history, only the last 20 will be displayed
5. Check the actual value of the parameter in the about page. It will show 20 instead of 1000.

**Expected behavior**

I expected all 25 queries to show up in history, and to see the correct value of 1000 for the parameter in the about page.

**Screenshots**

![Qi1wWPp](https://github.com/pgadmin-org/pgadmin4/assets/2158971/79572092-df16-4ee1-ae07-d8bf4d91a06c)
![DGC9DWz](https://github.com/pgadmin-org/pgadmin4/assets/2158971/7775f611-8669-4a91-8649-70e1d8a78eb3)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 7.3
 - Mode: Desktop
 - Package type: .exe

**Additional context**

This bug was introduced recently, I don't remember having this issue in the past. Not sure which version was the last one where this worked properly.

I can't use 7.4 due to other bugs (lost connection when running queries that return a lot of data).

Regardless of this bug, in my opinion the default for this parameter is way to low. And not being able to configure this parameter from the UI doesn't make any sense to me.

pgAdmin is a quite unstable app, it crashes for me about once per day. It just closes. This means all unsaved query text is lost, and the only chance to recover it is to find it in history, if by any chance it was executed earlier. Losing a huge query I worked maybe hours on because of the very low history setting can be quite frustrating. Yes, I know, I can save to prevent that. But, if for some reason I forget to do that, having a large history would be a failsafe.

Web browsers can restore part of their state after crashes, perhaps this feature could be be added to pgAdmin too, save all the unsaved tabs periodically to some temporary files.

**Comment by khushboovashi** [comment] 2023-07-06 05:50
Hi @vnicolici,

I couldn't reproduce this issue. Please check the config_local.py has proper permission so that pgAdmin can read the file.

Thanks,
Khushboo

**Comment by vnicolici** [comment] 2023-07-06 06:40
I found the problem. The application was previously installed for all users, and used that directory. On one of the recent downgrades I did I forgot which setting I used previously, and I installed it for my user only, so the installation directory changed.

I had the same problem when upgrading from pgAdmin 4 v6 to pgAdmin 4 v7, since the installation directory path changes on major version updates.

Ideally, pgAdmin would also look for this file in the user directory, something like %USERPROFILE%\.pgadmin\config_local.py or %APPDATA%\pgAdmin\config_local.py, instead of just the installation directory. This way future version upgrades or changing the installation type from local to all users will no longer cause this problem. Having to place user configuration files for an application inside its installation directory, instead of the user directory, is a bit unusual, to say the least.

In any case, I renamed the file to "c:\Program Files\Common Files\pgadmin\config_system.py" , and it fixed my problem, and hopefully this will prevent the file from being ignored after future updates or downgrades.

**Comment by khushboovashi** [comment] 2023-07-06 06:55
> I found the problem. The application was previously installed for all users, and used that directory. On one of the recent downgrades I did, I forgot which setting I used previously, and I installed it for my user only, so the installation directory changed.
> 
> I had the same problem when upgrading from pgAdmin 4 v6 to pgAdmin 4 v7, since the installation directory path changes on major version updates.
> 
> Ideally, pgAdmin would also look for this file in the user directory, something like `%USERPROFILE%\.pgadmin\config_local.py` or `%APPDATA%\pgAdmin\config_local.py`, instead of just the installation directory. This way future version upgrades or changing the installation type from from all users to current user will no longer cause this problem. Having to place user configuration files for an application inside its installation directory, instead of the user directory, is a bit unusual, to say the least.

The config_local.py file is not a user-specific configuration file. The changes in the file will apply to the application level.
> 
> In any case, I renamed the file to `c:\Program Files\Common Files\pgadmin\config_system.py` , and it fixed my problem, and hopefully this will prevent the file from being ignored after future updates or downgrades.

For more details, please refer https://www.pgadmin.org/docs/pgadmin4/7.4/config_py.html.

I am closing this issue.

**Closed by khushboovashi** 2023-07-06 06:55 UTC
Labels: Bug, EDB Sprint 146

**Comment by vnicolici** [comment] 2023-07-06 06:59
> The config_local.py file is not a user-specific configuration file. The changes in the file will apply to the application level.

Then the documentation needs to be updated. Because it mentions: "config_local.py: This file is read after config_distro.py and is intended for **end users** to change any default"

**Comment by vnicolici** [comment] 2023-07-06 07:27
Thinking more about it, if you install the application for the current user only on Windows, the application directory is actually inside the user directory, so it does actually behave like "a user-specific configuration file" in that situation. It's just that each of the users will each have to install a copy of the application to be able to configure these settings independently. So, in addition to preventing the issue I had, having user specific configuration files outside the application directory would prevent wasting disk space with multiple installations. In any case, for me personally this is not an issue anymore I found a workaround for the problem and I'm the only person using my computer.

**Comment by khushboovashi** [comment] 2023-07-13 06:12
Updated he documentation for the config_local.py explanation. Ref: https://www.pgadmin.org/docs/pgadmin4/development/config_py.html

**Comment by vnicolici** [comment] 2023-07-13 11:09
> Updated he documentation for the config_local.py explanation. Ref: https://www.pgadmin.org/docs/pgadmin4/development/config_py.html

Thank you.

**Comment by ggriffin** [comment] 2023-12-06 19:00
> In any case, I renamed the file to `c:\Program Files\Common Files\pgadmin\config_system.py` , and it fixed my problem, and hopefully this will prevent the file from being ignored after future updates or downgrades.

@khushboovashi I am having a similar experience on MacOS 13.6, so this still appears to be an issue.

Creating a `config_local.py` file, with an increased `MAX_QUERY_HIST_STORED` value, stored in the same `/Applications/pgAdmin 4.app/Contents/Resources/web` folder as `config.py`, per the docs, had NO effect. Renaming `config_local.py` to `config_system.py` resolved the issue.
