### ISSUE TITLE
Editable shortcut for comments

### ISSUE THREAD

**Issue by Tobeyforce** [pgadmin-org/pgadmin4#6699] opened 2023-08-18 10:31 UTC
**Describe the solution you'd like**

On ubuntu/linux, the ability to change all comment-related shortcuts, both toggling line comments and block comments.

**A clear and concise description of any alternative solutions or features you've considered.**

None at this point, I just think commenting queries should be changeable, just like in vscode. It's one of the most common things you do as a developer when writing code.

**Additional context**

None of the preset shortcuts work for me using a scandinavian keyboard, had it been modifiable I could have just changed the shortcut, but for example ctrl + / doesn't work. It would be greatly appreciated if you could add this feature.

**Comment by nikhil-mohite** [comment] 2023-08-25 11:32
Duplicate of #2659

**Closed by nikhil-mohite** 2023-08-25 11:32 UTC
Labels: Feature
