### ISSUE TITLE
Modified SQL is not being displayed in properties of any object if the user modifies a query outside from pgadmin4 and click on the refresh button

### ISSUE THREAD

**Issue by FaharAbbasRizvi** [pgadmin-org/pgadmin4#6142] opened 2023-04-17 06:52 UTC
**To Reproduce**

1. Go to table node or any object
2. object created succesfully
3. Expand this newly created object
4. Click on properties tab
5.  open PSQL tool outside pgadmin4
6. execute the following query
COMMENT ON TABLE public.test
  IS 'abc';
7. comment created
8. Now Right Click and Click on the refresh button
9.  No comment is visible

**Expected behavior**

Modified SQL should be displayed in properties of any object if the user modifies a query outside from pgadmin4 and click on the refresh button

**Desktop (please complete the following information):**
 - OS: [All]
 - Version: [7.0]
 - Mode: [All]
 
 - Package type: [All]

**Comment by nikhil-mohite** [comment] 2023-04-24 07:13
Duplicate of #6158

**Closed by nikhil-mohite** 2023-04-24 07:13 UTC
Labels: Bug
