### ISSUE TITLE
Ability to Edit the View/Edit Data Query as if it were a query tool pane

### ISSUE THREAD

**Issue by stephenhutch** [pgadmin-org/pgadmin4#5908] opened 2023-03-02 06:58 UTC
**Describe the solution you'd like**

When selecting data from a particular table using the `right click on table` -> `view/edit data` -> `First 100 rows` menu item.
The returned query should allow for editing and execution of the given query by the user (in the same pane) - similar to the `query tool`.

**Describe alternatives you've considered**

Perhaps a button that can convert the `view/edit data` pane into a `query tool` pane.

**Additional context**

Example images given in this [stackoverflow question: [How to edit the SQL string in pgAdmin's "Last 100 Rows" window?](https://stackoverflow.com/questions/72422479/how-to-edit-the-sql-string-in-pgadmins-last-100-rows-window).

**Comment by akshay-joshi** [comment] 2023-03-03 11:41
This is by design, you can open the Query Tool and copy the Query from Query History.
closing the issue.

**Comment by stephenhutch** [comment] 2023-03-03 12:17
The issue is raised as an improvement on this existing poor user experience.
Perhaps instead of `view/edit data` an additional context menu item be added saying `select first 100 records in query tool` which will run the same query as from `view/edit` but then allow the user to modify the query.

**Comment by dpage** [comment] 2023-03-03 13:33
Personally I would like to merge both "versions" of the tool together, however the last time we polled users about this, folks seemed to prefer it as-is.

The crux of the problem here is that in Edit Grid mode, changes to the query are done through the UI, whilst in Query Tool mode, the user edits the query themselves. It would not be overly hard to "promote" an Edit Grid to a Query Tool (maybe upon first manual edit of the Query, with a suitable warning to the user), however, going the other way is not feasible.

I'm inclined to leave this on the TODO list. We get a steady stream of similar requests.

**Comment by usernamesareaholdoverfromthe90s** [comment] 2023-03-08 15:32
Up vote for this enhancement.  I find it perplexing that I can edit the query tool directly, but that I have to click the "Sort/Filter" icon to edit the select statement to ORDER BY.  You show the SQL being used to generate the results, why not let me edit it?

I mean why does the view/edit data even exist anymore (I know... there's definitely a reason), because the Query Tool is already now intelligent to recognize whether fields can be.

E.g., If I do "select * from TableA" in the Query Tool, then I'm allowed to edit the values, just like I can with View/Edit, presumably because the Query Tool recognizes that all rows from TableA (and nothing else) is included as columns in the results.  And, if I subsequently edit the query to be "select field from TableA" or "select * from TableA as a, TableB as b where..." then the Query Tool is smart enough to say that the edit row can't be written back.

So would it not be possible to have View/Edit simply create a Query Tool with the appropriate pre-generated SQL and let the user do with it what they want?

CAVEAT: I know, I'm looking at this strictly through my own lens, and there are undoubtedly other user cases that merit having the View/Edit interface be different than the Query Tool.

**Comment by gmiklich** [comment] 2023-04-20 15:39
It'd be interesting to see the poll if you have that handy.  I'm honestly surprised that people prefer the current state.  Personally, picturing using the UI to simply update a sort feels clunky compared to intellisense/autocomplete.  To each there own I guess.  Thank you dpage for explaining the reasoning behind the functionality.

However, as stephenhutch mentioned, this is at very least an enhancement to the UX.  Even with a "workaround" of copy-pasting queries, it's so much nicer to be able to just right click -> view records -> edit the query for what you need.  Knowing that there is some difficulty in reconciling the whole "edit grid" vs "query tool" thing, I won't necessarily suggest an implementation.  But it would be a great improvement to have a way to easily pre-populate an editable query.

**Comment by kevinhikaruevans** [comment] 2023-07-17 16:52
Just wanted to voice my support for this enhancement. I'm a new user coming from SSMS and MySQL Workbench, and I've really been missing this feature.

An alternative would be to enable the edit button in "View/Edit mode" ![image](https://github.com/pgadmin-org/pgadmin4/assets/4730591/736fa0dd-7af4-41b2-af59-e2c085a563ce) and have that open a new query tool with the query automatically copied over.

**Comment by Schlumie** [comment] 2023-08-02 12:20
An EditToolboxIcon to allow for edit, would not be necessary to be able to get back to Filter/Edit. Just a oneway switch, so that it changes to a normal querytool window.

**Comment by juan-diego89** [comment] 2023-10-16 16:29
When implementing this feature hope you can take some inspiration from how it works on MySQL Workbench. There is very intuitive how it works.

**Comment by pravesh-sharma** [comment] 2023-12-27 04:39
@nikhil-mohite 

I found one UI issue

<img width="1109" alt="Screenshot 2023-12-27 at 9 36 07 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/09a23da1-e534-45d1-9e2d-e049dff7ce2c">

The highlighted button in the above image has a different colour when the normal query tool is opened.

**Comment by pravesh-sharma** [comment] 2023-12-29 07:34
Feature implemented. Verified on snapshot build https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2023-12-29/

Env
OS - macOS Sonoma (14.1.2)
Mode - Desktop

**Closed by pravesh-sharma** 2023-12-29 07:34 UTC
Labels: Feature, EDB Sprint 158
