### ISSUE TITLE
Error when creating table

### ISSUE THREAD

**Issue by rbrooklyn** [pgadmin-org/pgadmin4#7810] opened 2024-08-13 08:16 UTC
**Describe the bug**

Creating a fairly basic table, and I'm seeing the error below:
![image](https://github.com/user-attachments/assets/d8141953-6209-4287-89d7-0e7e1cd69a65)

Error reads:
column "none" named in key does not exist LINE 5: PRIMARY KEY (None) ^

**To Reproduce**

Create a new table with two columns:
"id" with the data type "smallserial" not null, primary key
"description" with the data type "text" not null
Press save

**Expected behavior**

Table should be created.

**Error message**

If possible, include the full, unedited text of any error messages displayed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.10
 - Mode: Desktop
 - Package type: Windows MSI installer

**Comment by anilsahoo20** [comment] 2024-08-14 05:12
Hi @rbrooklyn 
I am not able to reproduce the issue with the given reproducible steps. Can you try using the latest pgAdmin 4. You can get it from [here](https://www.pgadmin.org/download/).

**Comment by rbrooklyn** [comment] 2024-08-16 16:44
I cannot reproduce either.

I'm a little worried this will be like #7210 where it only happens "every now and then" and it will be difficult to track down.

**Comment by adityatoshniwal** [comment] 2024-08-23 10:23
Hi @rbrooklyn,

Please feel free to re-open the issue once you have reproducible steps. Closing for now.

Thanks.

**Closed by adityatoshniwal** 2024-08-23 10:23 UTC
Labels: Bug

**Comment by Davide-Furlani** [comment] 2024-09-14 10:14
found the exact same issue trying to create a 2 column table

![Screenshot from 2024-09-14 11-57-27](https://github.com/user-attachments/assets/0200bfc0-c52c-4de9-b353-34011076a284)

here's the log

>  #pgAdmin Runtime Environment
>  --------------------------------------------------------
>  Python Path: "/usr/pgadmin4/venv/bin/python3"
>  Runtime Config File: "/home/user/.config/pgadmin4/config.json"
>  Webapp Path: "/usr/pgadmin4/web/pgAdmin4.py"
>  pgAdmin Command: "/usr/pgadmin4/venv/bin/python3 -s /usr/pgadmin4/web/pgAdmin4.py"
>  Environment: 
>    - GJS_DEBUG_TOPICS: JS ERROR;JS LOG
>    - LC_TIME: it_IT.UTF-8
>    - USER: user
>    - XDG_SESSION_TYPE: x11
>    - SHLVL: 0
>    - HOME: /home/user
>    - DESKTOP_SESSION: pop
>    - GIO_LAUNCHED_DESKTOP_FILE: /usr/share/applications/pgadmin4.desktop
>    - GTK_MODULES: gail:atk-bridge
>    - GNOME_SHELL_SESSION_MODE: pop
>    - LC_MONETARY: it_IT.UTF-8
>    - MANAGERPID: 5865
>    - SYSTEMD_EXEC_PID: 6537
>    - DBUS_SESSION_BUS_ADDRESS: unix:path=/run/user/1000/bus
>    - GIO_LAUNCHED_DESKTOP_FILE_PID: 10282
>    - LOGNAME: user
>    - GTK_IM_MODULE: ibus
>    - JOURNAL_STREAM: 9:40678
>    - XDG_SESSION_CLASS: user
>    - USERNAME: user
>    - GNOME_DESKTOP_SESSION_ID: this-is-deprecated
>    - WINDOWPATH: 2
>    - PATH: /usr/local/cuda-11.8/bin:/home/user/anaconda3/condabin:/home/user/.cargo/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
>    - PAPERSIZE: a4
>    - SESSION_MANAGER: local/pop-os:@/tmp/.ICE-unix/6510,unix/pop-os:/tmp/.ICE-unix/6510
>    - INVOCATION_ID: 783d39cab27b464abd7cd909d93b270e
>    - LC_ADDRESS: it_IT.UTF-8
>    - XDG_RUNTIME_DIR: /run/user/1000
>    - XDG_MENU_PREFIX: gnome-
>    - DISPLAY: :1
>    - LANG: en_US.UTF-8
>    - LC_TELEPHONE: it_IT.UTF-8
>    - XDG_CURRENT_DESKTOP: Unity
>    - XAUTHORITY: /run/user/1000/gdm/Xauthority
>    - XDG_SESSION_DESKTOP: pop
>    - XMODIFIERS: @im=ibus
>    - SSH_AGENT_LAUNCHER: gnome-keyring
>    - SSH_AUTH_SOCK: /run/user/1000/keyring/ssh
>    - LC_NAME: it_IT.UTF-8
>    - SHELL: /bin/bash
>    - QT_ACCESSIBILITY: 1
>    - GDMSESSION: pop
>    - LC_MEASUREMENT: it_IT.UTF-8
>    - LC_IDENTIFICATION: it_IT.UTF-8
>    - GPG_AGENT_INFO: /run/user/1000/gnupg/S.gpg-agent:0:1
>    - GJS_DEBUG_OUTPUT: stderr
>    - QT_IM_MODULE: ibus
>    - PWD: /home/user
>    - XDG_DATA_DIRS: /usr/share/pop:/usr/share/gnome:/home/user/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
>    - XDG_CONFIG_DIRS: /etc/xdg/xdg-pop:/etc/xdg
>    - LC_NUMERIC: it_IT.UTF-8
>    - LC_PAPER: it_IT.UTF-8
>    - CHROME_DESKTOP: pgadmin4.desktop
>    - ORIGINAL_XDG_CURRENT_DESKTOP: pop:GNOME
>    - ELECTRON_ENABLE_SECURITY_WARNINGS: false
>    - GDK_BACKEND: x11
>    - PGADMIN_INT_PORT: 44421
>    - PGADMIN_INT_KEY: 38gd4d9b-b31d-4282-874a-535f6d9764h2
>    - PGADMIN_SERVER_MODE: OFF
>  --------------------------------------------------------
>  
>  Total spawn time to start the pgAdmin4 server: 0.011 Sec
>  2024-09-14 09:51:51,748: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.
>  
>   * Serving Flask app 'pgadmin'
>   * Debug mode: off
>  
>  ------------------------------------------
>  Total time taken to ping pgAdmin4 server: 7.046 Sec
>  ------------------------------------------
>  Total launch time of pgAdmin4: 7.234 Sec
>  ------------------------------------------
>  Application Server URL: http://127.0.0.1:44421/?key=38gd4d9b-b31d-4282-874a-535f6d9764h2
>  2024-09-14 11:54:28,437: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:PV (Query-id: 6206849):
>  Error Message:column "none" named in key does not exist
>  LINE 5:     PRIMARY KEY (None)
>              ^
>  
>  2024-09-14 11:55:07,043: ERROR	pgadmin:	Failed to execute query (execute_scalar) for the server #1 - DB:PV (Query-id: 5700241):
>  Error Message:column "none" named in key does not exist
>  LINE 5:     PRIMARY KEY (None)
>              ^


restarting pg admin resolved the issue
hope this comment is usefull
