### ISSUE TITLE
Worker PID failing to boot after upgrading to latest version (tags: Latest & 8.13.0)

### ISSUE THREAD

**Issue by farewarr** [pgadmin-org/pgadmin4#8136] opened 2024-11-15 17:07 UTC
PgAdmin container does not fully boot and webpage is not accessible. 

###Container logs: 
 self.wsgi = self.app.wsgi() ^^^^^^^^^^^^^^^ File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi self.callable = self.load() ^^^^^^^^^^^ File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load return self.load_wsgiapp() ^^^^^^^^^^^^^^^^^^^ File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp return util.import_app(self.app_uri) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/venv/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app mod = importlib.import_module(module) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 995, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/pgadmin4/run_pgadmin.py", line 4, in <module> from pgAdmin4 import app File "/pgadmin4/pgAdmin4.py", line 103, in <module> app = create_app() ^^^^^^^^^^^^ File "/pgadmin4/pgadmin/__init__.py", line 754, in create_app app.register_blueprint(module) File "/venv/lib/python3.12/site-packages/flask/sansio/scaffold.py", line 47, in wrapper_func return f(self, *args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/venv/lib/python3.12/site-packages/flask/sansio/app.py", line 595, in register_blueprint blueprint.register(self, options) File "/pgadmin4/pgadmin/tools/__init__.py", line 52, in register from .psql import blueprint as module File "/pgadmin4/pgadmin/tools/psql/__init__.py", line 15, in <module> from eventlet.green import subprocess ModuleNotFoundError: No module named 'eventlet' [2024-11-15 16:15:46 +0000] [106] [INFO] Worker exiting (pid: 106) [2024-11-15 16:15:51 +0000] [1] [ERROR] Worker (pid:106) exited with code 3 [2024-11-15 16:15:51 +0000] [1] [ERROR] Shutting down: Master [2024-11-15 16:15:51 +0000] [1] [ERROR] Reason: Worker failed to boot.

Downgrading to 8.12.0 fixed the issue. Let me know if you have any questions. Thanks.

**Comment by Starstrike** [comment] 2024-11-15 19:32
Duplicate of https://github.com/pgadmin-org/pgadmin4/issues/8133

**Closed** 2024-11-18 04:29 UTC
