### ISSUE TITLE
pgAdmin window gets taller when re-opened (MacOS)

### ISSUE THREAD

**Issue by thomasgodart** [pgadmin-org/pgadmin4#6464] opened 2023-06-18 04:09 UTC
Might or might not be connected with the bug https://github.com/pgadmin-org/pgadmin4/issues/5755 This ticket is about the MacOS version

Every time we open pgAdmin, its window is taller of the menu height (approximately 29 pixels)

1. Open pgAdmin
2. Size it at any non fullscreen size, and position it anywhere
3. Close pgAdmin
4. Open pgAdmin
5. Note that the size of the window is now approximately 29 pixels higher than previously, and that its position on screen is also 29 pixels higher

Expected behavior:

The window should reopen having the same size and same position as when it was closed

 - OS: MacOS 13.x
 - Version: 7.x
 - Mode: Desktop
 - Package type: dmg

I use [Rectangle](https://rectangleapp.com/) to position pgAdmin to the bottom left corner of the screen, Chrome goes to the top left corner and VS Code goes on the right. Developper style

**Comment by akshay-joshi** [comment] 2024-04-26 11:51
Not able to reproduce with the latest version, hence closing it.

**Comment by thomasgodart** [comment] 2024-04-26 13:01
Hi @akshay-joshi, which version are you testing?

I'm using the v8.5 dated on the 4th of April 2024, and I can still see the bug, nothing changed.
I'm now using:

- OS: MacOS 14.4.x
- pgAdmin version: 8.5
- Mode: Desktop
- Package type: dmg

**Comment by akshay-joshi** [comment] 2024-04-29 08:00
Reopen again will check the cause again.

**Comment by akshay-joshi** [comment] 2024-05-03 10:15
This seems to be an NWjs issue [7973](https://github.com/nwjs/nw.js/issues/7973).
We will try to fix this by implementing the workaround given in the above mentioned issue.

**Comment by thomasgodart** [comment] 2024-05-03 10:25
I'm guessing that the library reads the window size somewhere wrong as it looks like obtaining the outer window size including the OS margins (for displaying the window borders), then asks the OS for a window with this inner window size, hence growing it of the size of the margins. Or something like that. Generally speaking you can't guess the OS margins as they depend on the version of the OS and on settings by the user (font size, screen size, etc)

**Comment by akshay-joshi** [comment] 2024-05-08 07:13
@thomasgodart 
Can you please test it on the [Snapshot Build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-08/)

**Comment by thomasgodart** [comment] 2024-05-08 07:28
Thank you @akshay-joshi for your time and efforts to try and fix this.

In this new version "/snapshots/2024-05-08/" the window doesn't expand anymore, but now it shrinks the window height of 22px on every opening. As a comparison, the window title height is 30px. If you need screenshots, I can provide some, feel free to ask.

**Comment by akshay-joshi** [comment] 2024-05-08 07:33
Yesterday, when I fixed it and debugged the code, the window height remained consistent after multiple reopenings. 
I'll have to check again

**Comment by akshay-joshi** [comment] 2024-05-08 10:07
@thomasgodart 

I have checked multiple times and cannot reproduce the shrink issue. I have tested it on Mac OSX Sonoma 14.4

**Comment by thomasgodart** [comment] 2024-05-08 10:23
@akshay-joshi Oh, interesting, let me see then.

The previous growing window bug was consistent on a MacBook Pro 14'' and a Mac Mini M2 Pro, so today I didn't double check both environments when I tested the new version, but I should have.

Turns out that the shrinking window bug only appears on the MacBook and not on the Mac Mini, and yet they have (supposedly) the exact same settings config, as far as I know.

**Comment by pravesh-sharma** [comment] 2024-05-16 09:58
Issue fixed. Verified on snapshot [build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2024-05-16/).

Env:
macOS Sonoma 14.4.1 on MacBook Pro 16"

**Closed by pravesh-sharma** 2024-05-16 09:58 UTC
Labels: Bug, EDB Sprint 168

**Comment by thomasgodart** [comment] 2024-05-16 11:12
@pravesh-sharma Thank you for your efforts.

On the Mac Mini M2 Pro, the bug is fixed, same as with the snapshot build 2024-05-08

But on the MacBook Pro 14'' the window is still shrinking, like on the build 2024-05-08 but it looks stronger now, and seems to depend on the window height or vertical position. Screenshot attached after closing a full vertical height window and reopening. It's shrinking on every opening

<img width="899" alt="Capture d’écran 2024-05-16 à 13 04 10" src="https://github.com/pgadmin-org/pgadmin4/assets/5947477/0d4f77c3-a78c-4677-b6b6-cef2403357dc">

**Comment by pravesh-sharma** [comment] 2024-05-16 11:39
Hi @thomasgodart,

I have tested today's snapshot build on my MacBook Pro 16" and did not face any shrinking issue.

**Comment by pravesh-sharma** [comment] 2024-05-20 04:21
Hi @thomasgodart,

There is nothing much we can do about it as this is an issue with [nwjs](https://github.com/nwjs/nw.js/issues/7973).
We have implemented a work around given in the issue discussion. We have to wait for nwjs to fix it.

**Comment by thomasgodart** [comment] 2024-07-30 13:59
Just updated to MacOS 14.6 and pgAdmin4 8.10, and the window size is fine, not expanding nor shrinking anymore on a MacBook Pro 14''. I'll test the Mac Mini later. Nice 👍🙏
