### ISSUE TITLE
Replace wcDocker with React based rc-dock

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#6479] opened 2023-06-22 06:16 UTC

**Comment by nikhil-mohite** [comment] 2023-10-24 09:34
UI issues:
1. Open multiple Query Tools and try switching the tabs it will show partial selection on the tab title
![image](https://github.com/pgadmin-org/pgadmin4/assets/69510038/8acef408-3466-4442-a3a7-ea5462825d8f)

2. If we open multiple Query Tools quickly after a few seconds it switches to an earlier open query tool(Switching is random), It is not a bug but it should focus on the latest open query tool, (Similar to older behavior)


https://github.com/pgadmin-org/pgadmin4/assets/69510038/16e5ec2c-c837-4a6c-ab59-438d67265d33

3. Preferences `Dynamic tab size` is not getting applied until we use `Reset Layout`

**Comment by nikhil-mohite** [comment] 2023-10-26 11:57
> UI issues:
> 
> 1. Open multiple Query Tools and try switching the tabs it will show partial selection on the tab title
>    ![image](https://user-images.githubusercontent.com/69510038/277609284-8acef408-3466-4442-a3a7-ea5462825d8f.png)
> 2. If we open multiple Query Tools quickly after a few seconds it switches to an earlier open query tool(Switching is random), It is not a bug but it should focus on the latest open query tool, (Similar to older behavior)
> 
>  Open_multiple_query_tool_focus_issue_1.mov 
> 3. Preferences `Dynamic tab size` is not getting applied until we use `Reset Layout`
> 4. icons on the `Create` and `Properties` dialog title are getting partiality hidden
> 
> <img alt="Screenshot 2023-10-24 at 3 06 32 PM" width="509" src="https://user-images.githubusercontent.com/69510038/277616440-2ed05d91-0ac2-4675-8f93-614f09da290d.png">
> 5. Icons alignment issue in schema diff tool
>    ![image](https://user-images.githubusercontent.com/69510038/277634491-ca9ea7c1-4e18-4aad-9ace-dc77f6ba844c.png)
> 6. In the `Process Tab` open any process details, dialog size is smaller than expected.
> 
> <img alt="image" width="779" src="https://user-images.githubusercontent.com/69510038/277634801-6370a9d4-5491-40fc-83aa-c9a21fe49954.png">
> 7. Open Query Tool and check `Connection status icon` is not visible (The issue is reproducible a few times only, didn’t find exact steps for this)

Hi @adityatoshniwal ,

Only issue no 4 is still reproducible, other issues mentioned are fixed

**Comment by yogeshmahajan-1903** [comment] 2023-10-27 07:33
@adityatoshniwal ,

In dev env, with master password enabled, when I click on any server it asks Master password as expected, but background screen gets black. Master password popup is polluted 3 times. If I click on cancel in pop up, I need to click 3 times.

<img width="1792" alt="Screenshot 2023-10-27 at 1 02 01 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/f45ef32a-547b-4348-883e-aae5644b23a2">

**Comment by anilsahoo20** [comment] 2023-10-30 12:10
@adityatoshniwal Autocomplete for Query tool is not working when we set it to True in Preferences Dialog->Query tool->Autocompletion.

It only works with CTRL+Space, irrespective of Autocomplete True or False.

I found the Autocomplete API is not being called.

**Comment by nikhil-mohite** [comment] 2023-10-31 08:49
Hi @adityatoshniwal,

Found UI issues in Object Explorer,
1. Add a new server and make sure it will get added to the end of the existing server. (last server)
This issues is reproducible on other nodes as well where added node is getting added as last node in existing nodes

https://github.com/pgadmin-org/pgadmin4/assets/69510038/be999cac-4a35-472a-bf51-bea84a352744

**Comment by yogeshmahajan-1903** [comment] 2023-10-31 10:43
@adityatoshniwal 
Please find some UI issues - (All testing done in Desktop mode on Ubntu 23.10)
1.Column title row and value rows are miss-aligned in configuration tab.
<img width="1475" alt="Screenshot 2023-10-31 at 1 37 22 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/b6df84c0-6c38-4d12-bc08-1a8b7773685a">

2.If there is error like connection lost, error pop up is shown 3 times.
<img width="1507" alt="Screenshot 2023-10-31 at 1 40 55 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/609413d6-efeb-4acc-a005-21e2dfe6275d">


3.About popup and Logs popup have black border. Intermittent reproducible. May be when you open query tool and after that you open this.
<img width="1455" alt="Screenshot 2023-10-31 at 1 53 42 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/6ad53f3c-e9b9-4261-83bb-71a442e14b63">
<img width="890" alt="Screenshot 2023-10-31 at 1 54 12 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/ef958925-f954-4b17-8bf9-eadb794841b4">


4.When switched to full screen, some blank screen shown on left side.
<img width="1577" alt="Screenshot 2023-10-31 at 1 54 55 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/d4c5d4dd-507d-4143-945b-f4d9ebca6a5f">


5.On entering full screen, Menu label is NOT changed to Exit Full Screen.
<img width="1521" alt="Screenshot 2023-10-31 at 4 11 24 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/a200e92a-1123-46c7-8503-760772691298">


6.Properties tab data keep loading when properties panel is docked from default position and another DB object is selected.
<img width="1521" alt="Screenshot 2023-10-31 at 4 11 24 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/91cc097f-f9d6-40ed-8a9d-64639b706249">

**Comment by adityatoshniwal** [comment] 2023-10-31 11:02
HI @yogeshmahajan-1903, only 2, 6 and 7(Screenshot not visible) are looks related to rc-dock changes. Other are pre-existing or related to NW.js.

**Comment by yogeshmahajan-1903** [comment] 2023-10-31 11:12
> HI @yogeshmahajan-1903, only 2, 6 and 7(Screenshot not visible) looks related to rc-dock changes. Other are pre-existing or related to NW.js.

Okay. Will raise separate issue for the rest.

**Comment by yogeshmahajan-1903** [comment] 2023-10-31 11:22
1.Opening ERD for database in new tab, gives blank window.
<img width="1349" alt="Screenshot 2023-10-31 at 4 38 32 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/01d1538e-bbbc-43e8-ba81-bf117ccaca12">

2.Opening ERD for Database in same window stuck with 'Fetching schema data'
<img width="1491" alt="Screenshot 2023-10-31 at 4 47 04 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/23cdbf94-7a5b-4192-8cdd-b98d7f99a5a2">

**Comment by nikhil-mohite** [comment] 2023-11-01 06:05
> > UI issues:
> > 
> > 1. Open multiple Query Tools and try switching the tabs it will show partial selection on the tab title
> >    ![image](https://user-images.githubusercontent.com/69510038/277609284-8acef408-3466-4442-a3a7-ea5462825d8f.png)
> > 2. If we open multiple Query Tools quickly after a few seconds it switches to an earlier open query tool(Switching is random), It is not a bug but it should focus on the latest open query tool, (Similar to older behavior)
> > 
> > Open_multiple_query_tool_focus_issue_1.mov
> > 3. Preferences `Dynamic tab size` is not getting applied until we use `Reset Layout`
> > 4. icons on the `Create` and `Properties` dialog title are getting partiality hidden
> > <img alt="Screenshot 2023-10-24 at 3 06 32 PM" width="509" src="https://user-images.githubusercontent.com/69510038/277616440-2ed05d91-0ac2-4675-8f93-614f09da290d.png">
> > 5. Icons alignment issue in schema diff tool
> >    ![image](https://user-images.githubusercontent.com/69510038/277634491-ca9ea7c1-4e18-4aad-9ace-dc77f6ba844c.png)
> > 6. In the `Process Tab` open any process details, dialog size is smaller than expected.
> > <img alt="image" width="779" src="https://user-images.githubusercontent.com/69510038/277634801-6370a9d4-5491-40fc-83aa-c9a21fe49954.png">
> > 7. Open Query Tool and check `Connection status icon` is not visible (The issue is reproducible a few times only, didn’t find exact steps for this)
> 
> Hi @adityatoshniwal ,
> 
> Only issue no 4 is still reproducible, other issues mentioned are fixed

The issue no 4 is fixed with the latest code.

**Comment by pravesh-sharma** [comment] 2023-11-01 10:34
The All Rows (view/edit) button icon in the toolbar is cropped. This issue is in server mode in Rocky 9 Firefox browser.

<img width="905" alt="Screenshot 2023-11-01 at 3 56 09 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/398bdff5-2518-45a9-a897-de23e50b9295">

**Comment by adityatoshniwal** [comment] 2023-11-01 14:57
> The All Rows (view/edit) button icon in the toolbar is cropped. This issue is in server mode in Rocky 9 Firefox browser.
> 
> <img alt="Screenshot 2023-11-01 at 3 56 09 PM" width="905" src="https://user-images.githubusercontent.com/111979571/279649408-398bdff5-2518-45a9-a897-de23e50b9295.png">

What is the firefox version? I cannot reproduce v110 on Mac.

**Comment by pravesh-sharma** [comment] 2023-11-01 15:07
> > The All Rows (view/edit) button icon in the toolbar is cropped. This issue is in server mode in Rocky 9 Firefox browser.
> > <img alt="Screenshot 2023-11-01 at 3 56 09 PM" width="905" src="https://user-images.githubusercontent.com/111979571/279649408-398bdff5-2518-45a9-a897-de23e50b9295.png">
> 
> @pravesh-sharma What is the firefox version? I cannot reproduce v110 on Mac.

Firefox version - 115.3.1esr (64-bit)
OS - Rocky Linux 9

**Comment by nikhil-mohite** [comment] 2023-11-02 07:02
> Hi @adityatoshniwal,
> 
> Found UI issues in Object Explorer,
> 
> 1. Add a new server and make sure it will get added to the end of the existing server. (last server)
>    This issues is reproducible on other nodes as well where added node is getting added as last node in existing nodes
> 
>  browser_explorer_add_issue.mov

Resolved, Working fine on the latest code

**Comment by nikhil-mohite** [comment] 2023-11-07 08:11
Issues found in testing:
1. The PSQL Tool icon is visible on the browser explorer menu bar in server mode even when `ENABLE_PSQL=False` is set
![image](https://github.com/pgadmin-org/pgadmin4/assets/69510038/ace5c55e-ac53-49cc-9f54-02e89e453be4)

In older versions, it is hidden if value is set to False
![image](https://github.com/pgadmin-org/pgadmin4/assets/69510038/1a108bcc-b468-4187-8872-a71654b33bd6)

**Comment by yogeshmahajan-1903** [comment] 2023-11-07 08:54
@adityatoshniwal 
1.Need to add top border for Dashboard Properties panel.Screenshot below is from windows

<img width="1790" alt="Screenshot 2023-11-07 at 2 19 12 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/4303ca3e-57b5-41a9-8760-9c8c2464f9c9">


2.Properties panel data is not updated on changing selected object.
 1.Detach the properties panel
 2.Select some db object and select dependent/dependency tab.
 3.Now change the db object.
 4.Check properties panel , data is not updated. It is blank.

**Comment by anilsahoo20** [comment] 2023-11-07 09:48
Issue:
When we create multiple database connections within a Query tool tab, the selected and active database connection is not same as the tab title been shown, the tab title shown is the other database connection that is idle.


Steps to reproduce the behavior:

1. Go to Query tool
2. Click on Connection Dropdown->New connection
3. Create a new connection
4. Check tab title by changing the connection
5. See the error

Expected behavior

In multiple database connections, the selected database connection and tab title should match.

![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/cf572d3c-0526-43ff-bf64-6aef1356525f)

**Comment by adityatoshniwal** [comment] 2023-11-07 10:07
As per @anilsahoo20 - ERD Tool Table Relationship Options giving Something went wrong error.

**Comment by yogeshmahajan-1903** [comment] 2023-11-07 11:35
@adityatoshniwal 
Object explorer is getting hinder we Amy want to increase little width.
<img width="563" alt="Screenshot 2023-11-07 at 5 04 20 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/f6b923db-e619-4a5b-9da0-4a6c02ec2f2f">

**Comment by adityatoshniwal** [comment] 2023-11-07 11:50
@yogeshmahajan-1903 the object explorer default width is set to make it clearly visible. Its 20:80 ratio.

**Comment by yogeshmahajan-1903** [comment] 2023-11-08 07:49
@adityatoshniwal 
No message is displayed in SQL/Dependent  etc tabs when no db object is selected.

<img width="1792" alt="Screenshot 2023-11-08 at 1 12 54 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/3143e7c3-5ce8-47f9-ab5f-7839997b8494">

**Comment by yogeshmahajan-1903** [comment] 2023-11-09 09:19
> @adityatoshniwal ,
> 
> 1.In dev env, with master password enabled, when I click on any server it asks Master password as expected, but background screen gets black. Master password popup is polluted 3 times. If I click on cancel in pop up, I need to click 3 times.
> 
> <img alt="Screenshot 2023-10-27 at 1 02 01 PM" width="1792" src="https://user-images.githubusercontent.com/16016019/278569729-f45ef32a-547b-4348-883e-aae5644b23a2.png">
> 2.Properties panel is empty for not-connected server. <img alt="Screenshot 2023-10-27 at 1 16 37 PM" width="1786" src="https://user-images.githubusercontent.com/16016019/278572942-3e79069b-e479-4eb6-b771-88d6d2ca37d9.png">

Both the issues are fixed.

**Comment by yogeshmahajan-1903** [comment] 2023-11-09 09:37
@adityatoshniwal 

1.Dashboards are not loaded on connecting server. User need to reselect the server.
1.Naviagate to Dashboard.
2.Go to the not connected server > Dashboard becomes blank -showing error connect to the DB object.
3.Now connect to server.
4.Dashboard shows still same error.
Issue not yet fixed.

2.Server activity table data is empty
<img width="1776" alt="Screenshot 2023-11-09 at 2 29 15 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/5c7a9267-5526-4f00-8096-4e37e87545ee">

**Comment by anilsahoo20** [comment] 2023-11-09 10:37
Issue:

1. If we open a file from ERD tool it shows untitled on the down arrow icon press.
2. If we open a file from Query tool it shows the Database connection title on the down arrow icon press.

Both the cases the file name is not showing on click down arrow for dropdown. 

Expected behaviour:
It should show the file name.

![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/f9ff4ac3-38a9-472e-a522-7440b9996e00)
![Image](https://github.com/pgadmin-org/pgadmin4/assets/122535205/9e394f7b-8cca-4a74-9e0e-a6e2a7226c6f)

**Comment by yogeshmahajan-1903** [comment] 2023-11-23 07:41
All reported issues are verified. and testing has been completed across different platforms.

**Closed by yogeshmahajan-1903** 2023-11-23 07:41 UTC
Labels: Housekeeping, EDB Sprint 156
