### ISSUE TITLE
Corrupted output of query result in pgadmin 8.11

### ISSUE THREAD

**Issue by kraynopp** [pgadmin-org/pgadmin4#7846] opened 2024-08-24 10:19 UTC
Output result of query is corrupted in Firefox 115.12esr. Previous version (8.10) works fine with this version of Firefox.
But pgadmin 8.11 works fine with Google Chrome (128.0.6613.84)

1. Start pgadmin
2. Start browser (Firefox 115.12)
3. Connect to database
4. Use query tool to launch select statement

**Expected behavior**

Output should be correct. Grid with header and rows.

**Error message**

No error messages, but in Firefox 115.12esr the output of query tool collapsed in grid with only one column.

**Comment by slewsys** [comment] 2024-08-25 08:15
Not able to reproduce this with current stable Firefox 129.0.2 (64-bit), which can be downloaded directly from [firefox.com](https://www.mozilla.org/en-US/firefox/all/#product-desktop-release).

**Comment by anilsahoo20** [comment] 2024-08-27 04:28
Hi @kraynopp,

Try updating the Firefox ESR to latest version. The issue is with the older Firefox ESR versions. And Firefox don't have the issue, also you can use Firefox.

The issue is not related to pgAdmin, hence closing the issue.

**Closed by anilsahoo20** 2024-08-27 04:28 UTC
Labels: Bug

**Comment by johanvdw** [comment] 2024-09-27 13:19
Just FYI, 115.15.0esr (64-bit) is the current version of Firefox in debian https://packages.debian.org/bookworm/firefox-esr

I think it is still actual.
