### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by PierceSDS** [pgadmin-org/pgadmin4#5816] opened 2023-02-02 14:56 UTC
Using version 6.19 on a local Windows 10 system connecting to a Heroku Postgres table. Drag and drop from the schema to the query window is not working for table names or column names. I believe this worked fine in the last version.

**Comment by slyapustin** [comment] 2023-02-02 19:56
Confirm, and that is quite a major issue for my use case.

**Comment by akshay-joshi** [comment] 2023-02-03 05:31
Duplicate of #5761

**Closed by akshay-joshi** 2023-02-03 05:31 UTC
