### ISSUE TITLE
Connection lost to pgadmin on Mac OS Sonoma 14.5

### ISSUE THREAD

**Issue by bjorngback** [pgadmin-org/pgadmin4#7850] opened 2024-08-25 18:41 UTC
When I leave pgadmin open without using it for 12-24 h and then go to run a query it says that it has lost connection to pgadmin. 

1. Run pgadmin on Mac OS Sonoma 14.5
2. Leave the app open without using it for 24 h
3. Try to run a query

I obviously expect no error message and that the query runs. Instead I get the error message "connection lost to pgadmin"

 - OS: Mac OS Sonoma 14.5
 - Version: 8.11
 - Mode: Desktop

This also happened on the previous version 8.10

**Comment by anilsahoo20** [comment] 2024-08-27 04:34
Duplicate of #6308.

**Closed by anilsahoo20** 2024-08-27 04:34 UTC
Labels: Bug
