### ISSUE TITLE
Replace NW.js with Electron

### ISSUE THREAD

**Issue by adityatoshniwal** [pgadmin-org/pgadmin4#7494] opened 2024-05-21 08:02 UTC

**Comment by adityatoshniwal** [comment] 2024-06-20 09:27
TODO: If possible, rebrand Electron Helper processes to pgAdmin.

**Comment by adityatoshniwal** [comment] 2024-06-20 12:34
On MacOS, `Preferences` will be automatically renamed to `Settings...`. Check - https://github.com/electron/electron/issues/42583

**Comment by akshay-joshi** [comment] 2024-07-03 07:45
Found a few issues during testing:

1. Preferences rename to Settings in OSX. On Windows it is Preferences.
2. Configure runtime and view log's inner container height should be corrected.
3. Open Query Tool in a new window, type some query and try to close this window. It asks for "Don't save" and "Save" click on any button, and the new window won't close at all. Reproduced only on Windows, OSX working fine.

**Comment by adityatoshniwal** [comment] 2024-07-03 08:02
@akshay-joshi for Preferences named as Settings please check my above comment - https://github.com/pgadmin-org/pgadmin4/issues/7494#issuecomment-2180560120

**Comment by akshay-joshi** [comment] 2024-07-03 08:27
But we should be consistent, is there any way to change it to Preferences?

**Comment by pravesh-sharma** [comment] 2024-07-04 04:51
Facing an issue with the file dialog. Below are steps to reproduce:

1. Open the backup/restore dialog and click on the file icon to open the file dialog
2. Input a file name and click on the save button.

Nothing happens

Expected behaviour:
The file name with the complete path should appear on input. Also, file extension is not present which was there earlier

https://github.com/pgadmin-org/pgadmin4/assets/111979571/31d53a30-e104-4bb8-abaf-df770f54cce1

**Comment by yogeshmahajan-1903** [comment] 2024-07-04 09:26
1.Try starting debugging for function from tools > Debugging option by selecting function. Seems to be error for the all callbacks functions.(From context menu works fine.)
<img width="1792" alt="Screenshot 2024-07-04 at 2 15 48 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/4da13275-1248-42f8-b724-7c0d95f86ecb">

2.Windows > zoom > minimises screen. Error in developer console.

<img width="1777" alt="Screenshot 2024-07-04 at 2 46 47 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/16016019/97d73f2f-9c7c-4ac1-96b5-0a6c8e89880e">

**Comment by pravesh-sharma** [comment] 2024-07-08 06:05
Menu options inside `Object -> Create` not working.

<img width="1580" alt="Screenshot 2024-07-08 at 11 33 38 AM" src="https://github.com/pgadmin-org/pgadmin4/assets/111979571/183600ff-4643-4d40-a79a-9f5b21c216c3">

**Comment by yogeshmahajan-1903** [comment] 2024-07-09 06:23
> 1.Try starting debugging for function from tools > Debugging option by selecting function. Seems to be error for the all callbacks functions.(From context menu works fine.) <img alt="Screenshot 2024-07-04 at 2 15 48 PM" width="1792" src="https://private-user-images.githubusercontent.com/16016019/345761307-4da13275-1248-42f8-b724-7c0d95f86ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDUwMTYsIm5iZiI6MTcyMDUwNDcxNiwicGF0aCI6Ii8xNjAxNjAxOS8zNDU3NjEzMDctNGRhMTMyNzUtMTI0OC00MmY4LWI3MjQtN2MwZDk1Zjg2ZWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA1NTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5YWNkNGRiNWVmNWNhMzU4ZGJlMWQ5YTUwZGU5MTVlNjdkOTBlZTQ2Yjk3MWM3NjlkMDcyZWRhYmMyMDg1YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-RIdWKq0PJQiNwomocAQ2Yv84tJ6RrP-9kE07-TwcGw">
> 
Works fine

> 2.Windows > zoom > minimises screen. Error in developer console.
> 
> <img alt="Screenshot 2024-07-04 at 2 46 47 PM" width="1777" src="https://private-user-images.githubusercontent.com/16016019/345772056-97d73f2f-9c7c-4ac1-96b5-0a6c8e89880e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDUwMTYsIm5iZiI6MTcyMDUwNDcxNiwicGF0aCI6Ii8xNjAxNjAxOS8zNDU3NzIwNTYtOTdkNzNmMmYtOWM3Yy00YWMxLTk2YjUtMGE2YzhlODk4ODBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA1NTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OTA3YjMyYWM5ZTQ4ZDAxMDVmOWQzM2E4MWMwNGVlMWE5NWFmZTk0MTQzOTEzNmZkNmNhMzZiYWZiZTQ2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xmK61kl3ILuiXcMvP5X46kppyKWnyRx0yg8PYmsmIls">

@adityatoshniwal This is not yet fixed

**Comment by adityatoshniwal** [comment] 2024-07-09 10:20
Hi @yogeshmahajan-1903,
Isn't this an expected behaviour? Why should pgAdmin close if it is confirming for closing query tool first? In fact, this is a missing feature I would say.

**Comment by yogeshmahajan-1903** [comment] 2024-07-09 10:34
> Hi @yogeshmahajan-1903, Isn't this an expected behaviour? Why should pgAdmin close if it is confirming for closing query tool first? In fact, this is a missing feature I would say.

Problem is that, pop up does not come on screen.it is stick to query tool tab only.

**Comment by adityatoshniwal** [comment] 2024-07-09 10:42
> > Hi @yogeshmahajan-1903, Isn't this an expected behaviour? Why should pgAdmin close if it is confirming for closing query tool first? In fact, this is a missing feature I would say.
> 
> Problem is that, pop up does not come on screen.it is stick to query tool tab only.

Each query tool will have its own pop-up, consider the case where there are multiple query tools open.

**Comment by yogeshmahajan-1903** [comment] 2024-07-10 07:21
1.Open query tool and click on close button for pgadmin. It closed query tool

**Comment by anilsahoo20** [comment] 2024-07-15 09:21
@adityatoshniwal When I try to close the ERD tool tab, it's not closing. Apart from that all other tool tabs and basic tabs gets closed on click of close icon of a tab.

**Comment by RohitBhati8269** [comment] 2024-07-15 10:18
ERD tool on Mac OS  (Server Mode):-
1. when we create a test object for ERD and then press the save button shortcut multiple times, it opens numerous save dialogs.
2. When I do that same thing for QueryToll, it first opens an application save dialog. Then if we again press (cmd + s), it opens a system save dialog on top of the application save dialog.

![Image](https://github.com/user-attachments/assets/ea8286d6-9266-411c-ab04-b22551fd9f86)

 the attached image.

**Comment by yogeshmahajan-1903** [comment] 2024-07-15 11:51
On windows, I could open 4 pgAdmin4 instances. by 4/5 times clicking icon. (Same case with Edge also). It's nice if we can prevent that.
<img width="1535" alt="Screenshot 2024-07-15 at 5 20 55 PM" src="https://github.com/user-attachments/assets/65a7e1d1-9c9c-49a9-b6e9-02475b8654c1">

**Comment by adityatoshniwal** [comment] 2024-07-17 06:30
@yogeshmahajan-1903 I searched for header sizing and found that it is bug in Electron on windows - https://github.com/electron/electron/issues/27651

**Comment by yogeshmahajan-1903** [comment] 2024-07-18 06:37
1.Addtional space in logs dialogue - 
<img width="1285" alt="Screenshot 2024-07-18 at 12 04 41 PM" src="https://github.com/user-attachments/assets/e6a89933-01a3-45ba-9aa0-6695da8f2cb9">
Same for configure runtime
<img width="780" alt="Screenshot 2024-07-18 at 12 06 26 PM" src="https://github.com/user-attachments/assets/be86e609-0f63-409a-a64c-6cbbf0313d5e">

2.

**Comment by adityatoshniwal** [comment] 2024-07-18 06:45
> 1.Addtional space in logs dialogue - 

if there is something more important then I will reduce the space along with that. For now, I will not add any commit for this.

**Comment by yogeshmahajan-1903** [comment] 2024-07-18 07:19
In full screen mode, menu bar disappears on Ubuntu - 
<img width="1550" alt="Screenshot 2024-07-18 at 12 45 19 PM" src="https://github.com/user-attachments/assets/15425cbf-15ff-4e58-a9c0-8e5430b6ab75">

**Comment by akshay-joshi** [comment] 2024-07-31 06:01
Tested on candidate build.

**Closed by akshay-joshi** 2024-07-31 06:01 UTC
Labels: Housekeeping, EDB Sprint 173

**Comment by mr-ryan-james** [comment] 2024-11-26 10:36
Thanks everyone for this update! I hadn't updated pgAdmin in almost a year and noticed it's a lot less clunky on my MacBook now. This change really made a difference! 😊
