### ISSUE TITLE
connect failed after upgrade from 6.x to 7.0

### ISSUE THREAD

**Issue by MarekUniq** [pgadmin-org/pgadmin4#6149] opened 2023-04-18 11:29 UTC
**Help -> About pgAdmin 4**
```
Version 7.0
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.72.0
Browser Chromium 109.0.5414.87
Operating System macOS-13.3.1-x86_64-i386-64bit

```
**The Error mesage:**
![image](https://user-images.githubusercontent.com/42849684/232759886-fbd2c1a1-8792-4dfd-8c77-713d58c70b9f.png)

**The "Connection" page:**
![image](https://user-images.githubusercontent.com/42849684/232760655-210afedf-81ae-4865-b2ad-76a7113551e5.png)

**Based on error message it looks like pgAdmin tries to connect to ipv6 address [::1]**

**But in the file:**
`.pg_service.conf
`
**There is service entry. Service entry explicitly states that host=localhost (and not ::1)**
```
[dev_***_service_db]
host=localhost
port=61011
```

**Comment by nikhil-mohite** [comment] 2023-04-21 11:09
We need to test this.

**Comment by andrey-helldar** [comment] 2023-04-21 12:56
I also faced this problem.

Tried to remove container and volume - can't connect.

**Comment by andrey-helldar** [comment] 2023-04-24 09:13
I found a solution: in the host name field, I used to enter "localhost" or "127.0.0.1". Now this causes an error, but if you enter the name of the service, then the connection works.

![image](https://user-images.githubusercontent.com/10347617/233953038-fede7900-ad6e-4d62-bcd4-1f226c3f4bea.png)

**Comment by yogeshmahajan-1903** [comment] 2023-04-24 13:47
> **Help -> About pgAdmin 4**
> 
> ```
> Version 7.0
> Application Mode Desktop
> Current User pgadmin4@pgadmin.org
> NW.js Version 0.72.0
> Browser Chromium 109.0.5414.87
> Operating System macOS-13.3.1-x86_64-i386-64bit
> ```
> 
> **The Error mesage:** ![image](https://user-images.githubusercontent.com/42849684/232759886-fbd2c1a1-8792-4dfd-8c77-713d58c70b9f.png)
> 
> **The "Connection" page:** ![image](https://user-images.githubusercontent.com/42849684/232760655-210afedf-81ae-4865-b2ad-76a7113551e5.png)
> 
> **Based on error message it looks like pgAdmin tries to connect to ipv6 address [::1]**
> 
> **But in the file:** `.pg_service.conf ` **There is service entry. Service entry explicitly states that host=localhost (and not ::1)**
> 
> ```
> [dev_***_service_db]
> host=localhost
> port=61011
> ```

@MarekUniq 
We are able to reproduce the same error only if we provide a port where service is NOT running.
Could you please confirm that your are able to connect to server using service with psql?

**Comment by khushboovashi** [comment] 2023-04-24 14:00
Hi @MarekUniq,

We couldn't reproduce this issue on our end. Does psql work with this service file?

**Comment by MarekUniq** [comment] 2023-04-24 19:06
I did test on `Windows 11 Pro` and got the following results.

**Help -> About pgAdmin 4**
```
Version 7.0
Application Mode Desktop
Current User pgadmin4@pgadmin.org
NW.js Version 0.72.0
Browser Chromium 109.0.5414.87
Operating System Windows-10-10.0.22000-SP0
```

**Test 1)**

With "Service" the connection fails with error message `"connection timeout expired"`.
(unfortunately, pgAdmin does not reveal the name of the host it is trying to connect to in the error message)

![image](https://user-images.githubusercontent.com/42849684/234088306-57731f8e-7b75-4769-b20f-e2c92209c9fa.png)

**Test 2)**

While specifying host/port directly (and not using "service") then pgAdmin asks for password (**which is wrong behavior**).
It should login transparently without asking password (because of single-sign on) as pgAdmin 6.x versions are doing.

![image](https://user-images.githubusercontent.com/42849684/234088547-87fdbfd1-1b1d-4590-89c7-b838b6c81d2e.png)

**Test 3)**

psql connection attempt works.
host/port/database name comes from file `.pg_service.conf`.
user comes from environment variable `PGUSER`.
there is no password

![image](https://user-images.githubusercontent.com/42849684/234090695-0ca95d50-e219-4906-9334-f4bece3443ac.png)

**Comment by akshay-joshi** [comment] 2023-04-25 12:17
Hi @MarekUniq 

I am not able to reproduce the issue. I have run the 2 tests on Windows 10:
I have set the **PGSERVICEFILE** and **PGUSER** in the environment variable
<img width="510" alt="Screenshot 2023-04-25 at 5 11 42 PM" src="https://user-images.githubusercontent.com/1632882/234270211-22c163ce-15fd-40df-bbfa-b21b4bd5ffaf.png">

**Test 1:** (Server connected no issues found)
- pg_service file contains host, port, and dbname. The database name is 'test_service'.
- pgpass file contains the entry for **test_service** database and **test_new** user.
- Set the maintenance database to 'test_service' in the server dialog and specify the service as pg15.

<img width="1239" alt="Screenshot 2023-04-25 at 5 13 25 PM" src="https://user-images.githubusercontent.com/1632882/234272022-9e4ef125-956c-4af5-aab4-9fc9719285ba.png">

**Test 2:** (Server connected after providing the password)
- pg_service file contains host, port, and dbname. The database name is 'test_service'.
- pgpass file contains the entry for **test_service** database and **test_new** user.
- Set the maintenance database to 'postgres' in the server dialog and specify the service as pg15.
<img width="1229" alt="Screenshot 2023-04-25 at 5 28 58 PM" src="https://user-images.githubusercontent.com/1632882/234272886-e7dfe7d1-8d32-4936-8d19-d4f5ec1d5097.png">

**Note:** Anything provided as part of the connection string will override the values of the service file. As per documentation "A service file setting overrides the corresponding environment variable, and in turn, can be overridden by a value given directly in the connection string"

**Comment by MarekUniq** [comment] 2023-04-25 14:41
@akshay-joshi Please take a look at the error message for "Test 2"
`connection failed::1), port 5433 failed ...`

I guess the `::1` is referring to ipv6 address. Can you confirm it?
And in your test case the "postgres" is listening on both addresses: 1) ipv4 127.0.0.1 and 2) ipv6 [::1] - Can you confirm it?

In my case the `localhost` resolves to ipv4 address `127.0.0.1`:
```
% nslookup localhost
...
Name:	localhost
Address: 127.0.0.1
```

The "postgres" is listening on ipv4: `127.0.0.1:61011`
**And nothing is listening on ipv6: `[::1]:61011`**

My best guess is that pgAdmin for some reason ignores that `localhost` resolves to `127.0.0.1`
and instead resolves to ipv6 [::1] for some reason (which is not nice. result of name resolution should be respected)

**Comment by khushboovashi** [comment] 2023-04-26 09:30
Looks like some issues with the psycopg-c implementation. Please see the discussion here at https://github.com/psycopg/psycopg/discussions/270. I have added my findings there.

**Comment by khushboovashi** [comment] 2023-04-26 09:31
@MarekUniq, as a workaround, please use an IP address (127.0.0.1) instead of a server name in the service file.

**Comment by MarekUniq** [comment] 2023-04-26 10:42
@khushboovashi `127.0.0.1` workaround works.

In our case the `.pg_service.conf` file is centrally managed and distributed to all Windows, Linux and Mac users. For some computers the `localhost` can resolve to ipv6 address `[::1]`. We don't want to break configuration for those users. We want to keep using dns/host-name `localhost` and not hard-code any ipv4 or ipv6 specific address.

**We keep using latest pgAdmin 6 for a while.** 

We have seen the `localhost` issue earlier. Very likely the root cause is inside underlying libraries or operating system api-s. I mean older and newer libraries/api-s does not resolve localhost consistently.
Sooner or later the root cause is identified and fixed OR older libraries are not in use anymore and `localhost` will be consistently resolved.

Any suggestions are welcome about how to make `localhost` name resolution consistent.

**Comment by MarekUniq** [comment] 2023-04-26 10:54
The following is a bit out-of-topic but very annoying.
Please look at the "Test 1" below (made @akshay-joshi).

On the "Connections" tab the "Maintenance database" is mandatory field.
Can you please make it **NOT MANDATORY**.

`dbname` comes from `.pg_service.conf` file. It is very annoying to duplicate the same data to "Connections" tab for each entry by each user.
.
.

> Hi @MarekUniq
> 
> I am not able to reproduce the issue. I have run the 2 tests on Windows 10: I have set the **PGSERVICEFILE** and **PGUSER** in the environment variable <img alt="Screenshot 2023-04-25 at 5 11 42 PM" width="510" src="https://user-images.githubusercontent.com/1632882/234270211-22c163ce-15fd-40df-bbfa-b21b4bd5ffaf.png">
> 
> **Test 1:** (Server connected no issues found)
> 
> * pg_service file contains host, port, and dbname. The database name is 'test_service'.
> * pgpass file contains the entry for **test_service** database and **test_new** user.
> * Set the maintenance database to 'test_service' in the server dialog and specify the service as pg15.
> 
> <img alt="Screenshot 2023-04-25 at 5 13 25 PM" width="1239" src="https://user-images.githubusercontent.com/1632882/234272022-9e4ef125-956c-4af5-aab4-9fc9719285ba.png">
>

**Comment by axelsean** [comment] 2023-10-10 17:08
> @khushboovashi `127.0.0.1` workaround works.
> 
> In our case the `.pg_service.conf` file is centrally managed and distributed to all Windows, Linux and Mac users. For some computers the `localhost` can resolve to ipv6 address `[::1]`. We don't want to break configuration for those users. We want to keep using dns/host-name `localhost` and not hard-code any ipv4 or ipv6 specific address.
> 
> **We keep using latest pgAdmin 6 for a while.**
> 
> We have seen the `localhost` issue earlier. Very likely the root cause is inside underlying libraries or operating system api-s. I mean older and newer libraries/api-s does not resolve localhost consistently. Sooner or later the root cause is identified and fixed OR older libraries are not in use anymore and `localhost` will be consistently resolved.
> 
> Any suggestions are welcome about how to make `localhost` name resolution consistent.

This worked for me on MacOS

Thx

**Comment by khushboovashi** [comment] 2024-05-17 11:22
There is no fix for this issue, upstream ref: https://github.com/psycopg/psycopg/issues/519.

**Closed by khushboovashi** 2024-05-17 11:22 UTC
Labels: Bug
