### ISSUE TITLE
Ubuntu keys

### ISSUE THREAD

**Issue by thk686** [pgadmin-org/pgadmin4#5341] opened 2022-09-18 19:36 UTC
From the apt-key man page:
```
       Except for using apt-key del in maintainer scripts, the use of apt-key is deprecated. This section shows how to replace existing use of
       apt-key.

       If your existing use of apt-key add looks like this:

       wget -qO- https://myrepo.example/myrepo.asc | sudo apt-key add -

       Then you can directly replace this with (though note the recommendation below):

       wget -qO- https://myrepo.example/myrepo.asc | sudo tee /etc/apt/trusted.gpg.d/myrepo.asc

       Make sure to use the "asc" extension for ASCII armored keys and the "gpg" extension for the binary OpenPGP format (also known as "GPG key
       public ring"). The binary OpenPGP format works for all apt versions, while the ASCII armored format works for apt version >= 1.4.
```
Is there an ASCII armored key and where is it? If not, can one be generated? Thanks.

**Comment by yogeshmahajan-1903** [comment] 2022-09-29 09:04
Duplicate of #5290

**Closed by yogeshmahajan-1903** 2022-09-29 09:04 UTC
Labels: Bug, EDB Sprint 127
