### ISSUE TITLE
Using arrows to minimize server groups results in blank server browser

### ISSUE THREAD

**Issue by freightverifianbrian** [pgadmin-org/pgadmin4#5771] opened 2023-01-23 22:18 UTC
When I use my keyboard arrow keys to minimize/collapse my list of servers in my server browser it will (virtually every single time) blank out my server browser menu.  I therefore can not view servers, server groups, connect to servers, etc.

This has happened a number of times in past, seemingly for no reason, or I would re-size the browser side bar and it would go blank, however this latest occurrence is reproducible any time.

This has been happening for multiple versions of PgAdmin, I am finally taking the time to submit the bug however if you go back two or even three versions you will still see the problem.

This is very frustrating because I then have to either reset my layout, or close PgAdmin and re-open it.  The fact that PgAdmin doesn't save work in open tabs adds to the frustration as I either have to copy/paste my queries into Notepad++ before rebooting the app, or I have to save all of my tabs and remember which ones I had opened last.

Steps to reproduce

1. Open PgAdmin
2. Expand at least one or more server groups
3. Connect to servers from each group
4. Expand one of the servers down to the database>>schema>>table level
5. While having the table (or it's indexes etc.) selected, quickly keep pressing the left arrow key on your keyboard to minimize the tables, schema, database, server, server group
6. At this point the whole server browser screen should go blank.

Version : 6.19
Application Mode : Desktop
Current User : pgadmin4@pgadmin.org
NW.js Version : 0.72.0
Browser : Chromium 109.0.5414.87
Operating System : Windows-10-10.0.22621-SP0

**Comment by casparsch** [comment] 2024-04-26 14:24
After resolving this issue I'm willing to test #7025 
Looks similar (?same technical flaw?) but it has different reproduction-path.

**Comment by adityatoshniwal** [comment] 2024-04-27 05:21
> After resolving this issue I'm willing to test #7025 Looks similar (?same technical flaw?) but it has different reproduction-path.

@casparsch At least this path is reproducible, but #7025 is not even reproducible.

**Comment by pravesh-sharma** [comment] 2024-05-27 13:03
The issue is with the underlying react-aspen library and is unlikely to be fixed as they are currently focusing on aspen2. We have to wait for the new version.

**Comment by japaroooo** [comment] 2024-06-05 03:01
Also encounter this problem with the following log...

--------------[UI error]---------------
TypeError: Cannot read properties of undefined (reading 'constructor')
    at d.getItemAtIndex (http://127.0.0.1:50218/static/js/generated/vendor.others.js?ver=80600:312:1428092)
    at getItemKey (http://127.0.0.1:50218/static/js/generated/vendor.others.js?ver=80600:312:1428543)
    at w.render (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:276166)
    at Ul (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:113101)
    at Gl (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:112901)
    at Ka (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:153516)
    at Pu (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:139807)
    at Iu (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:139735)
    at _u (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:139598)
    at bu (http://127.0.0.1:50218/static/js/generated/vendor.react.js?ver=80600:2:136595)
------------[UI End]----------------

**Comment by pravesh-sharma** [comment] 2024-09-26 09:55
Hi @freightverifianbrian,

Could you please try using the latest version of pgAdmin 4 and check if the issue is still reproducible? You can download the latest version from [here](https://www.pgadmin.org/download/).

**Comment by freightverifianbrian** [comment] 2024-09-27 15:25
> Hi @freightverifianbrian,
> 
> Could you please try using the latest version of pgAdmin 4 and check if the issue is still reproducible? You can download the latest version from [here](https://www.pgadmin.org/download/).

I just ran a few tests and it appears to be working just fine now, thank you @pravesh-sharma !

**Closed** 2024-09-27 15:25 UTC
Labels: Bug
