### ISSUE TITLE
Query Tool not considering the complete row output when it contains ^I (tab) character after a newline

### ISSUE THREAD

**Issue by eduardoalvarenga** [pgadmin-org/pgadmin4#6521] opened 2023-07-01 13:42 UTC
**Describe the bug**

PgAdmin 7.4

If the output row contains ^I (tab) character after a newline (usually in XML data), the UI does not show any data after that.

**Regular psql or any other SQL tools works normally.**

**To Reproduce**

Steps to reproduce the behaviour:
1. Add a text to a row that contains the ^I (tab) character after a $ (newline) character
2. Query that row

**Expected behaviour**

The Query Tool should present that information property in the results

**Note 1:** Copying the results from the Query tool produces the correct output
**Note 2:** Exporting from the Query tool as CSV produces full line breaks which may fail to be imported

**Error message**

No error message

**Screenshots**

Sample expected output (from Copying the results to the clipboard, pasting and showing all chars via "cat -A")
```
"environment_id"^I"name"^I"description"^I"xml_definition_data"^I"triggers_xml_data"^I"configuration_state"^I"package_definition_id"^I"requirement_set"^I"notification_set"^I"list_position"$
19136514^I"Production 3"^I^I"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""no""?>$
<configuration xml:space=""preserve""><taskDefinition><id>1</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:cleanWorkingDirectoryTask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649988</oid></taskDefinition><taskDefinition><id>2</id><userDescription>Download release contents</userDescription><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:artifactdownloadertask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649989</oid><config><item><key>sourcePlanKey</key><value>ABC-CON</value></item><item><key>artifactId_0</key><value>-1</value></item><item><key>localPath_0</key><value/></item></config></taskDefinition><taskDefinition><id>3</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.scripttask:task.builder.script</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649990</oid><config><item><key>argument</key><value/></item><item><key>scriptLocation</key><value>INLINE</value></item><item><key>environmentVariables</key><value/></item><item><key>scriptBody</key><value>echo hello world</value></item><item><key>interpreter</key><value>RUN_AS_EXECUTABLE</value></item><item><key>script</key><value/></item><item><key>workingSubDirectory</key><value/></item></config></taskDefinition><bambooDelimiterParsingDisabled>true</bambooDelimiterParsingDisabled></configuration>$
"^I"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""no""?>$
<configuration xml:space=""preserve""><triggers><defined>true</defined><triggerDefinition><id>1</id><name>After successful deployment</name><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.triggers.atlassian-bamboo-triggers:afterSuccessfulDeployment</pluginKey><triggeringRepositories/><config><item><key>deployment.trigger.afterSuccessfulDeployment.triggeringEnvironmentId</key><value>19136513</value></item></config></triggerDefinition><triggerDefinition><id>2</id><name>After successful deployment</name><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.triggers.atlassian-bamboo-triggers:afterSuccessfulDeployment</pluginKey><triggeringRepositories/><config><item><key>deployment.trigger.afterSuccessfulDeployment.triggeringEnvironmentId</key><value>19136513</value></item></config></triggerDefinition><triggerDefinition><id>3</id><name>After successful deployment</name><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.triggers.atlassian-bamboo-triggers:afterSuccessfulDeployment</pluginKey><triggeringRepositories/><config><item><key>deployment.trigger.afterSuccessfulDeployment.triggeringEnvironmentId</key><value>19136513</value></item></config></triggerDefinition></triggers><bambooDelimiterParsingDisabled>true</bambooDelimiterParsingDisabled></configuration>$
"^I"TASKED"^I9076737^I19169282^I19202050^I2$
```
Sample presented output (broken):
```
"environment_id"^I"name"^I"description"^I"xml_definition_data"^I"triggers_xml_data"^I"configuration_state"^I"package_definition_id"^I"requirement_set"^I"notification_set"^I"list_position"$
19136514^I"Production 3"^I^I"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""no""?>$
<configuration xml:space=""preserve""><taskDefinition><id>1</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:cleanWorkingDirectoryTask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649988</oid></taskDefinition><taskDefinition><id>2</id><userDescription>Download release contents</userDescription><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:artifactdownloadertask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649989</oid><config><item><key>sourcePlanKey</key><value>ABC-CON</value></item><item><key>artifactId_0</key><value>-1</value></item><item><key>localPath_0</key><value/></item></config></taskDefinition><taskDefinition><id>3</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.scripttask:task.builder.script</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649990</oid><config><item><key>argument</key><value/></item><item><key>scriptLocation</key><value>INLINE</value></item><item><key>environmentVariables</key><value/></item><item><key>scriptBody</key><value>echo hello world</value></item><item><key>interpreter</key><value>RUN_AS_EXECUTABLE</value></item><item><key>script</key><value/></item><item><key>workingSubDirectory</key><value/></item></config></taskDefinition><bambooDelimiterParsingDisabled>true</bambooDelimiterParsingDisabled></configuration>$
```

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: [13.4.1 (22F82)]

**Comment by khushboovashi** [comment] 2023-07-06 05:21
Hi @eduardoalvarenga,

I couldn't reproduce this issue on the 7.4 release. Can you please send the screenshot?

**Comment by eduardoalvarenga** [comment] 2023-07-06 06:09
From PgAdmin:

![image](https://github.com/pgadmin-org/pgadmin4/assets/19997826/ab1c04b9-4d1c-4a96-9983-db84e3af4f24)

```
<configurationxml:space=preserve><taskDefinition><id>1</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:cleanWorkingDirectoryTask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649988</oid></taskDefinition><taskDefinition><id>2</id><userDescription>Downloadreleasecontents</userDescription><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:artifactdownloadertask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649989</oid><config><item><key>sourcePlanKey</key><value>ABC-CON</value></item><item><key>artifactId_0</key><value>-1</value></item><item><key>localPath_0</key><value/></item></config></taskDefinition><taskDefinition><id>3</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.scripttask:task.builder.script</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649990</oid><config><item><key>argument</key><value/></item><item><key>scriptLocation</key><value>INLINE</value></item><item><key>environmentVariables</key><value/></item><item><key>scriptBody</key><value>echohelloworld</value></item><item><key>interpreter</key><value>RUN_AS_EXECUTABLE</value></item><item><key>script</key><value/></item><item><key>workingSubDirectory</key><value/></item></config></taskDefinition><bambooDelimiterParsingDisabled>true</bambooDelimiterParsingDisabled></configuration>+
```

From psql (notice an extra <configurationxml:space=preserve> property and additional data)

![image](https://github.com/pgadmin-org/pgadmin4/assets/19997826/7dd21a20-97d8-4b2b-a900-6a58a0ba1dac)

```
<configurationxml:space=preserve><taskDefinition><id>1</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:cleanWorkingDirectoryTask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649988</oid></taskDefinition><taskDefinition><id>2</id><userDescription>Downloadreleasecontents</userDescription><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.bamboo-artifact-downloader-plugin:artifactdownloadertask</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649989</oid><config><item><key>sourcePlanKey</key><value>ABC-CON</value></item><item><key>artifactId_0</key><value>-1</value></item><item><key>localPath_0</key><value/></item></config></taskDefinition><taskDefinition><id>3</id><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.plugins.scripttask:task.builder.script</pluginKey><finalising>false</finalising><rootDirectoryType>DEFAULT</rootDirectoryType><repositoryDefiningWorkingDir>-1</repositoryDefiningWorkingDir><oid>2847260126916649990</oid><config><item><key>argument</key><value/></item><item><key>scriptLocation</key><value>INLINE</value></item><item><key>environmentVariables</key><value/></item><item><key>scriptBody</key><value>echohelloworld</value></item><item><key>interpreter</key><value>RUN_AS_EXECUTABLE</value></item><item><key>script</key><value/></item><item><key>workingSubDirectory</key><value/></item></config></taskDefinition><bambooDelimiterParsingDisabled>true</bambooDelimiterParsingDisabled></configuration>+|<configurationxml:space=preserve><triggers><defined>true</defined><triggerDefinition><id>1</id><name>Aftersuccessfuldeployment</name><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.triggers.atlassian-bamboo-triggers:afterSuccessfulDeployment</pluginKey><triggeringRepositories/><config><item><key>deployment.trigger.afterSuccessfulDeployment.triggeringEnvironmentId</key><value>19136513</value></item></config></triggerDefinition><triggerDefinition><id>2</id><name>Aftersuccessfuldeployment</name><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.triggers.atlassian-bamboo-triggers:afterSuccessfulDeployment</pluginKey><triggeringRepositories/><config><item><key>deployment.trigger.afterSuccessfulDeployment.triggeringEnvironmentId</key><value>19136513</value></item></config></triggerDefinition><triggerDefinition><id>3</id><name>Aftersuccessfuldeployment</name><userDescription/><isEnabled>true</isEnabled><pluginKey>com.atlassian.bamboo.triggers.atlassian-bamboo-triggers:afterSuccessfulDeployment</pluginKey><triggeringRepositories/><config><item><key>deployment.trigger.afterSuccessfulDeployment.triggeringEnvironmentId</key><value>9306113</value></item></config></triggerDefinition></triggers><bambooDelimiterParsingDisabled>true</bambooDelimiterParsingDisabled></configuration>+
```

I've noticed that psql would also report the same output as pgAdmin when selecting specific columns. When running a "SELECT *", I can then see the full contents.

So I guess it can be a major issue with the general PostgreSQL client.

**Comment by khushboovashi** [comment] 2023-07-10 06:24
@eduardoalvarenga, if it is reproducible in PSQL too, should we close this issue?

**Closed** 2023-07-14 11:14 UTC
Labels: Bug
