### ISSUE TITLE
Unable to backup pgsql-16 DB (Latest Docker 7.7)

### ISSUE THREAD

**Issue by emmanuelpare** [pgadmin-org/pgadmin4#6790] opened 2023-09-25 12:26 UTC
Using the latest docker images I could not backup my pgsql-16 DB,  Look like some shared library are missing.

/usr/local/pgsql-16/pg_dump --file "/var/lib/pgadmin/storage/adm-gcbrieau_gcbrieau.com/ddfasd" --host "postgres" --port "5432" --username "gcbdashboard" --no-password --format=c --large-objects --verbose "dashboard"

Error loading shared library libzstd.so.1: No such file or directory (needed by /usr/local/pgsql-16/pg_dump)
Error loading shared library liblz4.so.1: No such file or directory (needed by /usr/local/pgsql-16/pg_dump)
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_compressUpdate: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_CCtx_setParameter: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_compressBegin: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_CStreamOutSize: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_createDecompressionContext: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_freeDecompressionContext: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_freeCStream: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_DStreamOutSize: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_maxCLevel: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_DStreamInSize: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_createDStream: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_minCLevel: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_compressBound: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_decompressStream: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_isError: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_decompress: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_getErrorName: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_compressEnd: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_createCStream: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_isError: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_freeDStream: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_getErrorName: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_createCompressionContext: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: LZ4F_freeCompressionContext: symbol not found
Error relocating /usr/local/pgsql-16/pg_dump: ZSTD_compressStream2: symbol not found
Failed (exit code: 127).
Execution time: 0 se

**Comment by Astropilot** [comment] 2023-09-25 14:04
I also confirm the problem (tested on the snapshot tag), installing the missing dependencies into the container solves the problem:
```shell
$ apk add zstd-libs lz4-libs
```

Otherwise I don't know if it is a good idea but the dependencies could be fetch from the pg16 image along with copying libpq (untested):
https://github.com/pgadmin-org/pgadmin4/blob/5a26cad588260b8abeaa56a83b8fd17a0abbc6a6/Dockerfile#L168-L170

```diff
COPY --from=pg16-builder /usr/local/lib/libpq.so.5.16 /usr/lib/
+ COPY --from=pg16-builder /usr/lib/libzstd.so.1.5.5 /usr/lib/
+ COPY --from=pg16-builder /usr/lib/liblz4.so.1.9.4 /usr/lib/
RUN ln -s libpq.so.5.16 /usr/lib/libpq.so.5 && \ 
     ln -s libpq.so.5.16 /usr/lib/libpq.so
+ RUN ln -s libzstd.so.1.5.5 /usr/lib/libzstd.so.1
+ RUN ln -s liblz4.so.1.9.4 /usr/lib/liblz4.so.1
```

**Comment by akshay-joshi** [comment] 2023-09-26 08:10
@emmanuelpare and @Astropilot 

This seems to be an issue with PostgreSQL's docker image. We have fixed one issue where binaries for PG16 (/usr/local/pgsql-16) are not getting copied to the docker container. 

I have tried the following:
<img width="1348" alt="Screenshot 2023-09-26 at 1 35 46 PM" src="https://github.com/pgadmin-org/pgadmin4/assets/1632882/f6164c42-5db4-4e81-b97c-091383c6c484">

**Comment by Astropilot** [comment] 2023-09-26 15:05
Hi @akshay-joshi , I think it is not a problem with the postgres docker image, after some investigating, it seems that with PG16 they added support for LZ4 and Zstandard compression to `pg_dump` and `pg_restore` binaries:
https://www.postgresql.org/docs/16/release-16.html#RELEASE-16-PGDUMP
> Add LZ4 and Zstandard compression to pg_dump (Georgios Kokolatos, Justin Pryzby)

Which explains why these two binaries now require the associated dynamic libraries (`libzstd` and `liblz4`). These libraries are indeed present in the postgres image, but are not present in the alpine image (last layer) created for pgadmin as you are directly copying the compiled binaries.

So I think my first message is still valid, either adding in the last layer of the pgadmin image the dependencies via apk:
`$ apk add zstd-libs lz4-libs`
Or copying the two libraries from the `postgres:16-alpine` directly to use the exact same version. (still wondering if it is preferred to the previous solution)

Kind regards,

**Comment by akshay-joshi** [comment] 2023-09-27 08:09
I have opened the issue [Docker Issue](https://github.com/docker-library/postgres/issues/1130). Waiting for the response.

**Comment by emmanuelpare** [comment] 2023-09-27 19:41
Solution provided by @Astropilot is correct and its doesnt need a fix from the Postgresql  docker teams... it just a matter to add the missing librairy to the pgadmin image

**Comment by akshay-joshi** [comment] 2023-09-28 06:56
All,

Yesterday we committed the suggested fix. Can someone please check if it is working fine?

**Comment by Astropilot** [comment] 2023-09-28 07:52
Hi @akshay-joshi ,

I just tested on the `snapshop` tag of the pgadmin4 (image generated Sep 28, 2023 at 3:30 am) and it is working well :)
![image](https://github.com/pgadmin-org/pgadmin4/assets/11898378/de215419-d400-4bc0-8e23-b9ff98afba57)
![image](https://github.com/pgadmin-org/pgadmin4/assets/11898378/a6ba083a-39d9-41cc-80dd-8833cb1b436b)

Kind regards,

**Comment by akshay-joshi** [comment] 2023-09-28 07:57
@Astropilot 

Thanks a lot.

**Comment by akshay-joshi** [comment] 2023-09-29 06:40
Closing the issue as one of the authors confirms it is working.

**Closed by akshay-joshi** 2023-09-29 06:40 UTC
Labels: Bug, EDB Sprint 152

**Comment by gioscarda** [comment] 2025-07-11 08:49
Hi @akshay-joshi and @Astropilot,

I'm facing the same problem with the new latest version `sha256:2a830466aafd9cbc2aea0f76ff81a80dbbba819f2f5db7e69cb40e9cbdb6bc7b`

are there any regressions?

I'm using this PostgreSQL docker image `postgis/postgis:17-3.5`.

**Comment by Astropilot** [comment] 2025-07-11 09:01
> Hi [@akshay-joshi](https://github.com/akshay-joshi) and [@Astropilot](https://github.com/Astropilot),
> 
> I'm facing the same problem with the new latest version `sha256:2a830466aafd9cbc2aea0f76ff81a80dbbba819f2f5db7e69cb40e9cbdb6bc7b`
> 
> are there any regressions?
> 
> I'm using this PostgreSQL docker image `postgis/postgis:17-3.5`.

Hi @gioscarda , this is followed in this issue: https://github.com/pgadmin-org/pgadmin4/issues/8914
This is a bug introduced in the 9.5.0 (latest) version, either downgrade or use the `snapshot` tag where the fix is present while waiting for the next release.
