### ISSUE TITLE
pgadmin not launching macOS Monterey 12.6 M2 Chip

### ISSUE THREAD

**Issue by Waliddxb** [pgadmin-org/pgadmin4#5400] opened 2022-10-05 10:22 UTC
Greeting

recently I have purchased new MacBook Pro M2 Chip , macOS Monterey 12.6 .
downloaded pgadmin

I have installed successfully, when I try to launch pgadmin 4 I get below
error :-
the application cannot be opened for an unexpected reason , error=Error
Domain=NSOSStatusErrorDomain Code=-10669 "(Null") userinfo=
_LSLine=3863,_LSFunction=_LSopenStuffCallLocal (1)

I have formatted my Mac reinstalled  still getting same issue , I
have tried to search online for the above message and solution couldn't
find

I'm using Postgres on my other MacBook Pro Intel Chip with same macOS
Monterey 12.6 with no issues its working fine.

since 1 week I'm trying with no luck

appreciate your support please
thanks

**Comment by FaharAbbasRizvi** [comment] 2022-10-06 06:08
@Waliddxb 

I am not able to reproduce the issue on the fresh VM of macOS Monterey 12
<img width="1789" alt="Screen Shot 2022-10-06 at 11 01 27 AM" src="https://user-images.githubusercontent.com/43006122/194226287-4b4ed411-39d0-460f-8790-beb060b90861.png">

Can you please elaborate issue with more details, What is the difference between both machines, Is there any domain running on your machine where you are facing the problem?

**Comment by dpage** [comment] 2022-10-06 07:26
@FaharAbbasRizvi was that on M2? I thought (and you screenshot implies the same - though I’m not entirely sure how the OS is reported under Rosetta) you had an Intel Mac.

**Comment by Waliddxb** [comment] 2022-10-06 19:08
good day

first of all thank you for your reply and support
the difference between both MAC is the chipset/ processor  , the one which pgadmin is working with Intel processor 
and the one which pgadmin was giving me error is M2 processor  chip

no domain is running 

however just few minutes back I manage to solve the issue by running below command on on my MAC M2 chip terminal :- 

usr/sbin/softwareupdate --install-rosetta --agree-to-license
softwareupdate --install-rosetta 

now the pgadmin start working 

wanted to share above command 
thanks
regards

**Comment by adityatoshniwal** [comment] 2022-10-07 11:18
Closing as per user confirmation.

**Closed by adityatoshniwal** 2022-10-07 11:18 UTC

**Comment by DavidGRamiro** [comment] 2024-10-23 15:53
Thanks a lot! The same issue happens in Macbook Pro M3

**Comment by yogeshmahajan-1903** [comment] 2024-10-24 05:32
@DavidGRamiro 
Can you please provide OS details? And error screenshot?
