### ISSUE TITLE
Dashboard State panel show wrong details when inspecting a Session

### ISSUE THREAD

**Issue by antoniocaia** [pgadmin-org/pgadmin4#7936] opened 2024-09-16 15:37 UTC
**Describe the bug**

When inspecting details of a Session from the Dashboard | State panel pgadmin always show the details of the first session inspected. 

**To Reproduce**

1. Open State panel under Dashboard section
2. Click to inspect the details of a Session (the ">" button)
3. Inspect another Session, different from the previous one. The new Session show exactly the same details of the first one.  

**Expected behavior**

When performing step 3, pgadmin should shows the details of the currently inspected Session, not the previous one. 

**Error message**

No error message

**Screenshots**

No Screenshots

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.5 LTS
 - Version: 8.11
 - Mode: Desktop
 - Package type: DEB

**Comment by anilsahoo20** [comment] 2024-09-17 04:14
Duplicate of #7895

**Closed by anilsahoo20** 2024-09-17 04:14 UTC
Labels: Bug
