### ISSUE TITLE
Browser tree refreshes on editing DB node property

### ISSUE THREAD

**Issue by yogeshmahajan-1903** [pgadmin-org/pgadmin4#5426] opened 2022-10-12 06:06 UTC

**Comment by nl-savills-insightdata** [comment] 2023-04-01 09:50
@akshay-joshi 
In the next version of pgAdmin, it would be great if some attention could be given to the browser tree. Currently, there are still some issues with it (at bottom of this message), and certain behaviors could be improved to enhance user-friendliness. For instance, it would be beneficial if changes made to a browser tree node, such as renaming it, would not result in an error message when attempting to perform an action on the node, like accessing its properties. Currently, this error occurs, and to proceed, the parent node needs to be refreshed first. It can be really frustrating for DBA's who run into this all day.

Some other examples of feature requests which would also enhance user experience:
#5305 
#1714

Some examples of outstanding issues with the browser tree:
#5559 
#5306

**Comment by anilsahoo20** [comment] 2023-06-01 12:47
Closing it, as it is the duplicate of #6136.

**Closed by anilsahoo20** 2023-06-01 12:47 UTC
Labels: Bug, EDB Sprint 143
