### ISSUE TITLE
Annoying UI inconsistency that requires several extra clicks to work around

### ISSUE THREAD

**Issue by usernamesareaholdoverfromthe90s** [pgadmin-org/pgadmin4#8278] opened 2024-12-18 15:56 UTC
**Describe the bug**

When you lose a connection to the database, and then try to edit the "Sort/Filter" settings, you can't make the change, and have to exit the "Sort/Filter" dialog, re-run the old query, before you can re-edit the "Sort/Filter" settings

**To Reproduce**
This requires that you have database connections that are lost after a while.

1. Right-click on any table, and click "View/Edit Data" | "Filtered Rows..."
2. Type in some valid clause, and click "OK"
3. Wait until your database connection is (probably) lost
4. Click on "Sort/Filter" icon
5. Change the clause or add a sort criterion
6. Click on "Save"
7. BUG: Nothing happens

Of course, if you look carefully, it turns out that the Save button is (subtly) disabled, which explains why clicking OK does nothing.

You may also note that at the bottom of the "Sort/Filter" dialog, there's red text that says "connection to the database has been lost" which is a non-intuitive clue as to why the Save button might be disabled.

But, what do you do now?  How can you proceed?

You can't.

The only thing you can do is click on "Close", press on the "Execute Script" icon, which brings up the "Connection Warning: Cancel/Continue" message box, click "Continue", wait for the query to run, THEN click on the "Sort/Filter" icon, and make your edits all over again.

**Expected behavior**

I would expect the same "Connection Warning: Cancel/Continue" message box that you get if you had clicked on "Execute Script" icon would appear when I click on the "Sort/Filter" icon.  I.e., show me the warning **BEFORE** the "Sort/Filter" dialog opens, and if I click "Continue", THEN show the "Sort/Filter" dialog.

Alternatively, enable the "Save" button even though the connection was lost, and then show me the "Connection Warning: Cancel/Continue" message box when I click "Save".   <-- actually, this is probably the better option, because it handles the case in which I clicked "Sort/Filter" icon when I DID have a connection to the database, but then I got distracted and I didn't get around to clicking Save until after the connection was lost.

But either way, don't make me waste time making a bunch of edits that I'm just going to have to abandon due to the fact that my only option is to click "Close" when the connection was lost (which I had know way of knowing before I clicked "Sort/Filter").

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 8.14

**Comment by anilsahoo20** [comment] 2024-12-27 08:58
Hi @usernamesareaholdoverfromthe90s 

I am not able to reproduce the issue. Can you share the screen recording of the same.

**Comment by anilsahoo20** [comment] 2024-12-31 07:07
Duplicate of #6044.

**Closed by anilsahoo20** 2024-12-31 07:07 UTC
Labels: Bug, EDB Sprint 183
