### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by Whippet0** [pgadmin-org/pgadmin4#7433] opened 2024-04-26 07:24 UTC
![image](https://github.com/pgadmin-org/pgadmin4/assets/46486374/d9bf2fd2-e331-4cfd-b1ec-21542d5d7e14)

**Comment by akshay-joshi** [comment] 2024-04-26 10:37
Duplicate of #7429

**Closed by akshay-joshi** 2024-04-26 10:37 UTC
