### ISSUE TITLE
Import csv file from Storage manager: Error expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by robozor** [pgadmin-org/pgadmin4#6941] opened 2023-11-07 08:28 UTC
Official Docker container Pgadmin ver 7.7 (from dpage/pgadmin4:7.7)
Official Docker container Postgresql (from postgres:14.8 image)
Import fom csv:
![obrazek](https://github.com/pgadmin-org/pgadmin4/assets/7280092/5c4d6cdc-60e7-49e3-8b3b-bb795f8408d8)

![obrazek](https://github.com/pgadmin-org/pgadmin4/assets/7280092/87d3ccf3-da32-4d13-b1b7-7c593ce946d9)

Error log:

2023/11/07 09:10:10 | stdout | ::ffff:172.26.0.1 - - [07/Nov/2023:08:10:10 +0000] "POST /import_export/job/1 HTTP/1.1" 400 118 "http://192.168.0.151:6210/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"
-- | -- | --
2023/11/07 09:10:10 | stderr | TypeError: expected str, bytes or os.PathLike object, not NoneType
2023/11/07 09:10:10 | stderr | File "<frozen os>", line 812, in fsencode
2023/11/07 09:10:10 | stderr | ^^^^^^^^^^^^^^
2023/11/07 09:10:10 | stderr | env_list.append(k + b'=' + os.fsencode(v))
2023/11/07 09:10:10 | stderr | File "/usr/lib/python3.11/subprocess.py", line 1870, in _execute_child
2023/11/07 09:10:10 | stderr | self._execute_child(args, executable, preexec_fn, close_fds,
2023/11/07 09:10:10 | stderr | File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
2023/11/07 09:10:10 | stderr | ^^^^^^
2023/11/07 09:10:10 | stderr | p = Popen(
2023/11/07 09:10:10 | stderr | File "/pgadmin4/pgadmin/misc/bgprocess/processes.py", line 345, in start
2023/11/07 09:10:10 | stderr | p.start()
2023/11/07 09:10:10 | stderr | File "/pgadmin4/pgadmin/tools/import_export/__init__.py", line 349, in create_import_export_job
2023/11/07 09:10:10 | stderr | Traceback (most recent call last):
2023/11/07 09:10:10 | stderr | 2023-11-07 08:10:10,066: ERROR	pgadmin:	expected str, bytes or os.PathLike object, not NoneType
2023/11/07 09:10:09 | stdout | ::ffff:172.26.0.1 - - [07/Nov/2023:08:10:09 +0000] "POST /import_export/job/1 HTTP/1.1" 400 118 "http://192.168.0.151:6210/browser/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/119.0"

**Comment by yogeshmahajan-1903** [comment] 2023-11-07 12:43
@robozor 
Are you using pgpass file in server configuration?
Can you please try with today's snapshot? Duplicate of #6820

**Comment by robozor** [comment] 2023-11-08 08:15
>Are you using pgpass file in server configuration? 
NO
>Can you please try with today's snapshot?
Super!!! Doker image dpage/pgadmin4:snapshot working! :-)

**Closed** 2023-11-08 09:11 UTC
Labels: Bug
