### ISSUE TITLE
pgAdmin4 14: browser-panel not adjusting after windowsize changed

### ISSUE THREAD

**Issue by harpogo** [pgadmin-org/pgadmin4#5442] opened 2022-10-17 18:26 UTC
When resizing the pgAdmin4 14-window, the veritcal extent of the browser-panel(db-tree) stays the same and won't fit the new windowsize. So if the window got larger, there will be "unused" space below the browser-panel, if the window got smaller, the browser-panel is "cut" at the bottom and you're not able to see the undermost parts of the tree when scrolling down. Same experience with pgAdmin at Windows 11 and Kubuntu 20.04.5. pgAdmin4 13 at same Windows-11-machine works normal.

**Comment by nikhil-mohite** [comment] 2022-10-18 04:20
Duplicate of #5402.

**Closed by nikhil-mohite** 2022-10-18 04:20 UTC
