### ISSUE TITLE
Bug: in pgAdmin v6.20, double click in search results throws error.

### ISSUE THREAD

**Issue by ecerichter** [pgadmin-org/pgadmin4#5916] opened 2023-03-07 13:41 UTC
**Describe the bug**

I’ve found another little "glitch" in pgAdmin 6.20 regarding search functionality:
 
1 – search object (of type column)
2 – double click the row (any column)
3 – get the error “Unable to locate this object in the browser.” at bottom of the window
 
See attached image for reference.

**Expected behavior**

The the object is selected in browser left pane. Hopefully, user can choose to close or not the search window

**Error message**

"Unable to locate the object in the browser."

**Screenshots**

![image](https://user-images.githubusercontent.com/2746089/223435854-8f09ab39-a96f-4926-94a8-f80993815465.png)

**Desktop (please complete the following information):**
 - OS: docker container
 - Version: 6.20
 - Mode: Server
 - Browser Edge, Chrome, Firefox
 - Package type: docker container

**Additional context**

nothing else.

**Comment by adityatoshniwal** [comment] 2023-03-08 12:55
Found one more related to this. Please check the screenshot. Connected to PG14 server, but on double click it is trying to locate in 9.6
<img width="1482" alt="image" src="https://user-images.githubusercontent.com/31855755/223718530-84821fe7-cb50-4d11-b7ba-5130e213f8a2.png">

**Comment by adityatoshniwal** [comment] 2023-03-13 08:34
Hi @ecerichter,

Are you getting the error everytime you open pgAdmin or it goes away after restarting pgAdmin?
I am not able to reproduce it anymore.

Thanks.

**Comment by ecerichter** [comment] 2023-03-13 13:05
I do run pgAdmin in Docker, so I just restart it when upgrading.
Never tried after restart if make any difference.
I’ll try today at noon, and let you know.

Regards,

ER

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Aditya ***@***.***>
Enviado:segunda-feira, 13 de março de 2023 05:34
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [pgadmin-org/pgadmin4] Bug: in pgAdmin v6.20, double click in search results throws error. (Issue #5916)


Hi @ecerichter<https://github.com/ecerichter>,

Are you getting the error everytime you open pgAdmin or it goes away after restarting pgAdmin?
I am not able to reproduce it anymore.

Thanks.

**Comment by ecerichter** [comment] 2023-03-14 16:15
Well, I’ve made a test, and restarting pgAdmin docker container made double click on search window work again.
I’m not sure which conditions lead to the fail.

Regards,

ER

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Aditya ***@***.***>
Enviado:segunda-feira, 13 de março de 2023 05:34
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [pgadmin-org/pgadmin4] Bug: in pgAdmin v6.20, double click in search results throws error. (Issue #5916)


Hi @ecerichter<https://github.com/ecerichter>,

Are you getting the error everytime you open pgAdmin or it goes away after restarting pgAdmin?
I am not able to reproduce it anymore.

Thanks.

**Comment by akshay-joshi** [comment] 2023-03-15 05:29
Closing issue as it is working fine as per the user's response.

**Comment by adityatoshniwal** [comment] 2023-04-04 07:04
Able to reproduce the issue, and fix is available. So re-opening the issue.

**Comment by FaharAbbasRizvi** [comment] 2023-04-06 05:11
Tested in the candidate build for v7.0.

**Closed by FaharAbbasRizvi** 2023-04-06 05:11 UTC
Labels: Bug, EDB Sprint 139
