### ISSUE TITLE
Error: Object not found - GONE

### ISSUE THREAD

**Issue by leejoys** [pgadmin-org/pgadmin4#7077] opened 2023-12-21 14:04 UTC
**Describe the bug**    
    
![p3](https://github.com/pgadmin-org/pgadmin4/assets/44557202/c5988b8b-c6a0-4d8c-9d6f-d1e2993519b1)    
![p4](https://github.com/pgadmin-org/pgadmin4/assets/44557202/f42c18a8-0443-48db-b009-a11fa7b9477b)    
![p5](https://github.com/pgadmin-org/pgadmin4/assets/44557202/ef1ee543-910b-4fb1-ab0b-2a2b8ea0e7ab)    

    
I get this error when working with just one table in the database, despite the fact that all the others are working fine and even for this table selects from the query console work fine.    
    
![pg1](https://github.com/pgadmin-org/pgadmin4/assets/44557202/13f6d515-add9-4205-bcda-374238dd5c05)    
![p2](https://github.com/pgadmin-org/pgadmin4/assets/44557202/c759e1a1-835e-498d-b068-af1a48965d1d)    

    
That is, its properties are not visible and you cannot use such options as Filtered rows, First/Last 100 rows, etc.    
    
**To Reproduce**    
    
1. Go to 'Properties or SQL tab for this table'    
or    
2. Click on 'View/Edit data of RMB menu of this table'    
3. See the error    
    
**Expected behavior**    
    
Any other tables works fine this way    
    
**Error message**    
**Screenshots**    
In the description^    
    

**Desktop (please complete the following information):**    
 - OS: Windows 10    
 - Version: 8.1    
 - Mode: Desktop    
    
**Additional context**    
    
I had this problem on an earlier version, but even after the update it remained.

**Comment by adityatoshniwal** [comment] 2023-12-22 07:05
Hi @leejoys,
Please share more details liks PostgreSQL version and possibly table DDL to help us reproduce the issue.

**Comment by leejoys** [comment] 2023-12-22 11:54
Sure. These errors are not shown in the log. 

Log:

Total spawn time to start the pgAdmin4 server: 0.026 Sec
2023-12-22 12:39:23,195: WARNING	werkzeug:	Werkzeug appears to be used in a production deployment. Consider switching to a production web server instead.

 * Serving Flask app 'pgadmin'
 * Debug mode: off

------------------------------------------
Total time taken to ping pgAdmin4 server: 76.072 Sec
------------------------------------------
Total launch time of pgAdmin4: 77.631 Sec
------------------------------------------
Application Server URL: http://127.0.0.1:42547/?key=*******
2023-12-22 12:40:16,566: ERROR	pgadmin:	Could not connect to server(#5) - 'SSL base'.
Error: connection failed: fe_sendauth: no password supplied

2023-12-22 12:50:11,349: ERROR	pgadmin:	Could not connect to server(#4) - 'SSH Stage base'.
Error: connection failed: fe_sendauth: no password supplied



Version: 

PostgreSQL 14.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 13.2.1 20231011 (Red Hat 13.2.1-4), 64-bit

DDL: 

CREATE TABLE public.prices (
    id integer NOT NULL,
    created_at integer NOT NULL,
    updated_at integer NOT NULL,
    price_min bigint NOT NULL,
    price_max bigint NOT NULL,
    item_id integer
);

CREATE SEQUENCE public.prices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

**Comment by adityatoshniwal** [comment] 2023-12-22 12:10
Hi @leejoys,
This table works fine for me. Can you try:
<img width="921" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/9ec391c6-69b3-4518-80e1-b312c768ecc2">

**Comment by leejoys** [comment] 2023-12-22 14:21
Thank you. Now everything works as it should. Could you give a little more detail about what it was and why your method worked?

**Comment by adityatoshniwal** [comment] 2023-12-23 09:19
> Thank you. Now everything works as it should. Could you give a little more detail about what it was and why your method worked?
> 
> Neither reconnecting to the server, nor even deleting the program and installing a new version helped.

You must dropped and recreated the table manually using SQL and so the OID of the table changed. Since pgAdmin is still referring to older OID, it says object not found.

This is not an issue. Closing.

**Closed by adityatoshniwal** 2023-12-23 09:19 UTC
Labels: Bug
